CREATE NONCLUSTERED INDEX [_dta_index_companies_20_763149764__K4_K2_K1_K9]
    ON [dbo].[companies]([archived] ASC, [company] ASC, [companyid] ASC, [showto] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

