CREATE NONCLUSTERED INDEX [_dta_index_savedexpenses_47_666537508__K47_K11_K18_K1]
    ON [dbo].[savedexpenses]([carid] ASC, [date] ASC, [claimid] ASC, [expenseid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

