CREATE NONCLUSTERED INDEX [IX_esr_assignments_employeeid_esrAssignID] ON [dbo].[esr_assignments] 
	(
		[employeeid] ASC,
		[esrAssignID] ASC
	)
	INCLUDE ( [AccrualPlan],
	[Active],
	[AssignmentAddressCountry],
	[AssignmentAddressCounty],
	[AssignmentAddressLine1],
	[AssignmentAddressLine2],
	[AssignmentAddressPostcode],
	[AssignmentAddressTown],
	[AssignmentCategory],
	[AssignmentID],
	[AssignmentLocation],
	[AssignmentNumber],
	[AssignmentStatus],
	[AvailabilitySchedule],
	[CreatedBy],
	[createdon],
	[EarliestAssignmentStartDate],
	[EmployeeCategory],
	[FinalAssignmentEndDate],
	[FlexibleWorkingPattern],
	[Grade],
	[GradeContractHours],
	[Group],
	[JobName],
	[JobRole],
	[LegalEntity],
	[ModifiedBy],
	[modifiedon],
	[NightWorkerOptOut],
	[NoOfSessions],
	[NormalHours],
	[NormalHoursFrequency],
	[OccupationCode],
	[Organisation],
	[PayrollName],
	[PayrollPayType],
	[PayrollPeriodType],
	[PositionName],
	[PrimaryAssignment],
	[ProjectedHireDate],
	[SessionsFrequency],
	[SupervisorAssignmentNumber],
	[SupervisorEmployeeNumber],
	[SupervisorFlag],
	[SupervisorFullName],
	[TAndAFlag],
	[VacancyID],
	[WorkPatternDetails],
	[WorkPatternStartDay]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]