CREATE NONCLUSTERED INDEX [_dta_index_employees_51_811918014__K1_2]
    ON [dbo].[employees]([employeeid] ASC)
    INCLUDE([username]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

