CREATE NONCLUSTERED INDEX [_dta_index_claims_base_51_5575058__K15_K3_K1_K7]
    ON [dbo].[claims_base]([submitted] ASC, [employeeid] ASC, [claimid] ASC, [paid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

