CREATE NONCLUSTERED INDEX [_dta_index_auditLog_15_1608717875__K9_K11_K2]
    ON [dbo].[auditLog]([datestamp] ASC, [field] ASC, [elementID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

