CREATE TABLE [dbo].[fields_base] (
    [fieldid]                UNIQUEIDENTIFIER CONSTRAINT [DF_fields_base_fieldid_new_1] DEFAULT (newid()) NOT NULL,
    [field]                  NVARCHAR (100)   COLLATE Latin1_General_CI_AS NOT NULL,
    [fieldtype]              NVARCHAR (2)     COLLATE Latin1_General_CI_AS NOT NULL,
    [description]            NVARCHAR (1000)  COLLATE Latin1_General_CI_AS NULL,
    [comment]                NVARCHAR (4000)  COLLATE Latin1_General_CI_AS NULL,
    [normalview]             BIT              CONSTRAINT [DF_fields_normalview] DEFAULT ((1)) NOT NULL,
    [idfield]                BIT              CONSTRAINT [DF_fields_idfield] DEFAULT ((0)) NOT NULL,
    [viewgroupid_old]        INT              CONSTRAINT [DF_fields_viewgroupid] DEFAULT ((1)) NULL,
    [genlist]                BIT              CONSTRAINT [DF_fields_genlist] DEFAULT ((0)) NOT NULL,
    [width]                  INT              CONSTRAINT [DF_fields_width] DEFAULT ((0)) NOT NULL,
    [cantotal]               BIT              CONSTRAINT [DF_fields_cantotal] DEFAULT ((0)) NOT NULL,
    [printout]               BIT              CONSTRAINT [DF_fields_printout] DEFAULT ((0)) NOT NULL,
    [valuelist]              BIT              CONSTRAINT [DF_fields_valuelist] DEFAULT ((0)) NOT NULL,
    [allowimport]            BIT              CONSTRAINT [DF_fields_allowimport] DEFAULT ((0)) NOT NULL,
    [mandatory]              BIT              CONSTRAINT [DF_fields_mandatory] DEFAULT ((0)) NOT NULL,
    [amendedon]              DATETIME         CONSTRAINT [DF_fields_amendedon] DEFAULT (getdate()) NOT NULL,
    [lookuptable]            UNIQUEIDENTIFIER NULL,
    [lookupfield]            UNIQUEIDENTIFIER NULL,
    [useforlookup]           BIT              CONSTRAINT [DF_fields_useforlookup] DEFAULT ((0)) NOT NULL,
    [workflowUpdate]         BIT              CONSTRAINT [DF_fields_base_workflowUpdate] DEFAULT ((0)) NOT NULL,
    [workflowSearch]         BIT              CONSTRAINT [DF_fields_base_workflowSearch] DEFAULT ((0)) NOT NULL,
    [length]                 INT              CONSTRAINT [DF_fields_base_length] DEFAULT ((0)) NOT NULL,
    [tableid]                UNIQUEIDENTIFIER NOT NULL,
    [viewgroupid]            UNIQUEIDENTIFIER NULL,
    [relabel]                BIT              CONSTRAINT [DF__fields_ba__relab__5A8C5FCB] DEFAULT ((0)) NOT NULL,
    [relabel_param]          NVARCHAR (150)   COLLATE Latin1_General_CI_AS NULL,
    [fieldid_old]            INT              NULL,
    [allowDuplicateChecking] BIT              CONSTRAINT [DF_fields_base_allowDuplicateChecking] DEFAULT ((0)) NOT NULL,
    [classPropertyName]      NVARCHAR (500)   NULL,
    [isForeignKey]           BIT              CONSTRAINT [DF_fields_base_isForeignKey] DEFAULT ((0)) NOT NULL,
    [relatedTable]           UNIQUEIDENTIFIER NULL,
	[associatedFieldForDuplicateChecking] [uniqueidentifier] NULL,
	[DuplicateCheckingSource] [tinyint] NULL,
	[DuplicateCheckingCalculation] [tinyint] NULL,
	[friendlyNameTo] [nvarchar](100) NULL
    CONSTRAINT [PK_fields_base] PRIMARY KEY NONCLUSTERED ([fieldid] ASC),
    [friendlyNameFrom] NVARCHAR(100) NULL, 
    [treeGroup] UNIQUEIDENTIFIER NULL, 
    CONSTRAINT [FK_fields_base_fields_base] FOREIGN KEY ([lookupfield]) REFERENCES [dbo].[fields_base] ([fieldid]),
    CONSTRAINT [FK_fields_base_relatedTable_tables_base] FOREIGN KEY ([relatedTable]) REFERENCES [dbo].[tables_base] ([tableid]),
    CONSTRAINT [FK_fields_base_tables_base] FOREIGN KEY ([tableid]) REFERENCES [dbo].[tables_base] ([tableid]) ON DELETE CASCADE,
    CONSTRAINT [FK_fields_base_tables_base1] FOREIGN KEY ([lookuptable]) REFERENCES [dbo].[tables_base] ([tableid]),
    CONSTRAINT [FK_fields_base_viewgroups] FOREIGN KEY ([viewgroupid]) REFERENCES [dbo].[viewgroups_base] ([viewgroupid])
);



