CREATE TABLE [dbo].[registeredusers] (
    [accountid]               INT            IDENTITY (355, 1) NOT NULL,
    [companyname]             NVARCHAR (50)  COLLATE Latin1_General_CI_AS NOT NULL,
    [companyid]               NVARCHAR (50)  COLLATE Latin1_General_CI_AS NOT NULL,
    [contact]                 NVARCHAR (50)  COLLATE Latin1_General_CI_AS NOT NULL,
    [nousers]                 INT            NOT NULL,
    [expiry]                  DATETIME       NOT NULL,
    [accounttype]             TINYINT        CONSTRAINT [DF_registeredusers_accounttype] DEFAULT ((1)) NOT NULL,
    [dbserver]                INT            NULL,
    [dbname]                  NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
    [dbusername]              NVARCHAR (100) NOT NULL,
    [dbpassword]              NVARCHAR (200) COLLATE Latin1_General_CI_AS NULL,
    [resellerid]              INT            NULL,
    [archived]                BIT            CONSTRAINT [DF_registeredusers_archived] DEFAULT ((0)) NOT NULL,
    [autologEnabled]          BIT            CONSTRAINT [DF_registeredusers_autologEnabled] DEFAULT ((1)) NOT NULL,
    [quickEntryFormsEnabled]  BIT            CONSTRAINT [DF_registeredusers_quickEntryFormsEnabled] DEFAULT ((1)) NOT NULL,
    [employeeSearchEnabled]   BIT            CONSTRAINT [DF_registeredusers_employeeSearchEnabled] DEFAULT ((1)) NOT NULL,
    [hotelReviewsEnabled]     BIT            CONSTRAINT [DF_registeredusers_hotelReviewsEnabled] DEFAULT ((1)) NOT NULL,
    [advancesEnabled]         BIT            CONSTRAINT [DF_registeredusers_advancesEnabled] DEFAULT ((1)) NOT NULL,
    [postcodeAnyWhereEnabled] BIT            CONSTRAINT [DF_registeredusers_postcodeAnyWhereEnabled] DEFAULT ((1)) NOT NULL,
    [corporateCardsEnabled]   BIT            CONSTRAINT [DF_registeredusers_corporateCardsEnabled] DEFAULT ((1)) NOT NULL,
    [expensesConnectLicenses] INT            NULL,
    [reportDatabaseID]        INT            NULL,
    [isNHSCustomer]           BIT            CONSTRAINT [DF_registeredusers_isNHSCustomer] DEFAULT ((0)) NOT NULL,
    [contactHelpDeskAllowed]  BIT            CONSTRAINT [DF_registeredusers_contactHelpDeskAllowed] DEFAULT ((1)) NOT NULL,
    [postcodeAnywhereKey]     NVARCHAR (200) COLLATE Latin1_General_CI_AS NULL,
    [licencedUsers]           NVARCHAR (150) NULL,
    [mapsEnabled]             BIT            ,
    [ReceiptServiceEnabled]   BIT            NOT NULL,
	[ValidationServiceEnabled]					BIT            NOT NULL,
    [DaysToWaitBeforeSentEnvelopeIsMissing]		INT            NULL DEFAULT(NULL),
	[SingleSignOnEnabled]     BIT			 NOT NULL,	-- Obsolete, moved to a LicencedElement
	[addressLookupProvider]						TINYINT			CONSTRAINT CK_registeredusers_addressLookupProvider CHECK (addressLookupProvider IN (0, 1, 2)) CONSTRAINT DF_registeredusers_addressLookupProvider DEFAULT 0 NOT NULL,
	[addressLookupsChargeable]					BIT				CONSTRAINT DF_registeredusers_addressLookupsChargeable DEFAULT 0 NOT NULL,
	[addressLookupPsmaAgreement]				BIT				CONSTRAINT DF_registeredusers_addressLookupPsmaAgreement DEFAULT 0 NOT NULL,
	[addressInternationalLookupsAndCoordinates]	BIT				CONSTRAINT DF_registeredusers_addressDistanceLookupEnableCoordinates DEFAULT 0 NOT NULL,
	[addressLookupsRemaining]					INT				CONSTRAINT DF_registeredusers_addressLookupsRemaining DEFAULT 0 NULL,
	[addressDistanceLookupsRemaining]			INT				CONSTRAINT DF_registeredusers_addressDistanceLookupsRemaining DEFAULT 0 NULL,
	[licenceType]								TINYINT			CONSTRAINT CK_registeredusers_licenceType CHECK (licenceType IN (1, 2)) NULL,
    [annualContract]							BIT				CONSTRAINT DF_registeredusers_annualContract DEFAULT 0 NOT NULL,
    [renewalDate]								NVARCHAR(5)		NULL,
    [contactEmail]								NVARCHAR(500)	NULL,
	[PaymentServiceEnabled] BIT CONSTRAINT DF_registeredusers_paymentServiceEnabled DEFAULT 0 NOT NULL,
	[FundLimit] DECIMAL(18, 2) CONSTRAINT DF_registeredusers_FundLimit DEFAULT 0 NULL,
	[DVLALookUpKey] NVARCHAR(200) NULL, 
	[PostcodeAnywherePaymentServiceKey]         NVARCHAR(200) NULL,
    CONSTRAINT [PK_registeredusers] PRIMARY KEY CLUSTERED ([accountid] ASC)
);
