CREATE PROCEDURE [dbo].[APIgetEsrPersons]
	@esrPersonId bigint 
AS
BEGIN
	IF @esrPersonId = 0
	BEGIN
		SELECT [ESRPersonId]
			  ,[EffectiveStartDate]
			  ,[EffectiveEndDate]
			  ,[EmployeeNumber]
			  ,[Title]
			  ,[LastName]
			  ,[FirstName]
			  ,[MiddleNames]
			  ,[MaidenName]
			  ,[PreferredName]
			  ,[PreviousLastName]
			  ,[Gender]
			  ,[DateOfBirth]
			  ,[NINumber]
			  ,[NHSUniqueId]
			  ,[HireDate]
			  ,[ActualTerminationDate]
			  ,[TerminationReason]
			  ,[EmployeeStatusFlag]
			  ,[WTROptOut]
			  ,[WTROptOutDate]
			  ,[EthnicOrigin]
			  ,[MaritalStatus]
			  ,[CountryOfBirth]
			  ,[PreviousEmployer]
			  ,[PreviousEmployerType]
			  ,[CSD3Months]
			  ,[CSD12Months]
			  ,[NHSCRSUUID]
			  ,[SystemPersonType]
			  ,[UserPersonType]
			  ,[OfficeEmailAddress]
			  ,[NHSStartDate]
			  ,[ESRLastUpdateDate]
			  ,[DisabilityFlag]
			  ,[LegacyPayrollNumber]
			  ,[Nationality]
		  FROM [dbo].[ESRPersons]
	END
	ELSE
	BEGIN
		SELECT [ESRPersonId]
			  ,[EffectiveStartDate]
			  ,[EffectiveEndDate]
			  ,[EmployeeNumber]
			  ,[Title]
			  ,[LastName]
			  ,[FirstName]
			  ,[MiddleNames]
			  ,[MaidenName]
			  ,[PreferredName]
			  ,[PreviousLastName]
			  ,[Gender]
			  ,[DateOfBirth]
			  ,[NINumber]
			  ,[NHSUniqueId]
			  ,[HireDate]
			  ,[ActualTerminationDate]
			  ,[TerminationReason]
			  ,[EmployeeStatusFlag]
			  ,[WTROptOut]
			  ,[WTROptOutDate]
			  ,[EthnicOrigin]
			  ,[MaritalStatus]
			  ,[CountryOfBirth]
			  ,[PreviousEmployer]
			  ,[PreviousEmployerType]
			  ,[CSD3Months]
			  ,[CSD12Months]
			  ,[NHSCRSUUID]
			  ,[SystemPersonType]
			  ,[UserPersonType]
			  ,[OfficeEmailAddress]
			  ,[NHSStartDate]
			  ,[ESRLastUpdateDate]
			  ,[DisabilityFlag]
			  ,[LegacyPayrollNumber]
			  ,[Nationality]
		  FROM [dbo].[ESRPersons]
		  WHERE [ESRPersonId] = @esrPersonId;
	END
END

