CREATE PROCEDURE [dbo].[APIgetCars]
	@carid int 
	
AS
BEGIN
	IF @carid = 0
		BEGIN
			SELECT [carid]
		  ,[employeeid]
		  ,[startdate]
		  ,[enddate]
		  ,[make]
		  ,[model]
		  ,[registration]
		  ,[mileageid]
		  ,[cartypeid]
		  ,[active]
		  ,[odometer]
		  ,[fuelcard]
		  ,[endodometer]
		  ,[taxexpiry]
		  ,[taxlastchecked]
		  ,[taxcheckedby]
		  ,[mottestnumber]
		  ,[motlastchecked]
		  ,[motcheckedby]
		  ,[motexpiry]
		  ,[insurancenumber]
		  ,[insuranceexpiry]
		  ,[insurancelastchecked]
		  ,[insurancecheckedby]
		  ,[serviceexpiry]
		  ,[servicelastchecked]
		  ,[servicecheckedby]
		  ,[CreatedOn]
		  ,[CreatedBy]
		  ,[ModifiedOn]
		  ,[ModifiedBy]
		  ,[default_unit]
		  ,[enginesize]
		  ,[approved]
		  ,[exemptFromHomeToOffice]
		  ,[taxAttachID]
		  ,[MOTAttachID]
		  ,[insuranceAttachID]
		  ,[serviceAttachID]
	  FROM [dbo].[cars]
		END
	ELSE
		BEGIN
			SELECT [carid]
		  ,[employeeid]
		  ,[startdate]
		  ,[enddate]
		  ,[make]
		  ,[model]
		  ,[registration]
		  ,[mileageid]
		  ,[cartypeid]
		  ,[active]
		  ,[odometer]
		  ,[fuelcard]
		  ,[endodometer]
		  ,[taxexpiry]
		  ,[taxlastchecked]
		  ,[taxcheckedby]
		  ,[mottestnumber]
		  ,[motlastchecked]
		  ,[motcheckedby]
		  ,[motexpiry]
		  ,[insurancenumber]
		  ,[insuranceexpiry]
		  ,[insurancelastchecked]
		  ,[insurancecheckedby]
		  ,[serviceexpiry]
		  ,[servicelastchecked]
		  ,[servicecheckedby]
		  ,[CreatedOn]
		  ,[CreatedBy]
		  ,[ModifiedOn]
		  ,[ModifiedBy]
		  ,[default_unit]
		  ,[enginesize]
		  ,[approved]
		  ,[exemptFromHomeToOffice]
		  ,[taxAttachID]
		  ,[MOTAttachID]
		  ,[insuranceAttachID]
		  ,[serviceAttachID]
	  FROM [dbo].[cars]
	  WHERE carid = @carid
		END
END