CREATE PROCEDURE [dbo].[DuplicateExpense]
	@expenseID int

AS
	DECLARE @newExpenseID int;
	DECLARE @contraExpenseID int;
	DECLARE @oldValidationProgress int;

			SELECT @oldValidationProgress = ValidationProgress from dbo.savedexpenses where expenseid = @expenseID
			IF (@oldValidationProgress >= 20)
			BEGIN
				SET @oldValidationProgress = @oldValidationProgress + 10;
			END

			UPDATE [dbo].[savedexpenses]
			SET [Edited] = 1 , [returned] = 0, [ValidationProgress] = -4, [tempallow] = 1
			WHERE expenseid = @expenseID
				-- the positive
			INSERT INTO [dbo].[savedexpenses]
			   ([bmiles]
			   ,[pmiles]
			   ,[reason]
			   ,[receipt]
			   ,[net]
			   ,[vat]
			   ,[total]
			   ,[subcatid]
			   ,[date]
			   ,[staff]
			   ,[others]
			   ,[companyid]
			   ,[returned]
			   ,[home]
			   ,[refnum]
			   ,[claimid]
			   ,[plitres]
			   ,[blitres]
			   ,[allowanceamount]
			   ,[currencyid]
			   ,[attendees]
			   ,[tip]
			   ,[countryid]
			   ,[foreignvat]
			   ,[convertedtotal]
			   ,[exchangerate]
			   ,[tempallow]
			   ,[reasonid]
			   ,[normalreceipt]
			   ,[receiptattached]
			   ,[allowancestartdate]
			   ,[allowanceenddate]
			   ,[carid]
			   ,[allowancededuct]
			   ,[allowanceid]
			   ,[nonights]
			   ,[quantity]
			   ,[directors]
			   ,[amountpayable]
			   ,[hotelid]
			   ,[primaryitem]
			   ,[norooms]
			   ,[vatnumber]
			   ,[personalguests]
			   ,[remoteworkers]
			   ,[accountcode]
			   ,[pencepermile]
			   ,[basecurrency]
			   ,[globalexchangerate]
			   ,[globalbasecurrency]
			   ,[globaltotal]
			   ,[itemtype]
			   ,[CreatedOn]
			   ,[CreatedBy]
			   ,[ModifiedOn]
			   ,[ModifiedBy]
			   ,[mileageid]
			   ,[transactionid]
			   ,[journey_unit]
			   ,[esrAssignID]
			   ,[AssignmentNumber]
			   ,[CacheExpiry]
			   ,[hometooffice_deduction_method]
			   ,[addedAsMobileItem]
			   ,[addedByDeviceTypeId]
			   ,[itemCheckerId]
			   ,[organisationIdentifier]
			   ,[itemCheckerTeamId]
			   ,[ValidationProgress]
			   ,[ValidationCount]
			   ,[OriginalExpenseId]
			   ,[BankAccountId])
			   SELECT 
			   [bmiles]
			   ,[pmiles]
			   ,[reason]
			   ,[receipt]
			   ,[net]
			   ,[vat]
			   ,[total]
			   ,[subcatid]
			   ,[date]
			   ,[staff]
			   ,[others]
			   ,[companyid]
			   ,[returned]
			   ,[home]
			   ,[refnum]
			   , [claimid]
			   ,[plitres]
			   ,[blitres]
			   ,[allowanceamount]
			   ,[currencyid]
			   ,[attendees]
			   ,[tip]
			   ,[countryid]
			   ,[foreignvat]
			   ,[convertedtotal]
			   ,[exchangerate]
			   ,0
			   ,[reasonid]
			   ,[normalreceipt]
			   ,[receiptattached]
			   ,[allowancestartdate]
			   ,[allowanceenddate]
			   ,[carid]
			   ,[allowancededuct]
			   ,[allowanceid]
			   ,[nonights]
			   ,[quantity]
			   ,[directors]
			   ,[amountpayable]
			   ,[hotelid]
			   ,[primaryitem]
			   ,[norooms]
			   ,[vatnumber]
			   ,[personalguests]
			   ,[remoteworkers]
			   ,[accountcode]
			   ,[pencepermile]
			   ,[basecurrency]
			   ,[globalexchangerate]
			   ,[globalbasecurrency]
			   ,[globaltotal]
			   ,[itemtype]
			   ,[CreatedOn]
			   ,[CreatedBy]
			   ,[ModifiedOn]
			   ,[ModifiedBy]
			   ,[mileageid]
			   ,[transactionid]
			   ,[journey_unit]
			   ,[esrAssignID]
			   ,[AssignmentNumber]
			   ,[CacheExpiry]
			   ,[hometooffice_deduction_method]
			   ,[addedAsMobileItem]
			   ,[addedByDeviceTypeId]
			   ,[itemCheckerId]
			   ,[organisationIdentifier]
			   ,[itemCheckerTeamId]
			   ,@oldValidationProgress
			   ,[ValidationCount]
			   ,expenseid
			   ,CASE BankAccountId
                WHEN 0 THEN NULL
                ELSE BankAccountId END As BankAccountId


			   FROM savedexpenses where expenseid = @expenseID
			   SET @newExpenseID = SCOPE_IDENTITY();

			   INSERT INTO ReceiptOwnership (ReceiptId, SavedExpenseId)
				SELECT ReceiptId, @newExpenseID FROM ReceiptOwnership WHERE SavedExpenseId = @expenseID

				INSERT INTO ExpenseValidationResults ([ExpenseId]
				   ,[CriterionId]
				   ,[ValidationStatusBusiness]
				   ,[ValidationStatusVAT]
				   ,[PossiblyFraudulent]
				   ,[ValidationCompleted]
				   ,[Comments]
				   ,[Data]
				   ,[MatchingResult])
				SELECT @newExpenseID
				   ,[CriterionId]
				   ,[ValidationStatusBusiness]
				   ,[ValidationStatusVAT]
				   ,[PossiblyFraudulent]
				   ,[ValidationCompleted]
				   ,[Comments]
				   ,[Data]
				   ,[MatchingResult] 
				FROM dbo.ExpenseValidationResults WHERE expenseId = @expenseId


				-- the negative
			INSERT INTO [dbo].[savedexpenses]
			   ([bmiles]
			   ,[pmiles]
			   ,[reason]
			   ,[receipt]
			   ,[net] 
			   ,[vat]
			   ,[total]
			   ,[subcatid]
			   ,[date]
			   ,[staff]
			   ,[others]
			   ,[companyid]
			   ,[returned]
			   ,[home]
			   ,[refnum]
			   ,[claimid]
			   ,[plitres]
			   ,[blitres]
			   ,[allowanceamount]
			   ,[currencyid]
			   ,[attendees]
			   ,[tip]
			   ,[countryid]
			   ,[foreignvat]
			   ,[convertedtotal]
			   ,[exchangerate]
			   ,[tempallow]
			   ,[reasonid]
			   ,[normalreceipt]
			   ,[receiptattached]
			   ,[allowancestartdate]
			   ,[allowanceenddate]
			   ,[carid]
			   ,[allowancededuct]
			   ,[allowanceid]
			   ,[nonights]
			   ,[quantity]
			   ,[directors]
			   ,[amountpayable]
			   ,[hotelid]
			   ,[primaryitem]
			   ,[norooms]
			   ,[vatnumber]
			   ,[personalguests]
			   ,[remoteworkers]
			   ,[accountcode]
			   ,[pencepermile]
			   ,[basecurrency]
			   ,[globalexchangerate]
			   ,[globalbasecurrency]
			   ,[globaltotal]
			   ,[itemtype]
			   ,[CreatedOn]
			   ,[CreatedBy]
			   ,[ModifiedOn]
			   ,[ModifiedBy]
			   ,[mileageid]
			   ,[transactionid]
			   ,[journey_unit]
			   ,[esrAssignID]
			   ,[AssignmentNumber]
			   ,[CacheExpiry]
			   ,[hometooffice_deduction_method]
			   ,[addedAsMobileItem]
			   ,[addedByDeviceTypeId]
			   ,[itemCheckerId]
			   ,[organisationIdentifier]
			   ,[itemCheckerTeamId]
			   ,[ValidationProgress]
			   ,[ValidationCount]
			   ,[OriginalExpenseID]
			   ,[BankAccountId]
			   ,[Edited])
			   SELECT 
			   [bmiles]
			   ,[pmiles]
			   ,[reason] + ' - Contra entry from previously paid claim.'
			   ,[receipt]
			   ,[net] * -1
			   ,[vat] * -1
			   ,[total] * -1
			   ,[subcatid]
			   ,[date]
			   ,[staff]
			   ,[others]
			   ,[companyid]
			   ,0
			   ,[home]
			   ,[refnum]
			   ,[claimid]
			   ,[plitres]
			   ,[blitres]
			   ,[allowanceamount] * -1
			   ,[currencyid]
			   ,[attendees]
			   ,[tip] * -1
			   ,[countryid]
			   ,[foreignvat] * -1
			   ,[convertedtotal] * -1
			   ,[exchangerate]
			   ,1
			   ,[reasonid]
			   ,[normalreceipt]
			   ,[receiptattached]
			   ,[allowancestartdate]
			   ,[allowanceenddate]
			   ,[carid]
			   ,[allowancededuct] * -1
			   ,[allowanceid]
			   ,[nonights]
			   ,[quantity]
			   ,[directors]
			   ,[amountpayable] * -1
			   ,[hotelid]
			   ,[primaryitem]
			   ,[norooms]
			   ,[vatnumber]
			   ,[personalguests]
			   ,[remoteworkers]
			   ,[accountcode]
			   ,[pencepermile]
			   ,[basecurrency]
			   ,[globalexchangerate]
			   ,[globalbasecurrency]
			   ,[globaltotal] * -1
			   ,[itemtype]
			   ,[CreatedOn]
			   ,[CreatedBy]
			   ,[ModifiedOn]
			   ,[ModifiedBy]
			   ,[mileageid]
			   ,[transactionid]
			   ,[journey_unit]
			   ,[esrAssignID]
			   ,[AssignmentNumber]
			   ,[CacheExpiry]
			   ,[hometooffice_deduction_method]
			   ,[addedAsMobileItem]
			   ,[addedByDeviceTypeId]
			   ,[itemCheckerId]
			   ,[organisationIdentifier]
			   ,[itemCheckerTeamId]
			   ,-4
			   ,[ValidationCount]
			   ,expenseid		
			   ,CASE BankAccountId
			    WHEN 0 THEN NULL
			    ELSE BankAccountId END As BankAccountId		
			   ,1
			   FROM savedexpenses where expenseid = @expenseID
			   
			   SET @contraExpenseID = SCOPE_IDENTITY();
			   INSERT INTO ReceiptOwnership (ReceiptId, SavedExpenseId)
				SELECT ReceiptId, @contraExpenseID FROM ReceiptOwnership WHERE SavedExpenseId = @expenseID
			   INSERT INTO [dbo].[savedexpenses_costcodes]
			   ([expenseid]
			   ,[departmentid]
			   ,[costcodeid]
			   ,[percentused]
			   ,[projectcodeid])
				SELECT @contraExpenseID
			   ,[departmentid]
			   ,[costcodeid]
			   ,[percentused]
			   ,[projectcodeid]
			   FROM dbo.savedexpenses_costcodes where expenseid = @expenseID

			   INSERT INTO [dbo].[savedexpenses_costcodes]
			   ([expenseid]
			   ,[departmentid]
			   ,[costcodeid]
			   ,[percentused]
			   ,[projectcodeid])
				SELECT @newExpenseID
			   ,[departmentid]
			   ,[costcodeid]
			   ,[percentused]
			   ,[projectcodeid]
			   FROM dbo.savedexpenses_costcodes where expenseid = @expenseID

RETURN @newExpenseID;
