CREATE PROCEDURE [dbo].[getEsrAssignments]
	@empId int = null
AS

	SELECT [employeeid]
		  ,[AssignmentID]
		  ,[AssignmentNumber]
		  ,[EarliestAssignmentStartDate]
		  ,[FinalAssignmentEndDate]
		  ,[AssignmentStatus]
		  ,[PayrollPayType]
		  ,[PayrollName]
		  ,[PayrollPeriodType]
		  ,[AssignmentAddressLine1]
		  ,[AssignmentAddressLine2]
		  ,[AssignmentAddressTown]
		  ,[AssignmentAddressCounty]
		  ,[AssignmentAddressPostcode]
		  ,[AssignmentAddressCountry]
		  ,[SupervisorFlag]
		  ,[SupervisorAssignmentNumber]
		  ,[SupervisorEmployeeNumber]
		  ,[SupervisorFullName]
		  ,[AccrualPlan]
		  ,[EmployeeCategory]
		  ,[AssignmentCategory]
		  ,[PrimaryAssignment]
		  ,[PrimaryAssignmentString]
		  ,[NormalHours]
		  ,[NormalHoursFrequency]
		  ,[GradeContractHours]
		  ,[NoOfSessions]
		  ,[SessionsFrequency]
		  ,[WorkPatternDetails]
		  ,[WorkPatternStartDay]
		  ,[FlexibleWorkingPattern]
		  ,[AvailabilitySchedule]
		  ,[Organisation]
		  ,[LegalEntity]
		  ,[PositionName]
		  ,[JobRole]
		  ,[OccupationCode]
		  ,[AssignmentLocation]
		  ,[Grade]
		  ,[JobName]
		  ,[Group]
		  ,[TAndAFlag]
		  ,[NightWorkerOptOut]
		  ,[ProjectedHireDate]
		  ,[VacancyID]
		  ,[createdon]
		  ,[modifiedon]
		  ,[esrAssignID]
		  ,[Active]
		  ,[CreatedBy]
		  ,[ModifiedBy]
		  ,[ESRPersonId]
		  ,[AssignmentType]
		  ,[EffectiveStartDate]
		  ,[EffectiveEndDate]
		  ,[SystemAssignmentStatus]
		  ,[EmployeeStatusFlag]
		  ,[ESRLocationId]
		  ,[SupervisorPersonId]
		  ,[SupervisorAssignmentId]
		  ,[DepartmentManagerAssignmentId]
		  ,[FTE]
		  ,[ESROrganisationId]
		  ,[ESRPositionId]
		  ,[GradeStep]
		  ,[StartDateInGrade]
		  ,[AnnualSalaryValue]
		  ,[ContractEndDate]
		  ,[IncrementDate]
		  ,[MaximumPartTimeFlag]
		  ,[AFCFlag]
		  ,[ESRLastUpdate]
		  ,[LastWorkingDay]
		  ,[eKSFSpinalPoint]
		  ,[ManagerFlag]
		  ,[SupervisorEsrAssignID]
		  ,[SignOffOwner]
	FROM
		esr_assignments
	WHERE
		@empId is null
		or employeeid = @empId
	ORDER BY
		PrimaryAssignment desc,
		AssignmentNumber,
		AssignmentID desc,
		esrAssignID desc
		
RETURN 0
