ALTER TABLE [dbo].[help_text_new]
    ADD CONSTRAINT [PK_help_text_new] PRIMARY KEY CLUSTERED ([helpid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

