ALTER TABLE [dbo].[reportcolumns]
    ADD CONSTRAINT [PK_reportcolumns_1] PRIMARY KEY NONCLUSTERED ([reportcolumnid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

