ALTER TABLE [dbo].[reports_common_columns]
    ADD CONSTRAINT [PK_reports_common_columns] PRIMARY KEY NONCLUSTERED ([tableid] ASC, [fieldid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

