namespace DutyOfCareAPI.DutyOfCare
{
    /// <summary>
    /// Response class for GetConsentPortalAccess API
    /// </summary>
    public class GetConsentPortalAccessResponse
    {       
        /// <summary>
        /// Gets or sets the  Security Code required to access consent portal  
        /// </summary>
        public string SecurityCode { get; set; }

        /// <summary>
        /// Gets or sets the DriverId generated by consent portal when a request is submitted
        /// </summary>
        public long DriverId { get; set; }

        /// <summary>
        /// Gets or sets the response message from api
        /// </summary>
        public string ResponseMessage { get; set; }


        /// <summary>
        /// Gets or sets the response code from api
        /// </summary>
        public string ResponseCode { get; set; }

        /// <summary>
        /// Create a new instance of <see cref="GetConsentPortalAccessResponse"/>  sentPortalAccessResponse class.
        /// </summary>
        public GetConsentPortalAccessResponse()
        {
        }

        /// <summary>
        /// Create a new instance of <see cref="GetConsentPortalAccessResponse"/> class and initialse the Security code, driver id and response messages.
        /// </summary>
        /// <param name="securityCode">Security code returned by licence check API, used to access licence check portal</param>
        /// <param name="driverId">Id Generated by Licence Check portal for the valid driver information request</param>
        /// <param name="responseMessage">Response message returned by licence check portal</param>
        /// <param name="responseCode">Response code returned by licence check portal</param>
        public GetConsentPortalAccessResponse(string securityCode, long driverId,string responseMessage, string responseCode)
        {
            this.SecurityCode = securityCode;
            this.DriverId = driverId;
            this.ResponseMessage = responseMessage;
            this.ResponseCode = responseCode;
        }  
    }
}