ALTER TABLE [dbo].[elementsBase]
    ADD CONSTRAINT [IX_elementsBase] UNIQUE NONCLUSTERED ([elementName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

