ALTER TABLE [dbo].[administrators]
    ADD CONSTRAINT [PK_administrators] PRIMARY KEY CLUSTERED ([administratorid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

