ALTER TABLE [dbo].[card_providers]
    ADD CONSTRAINT [PK_card_providers] PRIMARY KEY CLUSTERED ([cardproviderid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

