ALTER TABLE [dbo].[databases]
    ADD CONSTRAINT [PK_databases] PRIMARY KEY CLUSTERED ([databaseID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

