ALTER TABLE [dbo].[emailNotifications]
    ADD CONSTRAINT [PK_emailNotifications] PRIMARY KEY CLUSTERED ([emailNotificationID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

