ALTER TABLE [dbo].[elementsBase]
    ADD CONSTRAINT [PK_elements_base] PRIMARY KEY CLUSTERED ([elementID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

