ALTER TABLE [dbo].[global_faqs]
    ADD CONSTRAINT [PK_faqs] PRIMARY KEY CLUSTERED ([faqid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

