ALTER TABLE [dbo].[fields_base]
    ADD CONSTRAINT [PK_fields_base] PRIMARY KEY CLUSTERED ([fieldid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

