ALTER TABLE [dbo].[global_countries]
    ADD CONSTRAINT [PK_global_countries] PRIMARY KEY CLUSTERED ([globalcountryid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

