ALTER TABLE [dbo].[global_currencies]
    ADD CONSTRAINT [PK_global_currencies] PRIMARY KEY CLUSTERED ([globalcurrencyid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

