ALTER TABLE [dbo].[globalESRElements]
    ADD CONSTRAINT [PK_globalESRElements] PRIMARY KEY CLUSTERED ([globalESRElementID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

