ALTER TABLE [dbo].[hotels]
    ADD CONSTRAINT [PK_hotels] PRIMARY KEY CLUSTERED ([hotelid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

