ALTER TABLE [dbo].[hostnames]
    ADD CONSTRAINT [PK_hostnames] PRIMARY KEY CLUSTERED ([hostnameID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

