ALTER TABLE [dbo].[hotel_reviews]
    ADD CONSTRAINT [PK_hotel_review] PRIMARY KEY CLUSTERED ([reviewid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

