ALTER TABLE [dbo].[joinbreakdown_base]
    ADD CONSTRAINT [PK_joinbreakdown] PRIMARY KEY CLUSTERED ([joinbreakdownid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

