ALTER TABLE [dbo].[languages]
    ADD CONSTRAINT [PK_languages] PRIMARY KEY CLUSTERED ([phraseid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

