ALTER TABLE [dbo].[moduleElementBase]
    ADD CONSTRAINT [PK_moduleElementBase] PRIMARY KEY CLUSTERED ([moduleID] ASC, [elementID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

