ALTER TABLE [dbo].[mime_headers]
    ADD CONSTRAINT [PK_mime_headers] PRIMARY KEY CLUSTERED ([mimeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

