ALTER TABLE [dbo].[mobileDeviceTypes]
    ADD CONSTRAINT [PK_mobileDeviceTypes] PRIMARY KEY CLUSTERED ([mobileDeviceTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

