ALTER TABLE [dbo].[menu_structure_base]
    ADD CONSTRAINT [PK_menu_structure] PRIMARY KEY CLUSTERED ([menuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

