ALTER TABLE [dbo].[moduleBase]
    ADD CONSTRAINT [PK_module_base] PRIMARY KEY CLUSTERED ([moduleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

