ALTER TABLE [dbo].[resellers]
    ADD CONSTRAINT [PK_resellers] PRIMARY KEY CLUSTERED ([resellerid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

