ALTER TABLE [dbo].[registeredusers]
    ADD CONSTRAINT [PK_registeredusers] PRIMARY KEY CLUSTERED ([accountid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

