ALTER TABLE [dbo].[tables_base]
    ADD CONSTRAINT [PK_tables] PRIMARY KEY CLUSTERED ([tableid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

