ALTER TABLE [dbo].[viewgroups_base]
    ADD CONSTRAINT [PK_viewgroups] PRIMARY KEY CLUSTERED ([viewgroupid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

