'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Framework2006

    Partial Public Class ContractHistory

        '''<summary>
        '''lnkCDnav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCDnav As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCAnav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCAnav As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCPnav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCPnav As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkIDnav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkIDnav As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkIFnav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkIFnav As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkNSnav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkNSnav As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkLCnav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkLCnav As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCHnav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCHnav As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkRTnav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkRTnav As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkRPnav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkRPnav As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''litHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litHistory As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''cmdClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdClose As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As frameworkWebApp.FWMaster
            Get
                Return CType(MyBase.Master, frameworkWebApp.FWMaster)
            End Get
        End Property
    End Class
End Namespace
