// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Auto_Tests.UIMaps.CorporateCardsUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public partial class CorporateCardsUIMap
    {
        
        /// <summary>
        /// SearchForEmployee - Use 'SearchForEmployeeParams' to pass parameters into this method.
        /// </summary>
        public void SearchForEmployee()
        {
            #region Variable Declarations
            HtmlEdit uIUsernameEdit = this.UIHttpstestingselexpenWindow.UIHttpstestingselexpenDocument.UIUsernameEdit;
            HtmlInputButton uICtl00contentmaincmdoButton = this.UIHttpstestingselexpenWindow.UIHttpstestingselexpenDocument.UICtl00contentmaincmdoButton;
            #endregion

            // Type 'CodedUIAdmin' in 'Username' text box
            uIUsernameEdit.Text = this.SearchForEmployeeParams.UIUsernameEditText;

            // Click 'ctl00$contentmain$cmdok' button
            Mouse.Click(uICtl00contentmaincmdoButton, new Point(10, 17));
        }
        
        /// <summary>
        /// ClickEmployeeEditIcon
        /// </summary>
        public void ClickEmployeeEditIcon()
        {
            #region Variable Declarations
            HtmlImage uIEditImage = this.UIEmployeesWindowsInteWindow.UIEmployeesDocument.UITbl_gridEmployees_32Row.UIEditImage;
            #endregion

            // Click 'Edit' image
            Mouse.Click(uIEditImage, new Point(9, 8));
        }
        
        /// <summary>
        /// SelectCorporateCardsPage
        /// </summary>
        public void SelectCorporateCardsPage()
        {
            #region Variable Declarations
            HtmlHyperlink uICorporateCardsHyperlink = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UICorporateCardsHyperlink;
            #endregion

            // Click 'Corporate Cards' link
            Mouse.Click(uICorporateCardsHyperlink, new Point(85, 7));
        }
        
        /// <summary>
        /// ValidateNoCorporateCardsExist - Use 'ValidateNoCorporateCardsExistExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ValidateNoCorporateCardsExist()
        {
            #region Variable Declarations
            HtmlCell uITherearenocorporatecCell = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UITbl_gridCardsTable.UITherearenocorporatecCell;
            #endregion

            // Verify that 'There are no corporate cards defined for' cell's property 'InnerText' equals 'There are no corporate cards defined for this employee'
            Assert.AreEqual(this.ValidateNoCorporateCardsExistExpectedValues.UITherearenocorporatecCellInnerText, uITherearenocorporatecCell.InnerText);
        }
        
        /// <summary>
        /// ClickAddCorporateCardLink
        /// </summary>
        public void ClickAddCorporateCardLink()
        {
            #region Variable Declarations
            HtmlHyperlink uIAddCorporateCardHyperlink = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UIAddCorporateCardPane.UIAddCorporateCardHyperlink;
            #endregion

            // Click 'Add Corporate Card' link
            Mouse.Click(uIAddCorporateCardHyperlink, new Point(34, 13));
        }
        
        /// <summary>
        /// SelectFirstCorporateCardFromList - Use 'SelectFirstCorporateCardFromListParams' to pass parameters into this method.
        /// </summary>
        public void SelectFirstCorporateCardFromList()
        {
            #region Variable Declarations
            HtmlComboBox uICardProviderComboBox = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UICardProviderComboBox;
            #endregion

            // Select 'Barclaycard' in 'Card Provider' combo box
            uICardProviderComboBox.SelectedItem = this.SelectFirstCorporateCardFromListParams.UICardProviderComboBoxSelectedItem;
        }
        
        /// <summary>
        /// SelectSecondCorporateCardFromList - Use 'SelectSecondCorporateCardFromListParams' to pass parameters into this method.
        /// </summary>
        public void SelectSecondCorporateCardFromList()
        {
            #region Variable Declarations
            HtmlComboBox uICardProviderComboBox = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UICardProviderComboBox;
            #endregion

            // Select 'RBS Credit Card' in 'Card Provider' combo box
            uICardProviderComboBox.SelectedItem = this.SelectSecondCorporateCardFromListParams.UICardProviderComboBoxSelectedItem;
        }
        
        /// <summary>
        /// SelectActiveTickbox - Use 'SelectActiveTickboxParams' to pass parameters into this method.
        /// </summary>
        public void SelectActiveTickbox()
        {
            #region Variable Declarations
            HtmlCheckBox uIActiveCheckBox = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UIActiveCheckBox;
            #endregion

            // Select 'Active' check box
            uIActiveCheckBox.Checked = this.SelectActiveTickboxParams.UIActiveCheckBoxChecked;
        }
        
        /// <summary>
        /// UnselectActiveTickbox - Use 'UnselectActiveTickboxParams' to pass parameters into this method.
        /// </summary>
        public void UnselectActiveTickbox()
        {
            #region Variable Declarations
            HtmlCheckBox uIActiveCheckBox = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UIActiveCheckBox;
            #endregion

            // Clear 'Active' check box
            uIActiveCheckBox.Checked = this.UnselectActiveTickboxParams.UIActiveCheckBoxChecked;
        }
        
        /// <summary>
        /// PopulateCardNumber - Use 'PopulateCardNumberParams' to pass parameters into this method.
        /// </summary>
        public void PopulateCardNumber()
        {
            #region Variable Declarations
            HtmlEdit uICardNumberEdit = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UICardNumberEdit;
            #endregion

            // Type '12345' in 'Card Number' text box
            uICardNumberEdit.Text = this.PopulateCardNumberParams.UICardNumberEditText;
        }
        
        /// <summary>
        /// PressCorporateCardSaveButton
        /// </summary>
        public void PressCorporateCardSaveButton()
        {
            #region Variable Declarations
            HtmlImage uIOKImage = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UICtl00_contentmain_pnPane.UIOKImage;
            #endregion

            // Click 'OK' image
            Mouse.Click(uIOKImage, new Point(16, 14));
        }
        
        /// <summary>
        /// ValidateFirstCorporateCardExists - Use 'ValidateFirstCorporateCardExistsExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ValidateFirstCorporateCardExists()
        {
            #region Variable Declarations
            HtmlRow uITbl_gridCards_1994Row = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UITbl_gridCards_1994Row;
            #endregion

            // Verify that 'tbl_gridCards_1994' row's property 'InnerText' equals 'Credit CardBarclaycard12345'
            Assert.AreEqual(this.ValidateFirstCorporateCardExistsExpectedValues.UITbl_gridCards_1994RowInnerText, uITbl_gridCards_1994Row.InnerText);
        }
        
        /// <summary>
        /// ValidateFirstCorporateCardDoesNotExists - Use 'ValidateFirstCorporateCardDoesNotExistsExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ValidateFirstCorporateCardDoesNotExists()
        {
            #region Variable Declarations
            HtmlRow uITbl_gridCards_1994Row = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UITbl_gridCards_1994Row;
            #endregion

            // Verify that 'tbl_gridCards_1994' row's property 'InnerText' is not equal to 'Credit CardBarclaycard12345'
            Assert.AreNotEqual(this.ValidateFirstCorporateCardDoesNotExistsExpectedValues.UITbl_gridCards_1994RowInnerText, uITbl_gridCards_1994Row.InnerText);
        }
        
        /// <summary>
        /// PressCorporateCardEditIcon
        /// </summary>
        public void PressCorporateCardEditIcon()
        {
            #region Variable Declarations
            HtmlImage uIEditImage = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument2.UIEditgridCards_2070Cell.UIEditImage;
            #endregion

            // Click 'Edit' image
            Mouse.Click(uIEditImage, new Point(10, 8));
        }
        
        /// <summary>
        /// ValidateFirstCorporateCardIsEdited - Use 'ValidateFirstCorporateCardIsEditedExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ValidateFirstCorporateCardIsEdited()
        {
            #region Variable Declarations
            HtmlRow uITbl_gridCards_1994Row1 = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UITbl_gridCards_1994Row1;
            #endregion

            // Verify that 'tbl_gridCards_1994' row's property 'InnerText' equals 'Purchase CardPremier Inn xls98765'
            Assert.AreEqual(this.ValidateFirstCorporateCardIsEditedExpectedValues.UITbl_gridCards_1994Row1InnerText, uITbl_gridCards_1994Row1.InnerText);
        }
        
        /// <summary>
        /// PressCorporateCardDeleteIcon
        /// </summary>
        public void PressCorporateCardDeleteIcon()
        {
            #region Variable Declarations
            HtmlImage uIDeleteImage = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument1.UITbl_gridCards_2019Row.UIDeleteImage;
            WinButton uIOKButton = this.UIMessagefromwebpageWindow.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Delete' image
            Mouse.Click(uIDeleteImage, new Point(8, 8));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(58, 11));
        }
        
        /// <summary>
        /// PressEmployeeCancelButton
        /// </summary>
        public void PressEmployeeCancelButton()
        {
            #region Variable Declarations
            HtmlImage uICancelImage = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UICancelImage;
            #endregion

            // Click 'Cancel' image
            Mouse.Click(uICancelImage, new Point(31, 20));
        }
        
        /// <summary>
        /// ValidateDuplicateCardMessage - Use 'ValidateDuplicateCardMessageExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ValidateDuplicateCardMessage()
        {
            #region Variable Declarations
            HtmlDiv uICtl00_pnlMasterPopupPane = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UICtl00_pnlMasterPopupPane;
            #endregion

            // Verify that 'ctl00_pnlMasterPopup' pane's property 'DisplayText' equals 'Save Card Failed
            //
            //
            //The card number provided already exists on the system and cannot be duplicated'
            Assert.AreEqual(this.ValidateDuplicateCardMessageExpectedValues.UICtl00_pnlMasterPopupPaneDisplayText, uICtl00_pnlMasterPopupPane.DisplayText);

            // Verify that 'ctl00_pnlMasterPopup' pane's property 'Exists' equals 'True'
            Assert.AreEqual(this.ValidateDuplicateCardMessageExpectedValues.UICtl00_pnlMasterPopupPaneExists, uICtl00_pnlMasterPopupPane.Exists);
        }
        
        /// <summary>
        /// CancelFromDuplicateCardMessage
        /// </summary>
        public void CancelFromDuplicateCardMessage()
        {
            #region Variable Declarations
            HtmlImage uIOKImage = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UIOKImage;
            HtmlInputButton uICtl00contentmaincmdcButton = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UICtl00contentmaincmdcButton;
            #endregion

            // Click 'OK' image
            Mouse.Click(uIOKImage, new Point(25, 15));

            // Click 'ctl00$contentmain$cmdcorporatecardcancel' button
            Mouse.Click(uICtl00contentmaincmdcButton, new Point(22, 16));
        }
        
        /// <summary>
        /// PressSecondCorporateCardDeleteIcon
        /// </summary>
        public void PressSecondCorporateCardDeleteIcon()
        {
            #region Variable Declarations
            HtmlImage uIDeleteImage = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UITbl_gridCards_1998Row.UIDeleteImage;
            BrowserWindow uIEmployeeCodedUIAdminWindow = this.UIEmployeeCodedUIAdminWindow;
            #endregion

            // Click 'Delete' image
            Mouse.Click(uIDeleteImage, new Point(12, 9));

            // Click 'Ok' button in the browser dialog window
            uIEmployeeCodedUIAdminWindow.PerformDialogAction(BrowserDialogAction.Ok);
        }
        
        /// <summary>
        /// ValidateSecondCorporateCardExists - Use 'ValidateSecondCorporateCardExistsExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ValidateSecondCorporateCardExists()
        {
            #region Variable Declarations
            HtmlRow uITbl_gridCards_1999Row = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UITbl_gridCards_1999Row;
            #endregion

            // Verify that 'tbl_gridCards_1999' row's property 'InnerText' equals 'Credit CardRBS Credit Card2468'
            Assert.AreEqual(this.ValidateSecondCorporateCardExistsExpectedValues.UITbl_gridCards_1999RowInnerText, uITbl_gridCards_1999Row.InnerText);
        }
        
        /// <summary>
        /// ValidateSecondCorporateCardDoesNotExist - Use 'ValidateSecondCorporateCardDoesNotExistExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ValidateSecondCorporateCardDoesNotExist()
        {
            #region Variable Declarations
            HtmlRow uITbl_gridCards_1999Row = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UITbl_gridCards_1999Row;
            #endregion

            // Verify that 'tbl_gridCards_1999' row's property 'InnerText' is not equal to 'Credit CardRBS Credit Card2468'
            Assert.AreNotEqual(this.ValidateSecondCorporateCardDoesNotExistExpectedValues.UITbl_gridCards_1999RowInnerText, uITbl_gridCards_1999Row.InnerText);
        }
        
        /// <summary>
        /// ValidateTwoCorporateCardsExist - Use 'ValidateTwoCorporateCardsExistExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ValidateTwoCorporateCardsExist()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIEmployeeCodedUIAdminWindow.UIEmployeeCodedUIAdminDocument.UITbl_gridCardsTable1.UIItemCustom;
            #endregion

            // Verify that 'Unknown Name' custom control's property 'InnerText' equals 'Card Type Card ProviderCard NumberActive
            //Credit CardBarclaycard12345
            //Credit CardRBS Credit Card2468'
            Assert.AreEqual(this.ValidateTwoCorporateCardsExistExpectedValues.UIItemCustomInnerText, uIItemCustom.InnerText);
        }
        
        #region Properties
        public virtual SearchForEmployeeParams SearchForEmployeeParams
        {
            get
            {
                if ((this.mSearchForEmployeeParams == null))
                {
                    this.mSearchForEmployeeParams = new SearchForEmployeeParams();
                }
                return this.mSearchForEmployeeParams;
            }
        }
        
        public virtual ValidateNoCorporateCardsExistExpectedValues ValidateNoCorporateCardsExistExpectedValues
        {
            get
            {
                if ((this.mValidateNoCorporateCardsExistExpectedValues == null))
                {
                    this.mValidateNoCorporateCardsExistExpectedValues = new ValidateNoCorporateCardsExistExpectedValues();
                }
                return this.mValidateNoCorporateCardsExistExpectedValues;
            }
        }
        
        public virtual SelectFirstCorporateCardFromListParams SelectFirstCorporateCardFromListParams
        {
            get
            {
                if ((this.mSelectFirstCorporateCardFromListParams == null))
                {
                    this.mSelectFirstCorporateCardFromListParams = new SelectFirstCorporateCardFromListParams();
                }
                return this.mSelectFirstCorporateCardFromListParams;
            }
        }
        
        public virtual SelectSecondCorporateCardFromListParams SelectSecondCorporateCardFromListParams
        {
            get
            {
                if ((this.mSelectSecondCorporateCardFromListParams == null))
                {
                    this.mSelectSecondCorporateCardFromListParams = new SelectSecondCorporateCardFromListParams();
                }
                return this.mSelectSecondCorporateCardFromListParams;
            }
        }
        
        public virtual SelectActiveTickboxParams SelectActiveTickboxParams
        {
            get
            {
                if ((this.mSelectActiveTickboxParams == null))
                {
                    this.mSelectActiveTickboxParams = new SelectActiveTickboxParams();
                }
                return this.mSelectActiveTickboxParams;
            }
        }
        
        public virtual UnselectActiveTickboxParams UnselectActiveTickboxParams
        {
            get
            {
                if ((this.mUnselectActiveTickboxParams == null))
                {
                    this.mUnselectActiveTickboxParams = new UnselectActiveTickboxParams();
                }
                return this.mUnselectActiveTickboxParams;
            }
        }
        
        public virtual PopulateCardNumberParams PopulateCardNumberParams
        {
            get
            {
                if ((this.mPopulateCardNumberParams == null))
                {
                    this.mPopulateCardNumberParams = new PopulateCardNumberParams();
                }
                return this.mPopulateCardNumberParams;
            }
        }
        
        public virtual ValidateFirstCorporateCardExistsExpectedValues ValidateFirstCorporateCardExistsExpectedValues
        {
            get
            {
                if ((this.mValidateFirstCorporateCardExistsExpectedValues == null))
                {
                    this.mValidateFirstCorporateCardExistsExpectedValues = new ValidateFirstCorporateCardExistsExpectedValues();
                }
                return this.mValidateFirstCorporateCardExistsExpectedValues;
            }
        }
        
        public virtual ValidateFirstCorporateCardDoesNotExistsExpectedValues ValidateFirstCorporateCardDoesNotExistsExpectedValues
        {
            get
            {
                if ((this.mValidateFirstCorporateCardDoesNotExistsExpectedValues == null))
                {
                    this.mValidateFirstCorporateCardDoesNotExistsExpectedValues = new ValidateFirstCorporateCardDoesNotExistsExpectedValues();
                }
                return this.mValidateFirstCorporateCardDoesNotExistsExpectedValues;
            }
        }
        
        public virtual ValidateFirstCorporateCardIsEditedExpectedValues ValidateFirstCorporateCardIsEditedExpectedValues
        {
            get
            {
                if ((this.mValidateFirstCorporateCardIsEditedExpectedValues == null))
                {
                    this.mValidateFirstCorporateCardIsEditedExpectedValues = new ValidateFirstCorporateCardIsEditedExpectedValues();
                }
                return this.mValidateFirstCorporateCardIsEditedExpectedValues;
            }
        }
        
        public virtual ValidateDuplicateCardMessageExpectedValues ValidateDuplicateCardMessageExpectedValues
        {
            get
            {
                if ((this.mValidateDuplicateCardMessageExpectedValues == null))
                {
                    this.mValidateDuplicateCardMessageExpectedValues = new ValidateDuplicateCardMessageExpectedValues();
                }
                return this.mValidateDuplicateCardMessageExpectedValues;
            }
        }
        
        public virtual ValidateSecondCorporateCardExistsExpectedValues ValidateSecondCorporateCardExistsExpectedValues
        {
            get
            {
                if ((this.mValidateSecondCorporateCardExistsExpectedValues == null))
                {
                    this.mValidateSecondCorporateCardExistsExpectedValues = new ValidateSecondCorporateCardExistsExpectedValues();
                }
                return this.mValidateSecondCorporateCardExistsExpectedValues;
            }
        }
        
        public virtual ValidateSecondCorporateCardDoesNotExistExpectedValues ValidateSecondCorporateCardDoesNotExistExpectedValues
        {
            get
            {
                if ((this.mValidateSecondCorporateCardDoesNotExistExpectedValues == null))
                {
                    this.mValidateSecondCorporateCardDoesNotExistExpectedValues = new ValidateSecondCorporateCardDoesNotExistExpectedValues();
                }
                return this.mValidateSecondCorporateCardDoesNotExistExpectedValues;
            }
        }
        
        public virtual ValidateTwoCorporateCardsExistExpectedValues ValidateTwoCorporateCardsExistExpectedValues
        {
            get
            {
                if ((this.mValidateTwoCorporateCardsExistExpectedValues == null))
                {
                    this.mValidateTwoCorporateCardsExistExpectedValues = new ValidateTwoCorporateCardsExistExpectedValues();
                }
                return this.mValidateTwoCorporateCardsExistExpectedValues;
            }
        }
        
        public UIHttpstestingselexpenWindow UIHttpstestingselexpenWindow
        {
            get
            {
                if ((this.mUIHttpstestingselexpenWindow == null))
                {
                    this.mUIHttpstestingselexpenWindow = new UIHttpstestingselexpenWindow();
                }
                return this.mUIHttpstestingselexpenWindow;
            }
        }
        
        public UIEmployeesWindowsInteWindow UIEmployeesWindowsInteWindow
        {
            get
            {
                if ((this.mUIEmployeesWindowsInteWindow == null))
                {
                    this.mUIEmployeesWindowsInteWindow = new UIEmployeesWindowsInteWindow();
                }
                return this.mUIEmployeesWindowsInteWindow;
            }
        }
        
        public UIEmployeeCodedUIAdminWindow UIEmployeeCodedUIAdminWindow
        {
            get
            {
                if ((this.mUIEmployeeCodedUIAdminWindow == null))
                {
                    this.mUIEmployeeCodedUIAdminWindow = new UIEmployeeCodedUIAdminWindow();
                }
                return this.mUIEmployeeCodedUIAdminWindow;
            }
        }
        
        public UIMessagefromwebpageWindow UIMessagefromwebpageWindow
        {
            get
            {
                if ((this.mUIMessagefromwebpageWindow == null))
                {
                    this.mUIMessagefromwebpageWindow = new UIMessagefromwebpageWindow();
                }
                return this.mUIMessagefromwebpageWindow;
            }
        }
        #endregion
        
        #region Fields
        private SearchForEmployeeParams mSearchForEmployeeParams;
        
        private ValidateNoCorporateCardsExistExpectedValues mValidateNoCorporateCardsExistExpectedValues;
        
        private SelectFirstCorporateCardFromListParams mSelectFirstCorporateCardFromListParams;
        
        private SelectSecondCorporateCardFromListParams mSelectSecondCorporateCardFromListParams;
        
        private SelectActiveTickboxParams mSelectActiveTickboxParams;
        
        private UnselectActiveTickboxParams mUnselectActiveTickboxParams;
        
        private PopulateCardNumberParams mPopulateCardNumberParams;
        
        private ValidateFirstCorporateCardExistsExpectedValues mValidateFirstCorporateCardExistsExpectedValues;
        
        private ValidateFirstCorporateCardDoesNotExistsExpectedValues mValidateFirstCorporateCardDoesNotExistsExpectedValues;
        
        private ValidateFirstCorporateCardIsEditedExpectedValues mValidateFirstCorporateCardIsEditedExpectedValues;
        
        private ValidateDuplicateCardMessageExpectedValues mValidateDuplicateCardMessageExpectedValues;
        
        private ValidateSecondCorporateCardExistsExpectedValues mValidateSecondCorporateCardExistsExpectedValues;
        
        private ValidateSecondCorporateCardDoesNotExistExpectedValues mValidateSecondCorporateCardDoesNotExistExpectedValues;
        
        private ValidateTwoCorporateCardsExistExpectedValues mValidateTwoCorporateCardsExistExpectedValues;
        
        private UIHttpstestingselexpenWindow mUIHttpstestingselexpenWindow;
        
        private UIEmployeesWindowsInteWindow mUIEmployeesWindowsInteWindow;
        
        private UIEmployeeCodedUIAdminWindow mUIEmployeeCodedUIAdminWindow;
        
        private UIMessagefromwebpageWindow mUIMessagefromwebpageWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SearchForEmployee'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class SearchForEmployeeParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'CodedUIAdmin' in 'Username' text box
        /// </summary>
        public string UIUsernameEditText = "CodedUIAdmin";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateNoCorporateCardsExist'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class ValidateNoCorporateCardsExistExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'There are no corporate cards defined for' cell's property 'InnerText' equals 'There are no corporate cards defined for this employee'
        /// </summary>
        public string UITherearenocorporatecCellInnerText = "There are no corporate cards defined for this employee";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SelectFirstCorporateCardFromList'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class SelectFirstCorporateCardFromListParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Barclaycard' in 'Card Provider' combo box
        /// </summary>
        public string UICardProviderComboBoxSelectedItem = "Barclaycard";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SelectSecondCorporateCardFromList'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class SelectSecondCorporateCardFromListParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'RBS Credit Card' in 'Card Provider' combo box
        /// </summary>
        public string UICardProviderComboBoxSelectedItem = "RBS Credit Card";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SelectActiveTickbox'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class SelectActiveTickboxParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Active' check box
        /// </summary>
        public bool UIActiveCheckBoxChecked = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'UnselectActiveTickbox'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UnselectActiveTickboxParams
    {
        
        #region Fields
        /// <summary>
        /// Clear 'Active' check box
        /// </summary>
        public bool UIActiveCheckBoxChecked = false;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PopulateCardNumber'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class PopulateCardNumberParams
    {
        
        #region Fields
        /// <summary>
        /// Type '12345' in 'Card Number' text box
        /// </summary>
        public string UICardNumberEditText = "12345";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateFirstCorporateCardExists'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class ValidateFirstCorporateCardExistsExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'tbl_gridCards_1994' row's property 'InnerText' equals 'Credit CardBarclaycard12345'
        /// </summary>
        public string UITbl_gridCards_1994RowInnerText = "Credit CardBarclaycard12345";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateFirstCorporateCardDoesNotExists'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class ValidateFirstCorporateCardDoesNotExistsExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'tbl_gridCards_1994' row's property 'InnerText' is not equal to 'Credit CardBarclaycard12345'
        /// </summary>
        public string UITbl_gridCards_1994RowInnerText = "Credit CardBarclaycard12345";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateFirstCorporateCardIsEdited'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class ValidateFirstCorporateCardIsEditedExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'tbl_gridCards_1994' row's property 'InnerText' equals 'Purchase CardPremier Inn xls98765'
        /// </summary>
        public string UITbl_gridCards_1994Row1InnerText = "Purchase CardPremier Inn xls98765";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateDuplicateCardMessage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class ValidateDuplicateCardMessageExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'ctl00_pnlMasterPopup' pane's property 'DisplayText' equals 'Save Card Failed
        ///
        ///
        ///The card number provided already exists on the system and cannot be duplicated'
        /// </summary>
        public string UICtl00_pnlMasterPopupPaneDisplayText = "Save Card Failed\r\n\r\n\r\nThe card number provided already exists on the system and c" +
            "annot be duplicated";
        
        /// <summary>
        /// Verify that 'ctl00_pnlMasterPopup' pane's property 'Exists' equals 'True'
        /// </summary>
        public bool UICtl00_pnlMasterPopupPaneExists = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateSecondCorporateCardExists'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class ValidateSecondCorporateCardExistsExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'tbl_gridCards_1999' row's property 'InnerText' equals 'Credit CardRBS Credit Card2468'
        /// </summary>
        public string UITbl_gridCards_1999RowInnerText = "Credit CardRBS Credit Card2468";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateSecondCorporateCardDoesNotExist'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class ValidateSecondCorporateCardDoesNotExistExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'tbl_gridCards_1999' row's property 'InnerText' is not equal to 'Credit CardRBS Credit Card2468'
        /// </summary>
        public string UITbl_gridCards_1999RowInnerText = "Credit CardRBS Credit Card2468";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateTwoCorporateCardsExist'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class ValidateTwoCorporateCardsExistExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'Unknown Name' custom control's property 'InnerText' equals 'Card Type Card ProviderCard NumberActive
        ///Credit CardBarclaycard12345
        ///Credit CardRBS Credit Card2468'
        /// </summary>
        public string UIItemCustomInnerText = "Card Type Card ProviderCard NumberActive\r\nCredit CardBarclaycard12345\r\nCredit Car" +
            "dRBS Credit Card2468";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIHttpstestingselexpenWindow : BrowserWindow
    {
        
        public UIHttpstestingselexpenWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "https://testing.sel-expenses.com/shared/admin/selectemployee.aspx";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("https://testing.sel-expenses.com/shared/admin/selectemployee.aspx");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHttpstestingselexpenDocument UIHttpstestingselexpenDocument
        {
            get
            {
                if ((this.mUIHttpstestingselexpenDocument == null))
                {
                    this.mUIHttpstestingselexpenDocument = new UIHttpstestingselexpenDocument(this);
                }
                return this.mUIHttpstestingselexpenDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpstestingselexpenDocument mUIHttpstestingselexpenDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIHttpstestingselexpenDocument : HtmlDocument
    {
        
        public UIHttpstestingselexpenDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "ctl00_body";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/shared/admin/selectemployee.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://testing.sel-expenses.com/shared/admin/selectemployee.aspx";
            this.WindowTitles.Add("https://testing.sel-expenses.com/shared/admin/selectemployee.aspx");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_contentmain_txtusername";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$contentmain$txtusername";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Username";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "fillspan";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=ctl00_contentmain_txtusername class=f";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUIUsernameEdit.WindowTitles.Add("https://testing.sel-expenses.com/shared/admin/selectemployee.aspx");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlInputButton UICtl00contentmaincmdoButton
        {
            get
            {
                if ((this.mUICtl00contentmaincmdoButton == null))
                {
                    this.mUICtl00contentmaincmdoButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUICtl00contentmaincmdoButton.SearchProperties[HtmlButton.PropertyNames.Id] = "ctl00_contentmain_cmdok";
                    this.mUICtl00contentmaincmdoButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$contentmain$cmdok";
                    this.mUICtl00contentmaincmdoButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = null;
                    this.mUICtl00contentmaincmdoButton.FilterProperties[HtmlButton.PropertyNames.Type] = "image";
                    this.mUICtl00contentmaincmdoButton.FilterProperties["Src"] = "https://testing.sel-expenses.com/shared/images/buttons/pagebutton_search.gif";
                    this.mUICtl00contentmaincmdoButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICtl00contentmaincmdoButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUICtl00contentmaincmdoButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "style=\"BORDER-RIGHT-WIDTH: 0px; BORDER-T";
                    this.mUICtl00contentmaincmdoButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "7";
                    this.mUICtl00contentmaincmdoButton.WindowTitles.Add("https://testing.sel-expenses.com/shared/admin/selectemployee.aspx");
                    #endregion
                }
                return this.mUICtl00contentmaincmdoButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlInputButton mUICtl00contentmaincmdoButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIEmployeesWindowsInteWindow : BrowserWindow
    {
        
        public UIEmployeesWindowsInteWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Employees";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Employees");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIEmployeesDocument UIEmployeesDocument
        {
            get
            {
                if ((this.mUIEmployeesDocument == null))
                {
                    this.mUIEmployeesDocument = new UIEmployeesDocument(this);
                }
                return this.mUIEmployeesDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIEmployeesDocument mUIEmployeesDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIEmployeesDocument : HtmlDocument
    {
        
        public UIEmployeesDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "ctl00_body";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Employees";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/shared/admin/adminemployees.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://testing.sel-expenses.com/shared/admin/adminemployees.aspx?surname=&roleid" +
                "=0&groupid=&costcodeid=0&departmentid=0&username=CodedUIAdmin";
            this.WindowTitles.Add("Employees");
            #endregion
        }
        
        #region Properties
        public UITbl_gridEmployees_32Row UITbl_gridEmployees_32Row
        {
            get
            {
                if ((this.mUITbl_gridEmployees_32Row == null))
                {
                    this.mUITbl_gridEmployees_32Row = new UITbl_gridEmployees_32Row(this);
                }
                return this.mUITbl_gridEmployees_32Row;
            }
        }
        #endregion
        
        #region Fields
        private UITbl_gridEmployees_32Row mUITbl_gridEmployees_32Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITbl_gridEmployees_32Row : HtmlRow
    {
        
        public UITbl_gridEmployees_32Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlRow.PropertyNames.Id] = "tbl_gridEmployees_32054";
            this.SearchProperties[HtmlRow.PropertyNames.Name] = null;
            this.FilterProperties[HtmlRow.PropertyNames.InnerText] = "CodedUIAdminMrCodedUIAdmin ";
            this.FilterProperties[HtmlRow.PropertyNames.ControlDefinition] = "id=tbl_gridEmployees_32054";
            this.FilterProperties[HtmlRow.PropertyNames.RowIndex] = "1";
            this.FilterProperties[HtmlRow.PropertyNames.Class] = null;
            this.FilterProperties[HtmlRow.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Employees");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIEditImage
        {
            get
            {
                if ((this.mUIEditImage == null))
                {
                    this.mUIEditImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIEditImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIEditImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIEditImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Edit";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/shared/images/icons/edit.png";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://testing.sel-expenses.com/shared/images/icons/edit.png";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=Edit src=\"/shared/images/icons/edit.";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIEditImage.WindowTitles.Add("Employees");
                    #endregion
                }
                return this.mUIEditImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIEditImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIEmployeeCodedUIAdminWindow : BrowserWindow
    {
        
        public UIEmployeeCodedUIAdminWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Employee: CodedUIAdmin";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIEmployeeCodedUIAdminDocument UIEmployeeCodedUIAdminDocument
        {
            get
            {
                if ((this.mUIEmployeeCodedUIAdminDocument == null))
                {
                    this.mUIEmployeeCodedUIAdminDocument = new UIEmployeeCodedUIAdminDocument(this);
                }
                return this.mUIEmployeeCodedUIAdminDocument;
            }
        }
        
        public UIEmployeeCodedUIAdminDocument1 UIEmployeeCodedUIAdminDocument1
        {
            get
            {
                if ((this.mUIEmployeeCodedUIAdminDocument1 == null))
                {
                    this.mUIEmployeeCodedUIAdminDocument1 = new UIEmployeeCodedUIAdminDocument1(this);
                }
                return this.mUIEmployeeCodedUIAdminDocument1;
            }
        }
        
        public UIEmployeeCodedUIAdminDocument2 UIEmployeeCodedUIAdminDocument2
        {
            get
            {
                if ((this.mUIEmployeeCodedUIAdminDocument2 == null))
                {
                    this.mUIEmployeeCodedUIAdminDocument2 = new UIEmployeeCodedUIAdminDocument2(this);
                }
                return this.mUIEmployeeCodedUIAdminDocument2;
            }
        }
        #endregion
        
        #region Fields
        private UIEmployeeCodedUIAdminDocument mUIEmployeeCodedUIAdminDocument;
        
        private UIEmployeeCodedUIAdminDocument1 mUIEmployeeCodedUIAdminDocument1;
        
        private UIEmployeeCodedUIAdminDocument2 mUIEmployeeCodedUIAdminDocument2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIEmployeeCodedUIAdminDocument : HtmlDocument
    {
        
        public UIEmployeeCodedUIAdminDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "ctl00_body";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Employee: CodedUIAdmin";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/shared/admin/aeemployee.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://testing.sel-expenses.com/shared/admin/aeemployee.aspx?employeeid=32054";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UICorporateCardsHyperlink
        {
            get
            {
                if ((this.mUICorporateCardsHyperlink == null))
                {
                    this.mUICorporateCardsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICorporateCardsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "lnkCorporateCards";
                    this.mUICorporateCardsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICorporateCardsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICorporateCardsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Corporate Cards";
                    this.mUICorporateCardsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "changePage(\'CorporateCards\');";
                    this.mUICorporateCardsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICorporateCardsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:changePage(\'CorporateCards\');";
                    this.mUICorporateCardsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUICorporateCardsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=lnkCorporateCards href=\"javascript:ch";
                    this.mUICorporateCardsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUICorporateCardsHyperlink.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUICorporateCardsHyperlink;
            }
        }
        
        public UITbl_gridCardsTable UITbl_gridCardsTable
        {
            get
            {
                if ((this.mUITbl_gridCardsTable == null))
                {
                    this.mUITbl_gridCardsTable = new UITbl_gridCardsTable(this);
                }
                return this.mUITbl_gridCardsTable;
            }
        }
        
        public UIAddCorporateCardPane UIAddCorporateCardPane
        {
            get
            {
                if ((this.mUIAddCorporateCardPane == null))
                {
                    this.mUIAddCorporateCardPane = new UIAddCorporateCardPane(this);
                }
                return this.mUIAddCorporateCardPane;
            }
        }
        
        public HtmlComboBox UICardProviderComboBox
        {
            get
            {
                if ((this.mUICardProviderComboBox == null))
                {
                    this.mUICardProviderComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUICardProviderComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ctl00_contentmain_cmbcardprovider";
                    this.mUICardProviderComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ctl00$contentmain$cmbcardprovider";
                    this.mUICardProviderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUICardProviderComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "Card Provider";
                    this.mUICardProviderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUICardProviderComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "13";
                    this.mUICardProviderComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "fillspan";
                    this.mUICardProviderComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "id=ctl00_contentmain_cmbcardprovider cla";
                    this.mUICardProviderComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "18";
                    this.mUICardProviderComboBox.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUICardProviderComboBox;
            }
        }
        
        public HtmlCheckBox UIActiveCheckBox
        {
            get
            {
                if ((this.mUIActiveCheckBox == null))
                {
                    this.mUIActiveCheckBox = new HtmlCheckBox(this);
                    #region Search Criteria
                    this.mUIActiveCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Id] = "ctl00_contentmain_chkCardActive";
                    this.mUIActiveCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Name] = "ctl00$contentmain$chkCardActive";
                    this.mUIActiveCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Value] = "on";
                    this.mUIActiveCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.LabeledBy] = "Active";
                    this.mUIActiveCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Title] = null;
                    this.mUIActiveCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Class] = null;
                    this.mUIActiveCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.ControlDefinition] = "id=ctl00_contentmain_chkCardActive type=";
                    this.mUIActiveCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.TagInstance] = "58";
                    this.mUIActiveCheckBox.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUIActiveCheckBox;
            }
        }
        
        public HtmlEdit UICardNumberEdit
        {
            get
            {
                if ((this.mUICardNumberEdit == null))
                {
                    this.mUICardNumberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICardNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_contentmain_txtcardnumber";
                    this.mUICardNumberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$contentmain$txtcardnumber";
                    this.mUICardNumberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Card Number";
                    this.mUICardNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICardNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICardNumberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "fillspan";
                    this.mUICardNumberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=ctl00_contentmain_txtcardnumber class";
                    this.mUICardNumberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "57";
                    this.mUICardNumberEdit.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUICardNumberEdit;
            }
        }
        
        public UICtl00_contentmain_pnPane UICtl00_contentmain_pnPane
        {
            get
            {
                if ((this.mUICtl00_contentmain_pnPane == null))
                {
                    this.mUICtl00_contentmain_pnPane = new UICtl00_contentmain_pnPane(this);
                }
                return this.mUICtl00_contentmain_pnPane;
            }
        }
        
        public UITbl_gridCards_1994Row UITbl_gridCards_1994Row
        {
            get
            {
                if ((this.mUITbl_gridCards_1994Row == null))
                {
                    this.mUITbl_gridCards_1994Row = new UITbl_gridCards_1994Row(this);
                }
                return this.mUITbl_gridCards_1994Row;
            }
        }
        
        public HtmlRow UITbl_gridCards_1994Row1
        {
            get
            {
                if ((this.mUITbl_gridCards_1994Row1 == null))
                {
                    this.mUITbl_gridCards_1994Row1 = new HtmlRow(this);
                    #region Search Criteria
                    this.mUITbl_gridCards_1994Row1.SearchProperties[HtmlRow.PropertyNames.Id] = "tbl_gridCards_1994";
                    this.mUITbl_gridCards_1994Row1.SearchProperties[HtmlRow.PropertyNames.Name] = null;
                    this.mUITbl_gridCards_1994Row1.FilterProperties[HtmlRow.PropertyNames.InnerText] = "Purchase CardPremier Inn xls98765";
                    this.mUITbl_gridCards_1994Row1.FilterProperties[HtmlRow.PropertyNames.ControlDefinition] = "id=tbl_gridCards_1994";
                    this.mUITbl_gridCards_1994Row1.FilterProperties[HtmlRow.PropertyNames.RowIndex] = "1";
                    this.mUITbl_gridCards_1994Row1.FilterProperties[HtmlRow.PropertyNames.Class] = null;
                    this.mUITbl_gridCards_1994Row1.FilterProperties[HtmlRow.PropertyNames.TagInstance] = "14";
                    this.mUITbl_gridCards_1994Row1.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUITbl_gridCards_1994Row1;
            }
        }
        
        public HtmlImage UICancelImage
        {
            get
            {
                if ((this.mUICancelImage == null))
                {
                    this.mUICancelImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUICancelImage.SearchProperties[HtmlImage.PropertyNames.Id] = "ctl00_contentmain_imgCancelEmployee";
                    this.mUICancelImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUICancelImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Cancel";
                    this.mUICancelImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/shared/images/buttons/cancel_up.gif";
                    this.mUICancelImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://testing.sel-expenses.com/shared/images/buttons/cancel_up.gif";
                    this.mUICancelImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUICancelImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "style=\"BORDER-RIGHT-WIDTH: 0px; BORDER-T";
                    this.mUICancelImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "42";
                    this.mUICancelImage.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUICancelImage;
            }
        }
        
        public HtmlDiv UICtl00_pnlMasterPopupPane
        {
            get
            {
                if ((this.mUICtl00_pnlMasterPopupPane == null))
                {
                    this.mUICtl00_pnlMasterPopupPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUICtl00_pnlMasterPopupPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "ctl00_pnlMasterPopup";
                    this.mUICtl00_pnlMasterPopupPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUICtl00_pnlMasterPopupPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Save Card Failed\r\n\r\n\r\nThe card number pr";
                    this.mUICtl00_pnlMasterPopupPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUICtl00_pnlMasterPopupPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "errorModal";
                    this.mUICtl00_pnlMasterPopupPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"Z-INDEX: 11001; POSITION: fixed; ";
                    this.mUICtl00_pnlMasterPopupPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "313";
                    this.mUICtl00_pnlMasterPopupPane.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUICtl00_pnlMasterPopupPane;
            }
        }
        
        public HtmlImage UIOKImage
        {
            get
            {
                if ((this.mUIOKImage == null))
                {
                    this.mUIOKImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIOKImage.SearchProperties[HtmlImage.PropertyNames.Id] = "btnMasterPopup";
                    this.mUIOKImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIOKImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "OK";
                    this.mUIOKImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/shared/images/buttons/btn_close.png";
                    this.mUIOKImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://testing.sel-expenses.com/shared/images/buttons/btn_close.png";
                    this.mUIOKImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIOKImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "style=\"CURSOR: pointer\" id=btnMasterPopu";
                    this.mUIOKImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "123";
                    this.mUIOKImage.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUIOKImage;
            }
        }
        
        public HtmlInputButton UICtl00contentmaincmdcButton
        {
            get
            {
                if ((this.mUICtl00contentmaincmdcButton == null))
                {
                    this.mUICtl00contentmaincmdcButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUICtl00contentmaincmdcButton.SearchProperties[HtmlButton.PropertyNames.Id] = "ctl00_contentmain_cmdcorporatecardcancel";
                    this.mUICtl00contentmaincmdcButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$contentmain$cmdcorporatecardcancel";
                    this.mUICtl00contentmaincmdcButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = null;
                    this.mUICtl00contentmaincmdcButton.FilterProperties[HtmlButton.PropertyNames.Type] = "image";
                    this.mUICtl00contentmaincmdcButton.FilterProperties["Src"] = "https://testing.sel-expenses.com/shared/images/buttons/cancel_up.gif";
                    this.mUICtl00contentmaincmdcButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICtl00contentmaincmdcButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUICtl00contentmaincmdcButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "style=\"BORDER-RIGHT-WIDTH: 0px; BORDER-T";
                    this.mUICtl00contentmaincmdcButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "60";
                    this.mUICtl00contentmaincmdcButton.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUICtl00contentmaincmdcButton;
            }
        }
        
        public UITbl_gridCards_1998Row UITbl_gridCards_1998Row
        {
            get
            {
                if ((this.mUITbl_gridCards_1998Row == null))
                {
                    this.mUITbl_gridCards_1998Row = new UITbl_gridCards_1998Row(this);
                }
                return this.mUITbl_gridCards_1998Row;
            }
        }
        
        public HtmlRow UITbl_gridCards_1999Row
        {
            get
            {
                if ((this.mUITbl_gridCards_1999Row == null))
                {
                    this.mUITbl_gridCards_1999Row = new HtmlRow(this);
                    #region Search Criteria
                    this.mUITbl_gridCards_1999Row.SearchProperties[HtmlRow.PropertyNames.Id] = "tbl_gridCards_1999";
                    this.mUITbl_gridCards_1999Row.SearchProperties[HtmlRow.PropertyNames.Name] = null;
                    this.mUITbl_gridCards_1999Row.FilterProperties[HtmlRow.PropertyNames.InnerText] = "Credit CardRBS Credit Card2468";
                    this.mUITbl_gridCards_1999Row.FilterProperties[HtmlRow.PropertyNames.ControlDefinition] = "id=tbl_gridCards_1999";
                    this.mUITbl_gridCards_1999Row.FilterProperties[HtmlRow.PropertyNames.RowIndex] = "2";
                    this.mUITbl_gridCards_1999Row.FilterProperties[HtmlRow.PropertyNames.Class] = null;
                    this.mUITbl_gridCards_1999Row.FilterProperties[HtmlRow.PropertyNames.TagInstance] = "15";
                    this.mUITbl_gridCards_1999Row.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUITbl_gridCards_1999Row;
            }
        }
        
        public UITbl_gridCardsTable1 UITbl_gridCardsTable1
        {
            get
            {
                if ((this.mUITbl_gridCardsTable1 == null))
                {
                    this.mUITbl_gridCardsTable1 = new UITbl_gridCardsTable1(this);
                }
                return this.mUITbl_gridCardsTable1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUICorporateCardsHyperlink;
        
        private UITbl_gridCardsTable mUITbl_gridCardsTable;
        
        private UIAddCorporateCardPane mUIAddCorporateCardPane;
        
        private HtmlComboBox mUICardProviderComboBox;
        
        private HtmlCheckBox mUIActiveCheckBox;
        
        private HtmlEdit mUICardNumberEdit;
        
        private UICtl00_contentmain_pnPane mUICtl00_contentmain_pnPane;
        
        private UITbl_gridCards_1994Row mUITbl_gridCards_1994Row;
        
        private HtmlRow mUITbl_gridCards_1994Row1;
        
        private HtmlImage mUICancelImage;
        
        private HtmlDiv mUICtl00_pnlMasterPopupPane;
        
        private HtmlImage mUIOKImage;
        
        private HtmlInputButton mUICtl00contentmaincmdcButton;
        
        private UITbl_gridCards_1998Row mUITbl_gridCards_1998Row;
        
        private HtmlRow mUITbl_gridCards_1999Row;
        
        private UITbl_gridCardsTable1 mUITbl_gridCardsTable1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITbl_gridCardsTable : HtmlTable
    {
        
        public UITbl_gridCardsTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "tbl_gridCards";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Card Type Card ProviderCard NumberActive";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=tbl_gridCards class=cGrid";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "6";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "cGrid";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "7";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        #region Properties
        public HtmlCell UITherearenocorporatecCell
        {
            get
            {
                if ((this.mUITherearenocorporatecCell == null))
                {
                    this.mUITherearenocorporatecCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUITherearenocorporatecCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUITherearenocorporatecCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUITherearenocorporatecCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUITherearenocorporatecCell.FilterProperties[HtmlCell.PropertyNames.InnerText] = "There are no corporate cards defined for";
                    this.mUITherearenocorporatecCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=row1 colSpan=6 align=middle";
                    this.mUITherearenocorporatecCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUITherearenocorporatecCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUITherearenocorporatecCell.FilterProperties[HtmlCell.PropertyNames.Class] = "row1";
                    this.mUITherearenocorporatecCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1";
                    this.mUITherearenocorporatecCell.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUITherearenocorporatecCell;
            }
        }
        
        public HtmlCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.InnerText] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=row1";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "1";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.Class] = "row1";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "2";
                    this.mUIItemCell.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUITherearenocorporatecCell;
        
        private HtmlCell mUIItemCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIAddCorporateCardPane : HtmlDiv
    {
        
        public UIAddCorporateCardPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "pgOptCorporateCards";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Add Corporate Card ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=pgOptCorporateCards  className";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "13";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIAddCorporateCardHyperlink
        {
            get
            {
                if ((this.mUIAddCorporateCardHyperlink == null))
                {
                    this.mUIAddCorporateCardHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAddCorporateCardHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAddCorporateCardHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAddCorporateCardHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAddCorporateCardHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Add Corporate Card";
                    this.mUIAddCorporateCardHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "corporatecardid%20=%200;showCorporateCardModal();";
                    this.mUIAddCorporateCardHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAddCorporateCardHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:corporatecardid = 0;showCorporateCardModal();";
                    this.mUIAddCorporateCardHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "submenuitem";
                    this.mUIAddCorporateCardHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=submenuitem href=\"javascript:corpo";
                    this.mUIAddCorporateCardHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIAddCorporateCardHyperlink.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUIAddCorporateCardHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIAddCorporateCardHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UICtl00_contentmain_pnPane : HtmlDiv
    {
        
        public UICtl00_contentmain_pnPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "ctl00_contentmain_pnlCorporateCard";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "General Details\r\nCard Provider Allstar F";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "modalpanel";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"Z-INDEX: 10001; POSITION: fixed; ";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "153";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIOKImage
        {
            get
            {
                if ((this.mUIOKImage == null))
                {
                    this.mUIOKImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIOKImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIOKImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIOKImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "OK";
                    this.mUIOKImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/shared/images/buttons/btn_save.png";
                    this.mUIOKImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://testing.sel-expenses.com/shared/images/buttons/btn_save.png";
                    this.mUIOKImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIOKImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=OK src=\"/shared/images/buttons/btn_s";
                    this.mUIOKImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIOKImage.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUIOKImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIOKImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITbl_gridCards_1994Row : HtmlRow
    {
        
        public UITbl_gridCards_1994Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlRow.PropertyNames.Id] = "tbl_gridCards_1994";
            this.SearchProperties[HtmlRow.PropertyNames.Name] = null;
            this.FilterProperties[HtmlRow.PropertyNames.InnerText] = "Credit CardBarclaycard12345";
            this.FilterProperties[HtmlRow.PropertyNames.ControlDefinition] = "id=tbl_gridCards_1994";
            this.FilterProperties[HtmlRow.PropertyNames.RowIndex] = "1";
            this.FilterProperties[HtmlRow.PropertyNames.Class] = null;
            this.FilterProperties[HtmlRow.PropertyNames.TagInstance] = "14";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIEditImage
        {
            get
            {
                if ((this.mUIEditImage == null))
                {
                    this.mUIEditImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIEditImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIEditImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIEditImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Edit";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/shared/images/icons/edit.png";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://testing.sel-expenses.com/shared/images/icons/edit.png";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=Edit src=\"/shared/images/icons/edit.";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIEditImage.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUIEditImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIEditImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITbl_gridCards_1998Row : HtmlRow
    {
        
        public UITbl_gridCards_1998Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlRow.PropertyNames.Id] = "tbl_gridCards_1998";
            this.SearchProperties[HtmlRow.PropertyNames.Name] = null;
            this.FilterProperties[HtmlRow.PropertyNames.InnerText] = "Credit CardRBS Credit Card2468";
            this.FilterProperties[HtmlRow.PropertyNames.ControlDefinition] = "id=tbl_gridCards_1998";
            this.FilterProperties[HtmlRow.PropertyNames.RowIndex] = "2";
            this.FilterProperties[HtmlRow.PropertyNames.Class] = null;
            this.FilterProperties[HtmlRow.PropertyNames.TagInstance] = "15";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIDeleteImage
        {
            get
            {
                if ((this.mUIDeleteImage == null))
                {
                    this.mUIDeleteImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIDeleteImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIDeleteImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIDeleteImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Delete";
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/shared/images/icons/delete2.png";
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://testing.sel-expenses.com/shared/images/icons/delete2.png";
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=Delete src=\"/shared/images/icons/del";
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "2";
                    this.mUIDeleteImage.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUIDeleteImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIDeleteImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITbl_gridCardsTable1 : HtmlTable
    {
        
        public UITbl_gridCardsTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "tbl_gridCards";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Card Type Card ProviderCard NumberActive";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=tbl_gridCards class=cGrid";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "3";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "6";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "cGrid";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "7";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.SearchProperties["TagName"] = "TBODY";
                    this.mUIItemCustom.FilterProperties["Class"] = null;
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIEmployeeCodedUIAdminDocument1 : HtmlDocument
    {
        
        public UIEmployeeCodedUIAdminDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "ctl00_body";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Employee: CodedUIAdmin";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/shared/admin/aeemployee.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://testing.sel-expenses.com/shared/admin/aeemployee.aspx?employeeid=32070";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        #region Properties
        public UITbl_gridCards_2019Row UITbl_gridCards_2019Row
        {
            get
            {
                if ((this.mUITbl_gridCards_2019Row == null))
                {
                    this.mUITbl_gridCards_2019Row = new UITbl_gridCards_2019Row(this);
                }
                return this.mUITbl_gridCards_2019Row;
            }
        }
        #endregion
        
        #region Fields
        private UITbl_gridCards_2019Row mUITbl_gridCards_2019Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UITbl_gridCards_2019Row : HtmlRow
    {
        
        public UITbl_gridCards_2019Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlRow.PropertyNames.Id] = "tbl_gridCards_2019";
            this.SearchProperties[HtmlRow.PropertyNames.Name] = null;
            this.FilterProperties[HtmlRow.PropertyNames.InnerText] = "Credit CardBarclaycard12345";
            this.FilterProperties[HtmlRow.PropertyNames.ControlDefinition] = "id=tbl_gridCards_2019";
            this.FilterProperties[HtmlRow.PropertyNames.RowIndex] = "1";
            this.FilterProperties[HtmlRow.PropertyNames.Class] = null;
            this.FilterProperties[HtmlRow.PropertyNames.TagInstance] = "14";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIDeleteImage
        {
            get
            {
                if ((this.mUIDeleteImage == null))
                {
                    this.mUIDeleteImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIDeleteImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIDeleteImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIDeleteImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Delete";
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/shared/images/icons/delete2.png";
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://testing.sel-expenses.com/shared/images/icons/delete2.png";
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "deleteCorporateCard(2019);";
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.Href] = "javascript:deleteCorporateCard(2019);";
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=Delete src=\"/shared/images/icons/del";
                    this.mUIDeleteImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "2";
                    this.mUIDeleteImage.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUIDeleteImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIDeleteImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIEmployeeCodedUIAdminDocument2 : HtmlDocument
    {
        
        public UIEmployeeCodedUIAdminDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "ctl00_body";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Employee: CodedUIAdmin";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/shared/admin/aeemployee.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://testing.sel-expenses.com/shared/admin/aeemployee.aspx?employeeid=21359";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        #region Properties
        public UIEditgridCards_2070Cell UIEditgridCards_2070Cell
        {
            get
            {
                if ((this.mUIEditgridCards_2070Cell == null))
                {
                    this.mUIEditgridCards_2070Cell = new UIEditgridCards_2070Cell(this);
                }
                return this.mUIEditgridCards_2070Cell;
            }
        }
        #endregion
        
        #region Fields
        private UIEditgridCards_2070Cell mUIEditgridCards_2070Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIEditgridCards_2070Cell : HtmlCell
    {
        
        public UIEditgridCards_2070Cell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlCell.PropertyNames.Id] = "editgridCards_2070";
            this.SearchProperties[HtmlCell.PropertyNames.Name] = null;
            this.FilterProperties[HtmlCell.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "id=editgridCards_2070 class=row1";
            this.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
            this.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
            this.FilterProperties[HtmlCell.PropertyNames.Class] = "row1";
            this.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "66";
            this.WindowTitles.Add("Employee: CodedUIAdmin");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIEditImage
        {
            get
            {
                if ((this.mUIEditImage == null))
                {
                    this.mUIEditImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIEditImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIEditImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIEditImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Edit";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/shared/images/icons/edit.png";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://testing.sel-expenses.com/shared/images/icons/edit.png";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "editCorporateCard(2070);";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.Href] = "javascript:editCorporateCard(2070);";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=Edit src=\"/shared/images/icons/edit.";
                    this.mUIEditImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIEditImage.WindowTitles.Add("Employee: CodedUIAdmin");
                    #endregion
                }
                return this.mUIEditImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIEditImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIMessagefromwebpageWindow : WinWindow
    {
        
        public UIMessagefromwebpageWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Message from webpage";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Message from webpage");
            #endregion
        }
        
        #region Properties
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Message from webpage");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Message from webpage");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
