// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Auto_Tests.UIMaps.PoolCarsUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class PoolCarsUIMap
    {
        
        /// <summary>
        /// ClickNewPoolCarLink
        /// </summary>
        public void ClickNewPoolCarLink()
        {
            #region Variable Declarations
            HtmlHyperlink newPoolCarHyperlink = this.EmployeePoolCarControlsWindow.EmployeePoolCarControlsDocument.NewPoolCarPane.NewPoolCarHyperlink;
            #endregion

            // Click 'New Pool Car' link
            Mouse.Click(newPoolCarHyperlink, new Point(63, 12));
        }
        
        /// <summary>
        /// ClickPoolCarsLink
        /// </summary>
        public void ClickPoolCarsLink()
        {
            #region Variable Declarations
            HtmlHyperlink poolCarsHyperlink = this.EmployeePoolCarControlsWindow.EmployeePoolCarControlsDocument.PoolCarsHyperlink;
            #endregion

            // Click 'Pool Cars' link
            Mouse.Click(poolCarsHyperlink, new Point(53, 9));
        }
        
        /// <summary>
        /// PressCancelAddPoolCar
        /// </summary>
        public void PressCancelAddPoolCar()
        {
            #region Variable Declarations
            HtmlInputButton cancelButton = this.PoolCarGridWindow.PoolCarGridDocument.CancelButton;
            #endregion

            // Click 'ctl00$contentmain$cmdpoolcarcancel' button
            Mouse.Click(cancelButton, new Point(30, 16));
        }
        
        /// <summary>
        /// PressSavePoolCar
        /// </summary>
        public void PressSavePoolCar()
        {
            #region Variable Declarations
            HtmlImage oKImageButton = this.EmployeePoolCarControlsWindow.EmployeePoolCarControlsDocument.UICtl00_contentmain_pnPane.OKImageButton;
            #endregion

            // Click 'OK' image
            Mouse.Click(oKImageButton, new Point(27, 18));
        }
        
        #region Properties
        public EmployeePoolCarControlsWindow EmployeePoolCarControlsWindow
        {
            get
            {
                if ((this.mEmployeePoolCarControlsWindow == null))
                {
                    this.mEmployeePoolCarControlsWindow = new EmployeePoolCarControlsWindow();
                }
                return this.mEmployeePoolCarControlsWindow;
            }
        }
        
        public PoolCarGridWindow PoolCarGridWindow
        {
            get
            {
                if ((this.mPoolCarGridWindow == null))
                {
                    this.mPoolCarGridWindow = new PoolCarGridWindow();
                }
                return this.mPoolCarGridWindow;
            }
        }
        #endregion
        
        #region Fields
        private EmployeePoolCarControlsWindow mEmployeePoolCarControlsWindow;
        
        private PoolCarGridWindow mPoolCarGridWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class EmployeePoolCarControlsWindow : BrowserWindow
    {
        
        public EmployeePoolCarControlsWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public EmployeePoolCarControlsDocument EmployeePoolCarControlsDocument
        {
            get
            {
                if ((this.mEmployeePoolCarControlsDocument == null))
                {
                    this.mEmployeePoolCarControlsDocument = new EmployeePoolCarControlsDocument(this);
                }
                return this.mEmployeePoolCarControlsDocument;
            }
        }
        #endregion
        
        #region Fields
        private EmployeePoolCarControlsDocument mEmployeePoolCarControlsDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class EmployeePoolCarControlsDocument : HtmlDocument
    {
        
        public EmployeePoolCarControlsDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "ctl00_body";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/shared/admin/aeemployee.aspx";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "sel-expenses.com/shared/admin/aeemployee.aspx?employeeid=32054", PropertyExpressionOperator.Contains));
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink PoolCarsHyperlink
        {
            get
            {
                if ((this.mPoolCarsHyperlink == null))
                {
                    this.mPoolCarsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mPoolCarsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "lnkPoolCars";
                    this.mPoolCarsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mPoolCarsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mPoolCarsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Pool Cars";
                    this.mPoolCarsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "changePage(\'PoolCars\');";
                    this.mPoolCarsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mPoolCarsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:changePage(\'PoolCars\');";
                    this.mPoolCarsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mPoolCarsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=lnkPoolCars href=\"javascript:changePa";
                    this.mPoolCarsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    #endregion
                }
                return this.mPoolCarsHyperlink;
            }
        }
        
        public NewPoolCarPane NewPoolCarPane
        {
            get
            {
                if ((this.mNewPoolCarPane == null))
                {
                    this.mNewPoolCarPane = new NewPoolCarPane(this);
                }
                return this.mNewPoolCarPane;
            }
        }
        
        public HtmlComboBox PoolCarComboBox
        {
            get
            {
                if ((this.mPoolCarComboBox == null))
                {
                    this.mPoolCarComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mPoolCarComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ctl00_contentmain_txtPoolCarSelect";
                    this.mPoolCarComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ctl00$contentmain$txtPoolCarSelect";
                    this.mPoolCarComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mPoolCarComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "Pool Car";
                    this.mPoolCarComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mPoolCarComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "11";
                    this.mPoolCarComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = null;
                    this.mPoolCarComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "id=ctl00_contentmain_cmbPoolCars name=ct";
                    this.mPoolCarComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "21";
                    #endregion
                }
                return this.mPoolCarComboBox;
            }
        }
        
        public UICtl00_contentmain_pnPane UICtl00_contentmain_pnPane
        {
            get
            {
                if ((this.mUICtl00_contentmain_pnPane == null))
                {
                    this.mUICtl00_contentmain_pnPane = new UICtl00_contentmain_pnPane(this);
                }
                return this.mUICtl00_contentmain_pnPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mPoolCarsHyperlink;
        
        private NewPoolCarPane mNewPoolCarPane;
        
        private HtmlComboBox mPoolCarComboBox;
        
        private UICtl00_contentmain_pnPane mUICtl00_contentmain_pnPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class NewPoolCarPane : HtmlDiv
    {
        
        public NewPoolCarPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "pgOptPoolCars";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "New Pool Car ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=pgOptPoolCars  className";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "12";
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink NewPoolCarHyperlink
        {
            get
            {
                if ((this.mNewPoolCarHyperlink == null))
                {
                    this.mNewPoolCarHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mNewPoolCarHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mNewPoolCarHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mNewPoolCarHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mNewPoolCarHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "New Pool Car";
                    this.mNewPoolCarHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "showPoolCarModal(true);";
                    this.mNewPoolCarHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mNewPoolCarHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:showPoolCarModal(true);";
                    this.mNewPoolCarHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "submenuitem";
                    this.mNewPoolCarHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=submenuitem href=\"javascript:showP";
                    this.mNewPoolCarHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    #endregion
                }
                return this.mNewPoolCarHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mNewPoolCarHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICtl00_contentmain_pnPane : HtmlDiv
    {
        
        public UICtl00_contentmain_pnPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "ctl00_contentmain_pnlPoolCar";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "General Details\r\nPool Car VW Golf FY54 T";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "modalpanel";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"Z-INDEX: 10001; POSITION: fixed; ";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "243";
            #endregion
        }
        
        #region Properties
        public HtmlImage OKImageButton
        {
            get
            {
                if ((this.mOKImageButton == null))
                {
                    this.mOKImageButton = new HtmlImage(this);
                    #region Search Criteria
                    this.mOKImageButton.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mOKImageButton.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mOKImageButton.SearchProperties[HtmlImage.PropertyNames.Alt] = "OK";
                    this.mOKImageButton.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/shared/images/buttons/btn_save.png";
                    this.mOKImageButton.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.Src, "sel-expenses.com/shared/images/buttons/btn_save.png", PropertyExpressionOperator.Contains));
                    this.mOKImageButton.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mOKImageButton.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=OK src=\"/shared/images/buttons/btn_s";
                    this.mOKImageButton.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    #endregion
                }
                return this.mOKImageButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mOKImageButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class PoolCarGridWindow : BrowserWindow
    {
        
        public PoolCarGridWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public PoolCarGridDocument PoolCarGridDocument
        {
            get
            {
                if ((this.mPoolCarGridDocument == null))
                {
                    this.mPoolCarGridDocument = new PoolCarGridDocument(this);
                }
                return this.mPoolCarGridDocument;
            }
        }
        #endregion
        
        #region Fields
        private PoolCarGridDocument mPoolCarGridDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class PoolCarGridDocument : HtmlDocument
    {
        
        public PoolCarGridDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "ctl00_body";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/shared/admin/aeemployee.aspx";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "sel-expenses.com/shared/admin/aeemployee.aspx?employeeid=27", PropertyExpressionOperator.Contains));
            #endregion
        }
        
        #region Properties
        public HtmlTable PoolCarsGrid
        {
            get
            {
                if ((this.mPoolCarsGrid == null))
                {
                    this.mPoolCarsGrid = new HtmlTable(this);
                    #region Search Criteria
                    this.mPoolCarsGrid.SearchProperties[HtmlTable.PropertyNames.Id] = "tbl_gridPoolCars";
                    this.mPoolCarsGrid.SearchProperties[HtmlTable.PropertyNames.Name] = null;
                    this.mPoolCarsGrid.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Vehicle MakeVehicle ModelRegistration Nu";
                    this.mPoolCarsGrid.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=tbl_gridPoolCars class=cGrid";
                    this.mPoolCarsGrid.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
                    this.mPoolCarsGrid.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "8";
                    this.mPoolCarsGrid.FilterProperties[HtmlTable.PropertyNames.Class] = "cGrid";
                    this.mPoolCarsGrid.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "6";
                    #endregion
                }
                return this.mPoolCarsGrid;
            }
        }
        
        public HtmlInputButton CancelButton
        {
            get
            {
                if ((this.mCancelButton == null))
                {
                    this.mCancelButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mCancelButton.SearchProperties[HtmlButton.PropertyNames.Id] = "ctl00_contentmain_cmdpoolcarcancel";
                    this.mCancelButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$contentmain$cmdpoolcarcancel";
                    this.mCancelButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = null;
                    this.mCancelButton.FilterProperties[HtmlButton.PropertyNames.Type] = "image";
                    this.mCancelButton.FilterProperties.Add(new PropertyExpression("Src", "sel-expenses.com/shared/images/buttons/cancel_up.gif", PropertyExpressionOperator.Contains));
                    this.mCancelButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mCancelButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mCancelButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=ctl00_contentmain_cmdpoolcarcancel st";
                    this.mCancelButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "140";
                    #endregion
                }
                return this.mCancelButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlTable mPoolCarsGrid;
        
        private HtmlInputButton mCancelButton;
        #endregion
    }
}
