ALTER TABLE [dbo].[customEntities]
    ADD CONSTRAINT [IX_customEntities] UNIQUE NONCLUSTERED ([entity_name] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

