ALTER TABLE [dbo].[item_roles]
    ADD CONSTRAINT [IX_item_roles] UNIQUE NONCLUSTERED ([rolename] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

