ALTER TABLE [dbo].[workflowsApproval]
    ADD CONSTRAINT [IX_workflows_approval] UNIQUE NONCLUSTERED ([workflowStepID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

