ALTER TABLE [dbo].[invoiceProductDetails]
    ADD CONSTRAINT [PK__invoice_productd__1BFBC723] PRIMARY KEY CLUSTERED ([invoiceProductID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

