ALTER TABLE [dbo].[savedexpenses_costcodes]
    ADD CONSTRAINT [PK__savedexpenses-co__2739D489] PRIMARY KEY CLUSTERED ([savedcostcodeid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

