ALTER TABLE [dbo].[document_mergeprojects]
    ADD CONSTRAINT [PK__document_mergepr__156D2E77] PRIMARY KEY CLUSTERED ([mergeprojectid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

