ALTER TABLE [dbo].[codes_contractcategory]
    ADD CONSTRAINT [PK__codes_contractca__04AF18CE] PRIMARY KEY CLUSTERED ([categoryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

