ALTER TABLE [dbo].[rolesubcats]
    ADD CONSTRAINT [PK__rolesubcats__25518C17] PRIMARY KEY CLUSTERED ([rolesubcatid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

