ALTER TABLE [dbo].[importHistory]
    ADD CONSTRAINT [PK__importHistory__60DE2EB1] PRIMARY KEY CLUSTERED ([historyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

