ALTER TABLE [dbo].[invoices]
    ADD CONSTRAINT [PK__invoice_details__76CA4274] PRIMARY KEY CLUSTERED ([invoiceID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

