ALTER TABLE [dbo].[userdefinedSupplierContacts]
    ADD CONSTRAINT [PK__userdefinedSuppl__5B694530] PRIMARY KEY CLUSTERED ([contactid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

