ALTER TABLE [dbo].[supplier_addresses]
    ADD CONSTRAINT [PK__supplier_address__016F8C14] PRIMARY KEY CLUSTERED ([addressid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

