ALTER TABLE [dbo].[supplierContactNotes]
    ADD CONSTRAINT [PK__vendorcontact_no__5B42EEE7] PRIMARY KEY CLUSTERED ([noteId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

