ALTER TABLE [dbo].[countrysubcats]
    ADD CONSTRAINT [PK__countrysubcats__398D8EEE] PRIMARY KEY CLUSTERED ([countrysubcatid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

