ALTER TABLE [dbo].[invoiceStatusType]
    ADD CONSTRAINT [PK__codes_invoicesta__13F15C5E] PRIMARY KEY CLUSTERED ([invoiceStatusTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

