ALTER TABLE [dbo].[pdcats]
    ADD CONSTRAINT [PK__pdcats__1DB06A4F] PRIMARY KEY CLUSTERED ([pdcatid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

