ALTER TABLE [dbo].[tasks]
    ADD CONSTRAINT [PK__tasks__0DC5E3C1] PRIMARY KEY CLUSTERED ([taskId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

