ALTER TABLE [dbo].[supplier_categories]
    ADD CONSTRAINT [PK__supplier_categor__2E973846] PRIMARY KEY CLUSTERED ([categoryid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

