ALTER TABLE [dbo].[financial_status]
    ADD CONSTRAINT [PK__codes_financials__0D445ECF] PRIMARY KEY CLUSTERED ([statusid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

