ALTER TABLE [dbo].[groups]
    ADD CONSTRAINT [PK__groups__1BC821DD] PRIMARY KEY CLUSTERED ([groupid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

