ALTER TABLE [dbo].[productLicences]
    ADD CONSTRAINT [PK__product_licences__19D2BC38] PRIMARY KEY CLUSTERED ([licenceID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

