ALTER TABLE [dbo].[reasons]
    ADD CONSTRAINT [PK__reasons__208CD6FA] PRIMARY KEY CLUSTERED ([reasonid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

