ALTER TABLE [dbo].[userdefinedProductDetails]
    ADD CONSTRAINT [PK__userdefinedProdu__55B06BDA] PRIMARY KEY CLUSTERED ([productid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

