ALTER TABLE [dbo].[supplier_details]
    ADD CONSTRAINT [PK__supplier_details__3173A4F1] PRIMARY KEY CLUSTERED ([supplierid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

