ALTER TABLE [dbo].[codes_tasktypes]
    ADD CONSTRAINT [PK__codes_tasktypes__0AE97716] PRIMARY KEY CLUSTERED ([typeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

