ALTER TABLE [dbo].[attachments]
    ADD CONSTRAINT [PK_Attachments] PRIMARY KEY CLUSTERED ([attachmentId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

