ALTER TABLE [dbo].[accountsSubAccounts]
    ADD CONSTRAINT [PK_accountsSubAccounts] PRIMARY KEY CLUSTERED ([subAccountID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

