ALTER TABLE [dbo].[additems]
    ADD CONSTRAINT [PK_additems] PRIMARY KEY NONCLUSTERED ([employeeid] ASC, [subcatid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

