ALTER TABLE [dbo].[audienceTeams]
    ADD CONSTRAINT [PK_audienceTeams] PRIMARY KEY CLUSTERED ([audienceTeamID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

