ALTER TABLE [dbo].[customJoinTables]
    ADD CONSTRAINT [PK_customJoinTables] PRIMARY KEY NONCLUSTERED ([jointableid]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
