ALTER TABLE [dbo].[currencymonths]
    ADD CONSTRAINT [PK_currencymonths] PRIMARY KEY NONCLUSTERED ([currencymonthid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

