ALTER TABLE [dbo].[customMenuStructure]
    ADD CONSTRAINT [PK_customMenuStructure] PRIMARY KEY CLUSTERED ([menuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

