ALTER TABLE [dbo].[customEntityAttributes]
    ADD CONSTRAINT [PK_customEntityAttributes] PRIMARY KEY CLUSTERED ([attributeid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

