ALTER TABLE [dbo].[customEntityFormSections]
    ADD CONSTRAINT [PK_customEntityFormSections] PRIMARY KEY CLUSTERED ([sectionid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

