ALTER TABLE [dbo].[customEntityFormTabs]
    ADD CONSTRAINT [PK_customEntityFormTabs] PRIMARY KEY CLUSTERED ([tabid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

