ALTER TABLE [dbo].[customEntityAttachmentFields]
    ADD CONSTRAINT [PK_customEntityAttachmentFields] PRIMARY KEY NONCLUSTERED ([fieldid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

