ALTER TABLE [dbo].[customEntityForms]
    ADD CONSTRAINT [PK_customEntityForms] PRIMARY KEY CLUSTERED ([formid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

