ALTER TABLE [dbo].[customEntities]
    ADD CONSTRAINT [PK_customEntities] PRIMARY KEY CLUSTERED ([entityid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

