ALTER TABLE [dbo].[customEntityFormFields]
    ADD CONSTRAINT [PK_customEntityFormFields] PRIMARY KEY CLUSTERED ([formid] ASC, [attributeid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

