ALTER TABLE [dbo].[car_documents]
    ADD CONSTRAINT [PK_car_documents] PRIMARY KEY CLUSTERED ([documentid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

