ALTER TABLE [dbo].[customMimeHeaders]
    ADD CONSTRAINT [PK_customMimeHeaders_1] PRIMARY KEY CLUSTERED ([customMimeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

