ALTER TABLE [dbo].[contract_audience]
    ADD CONSTRAINT [PK_contract_audience] PRIMARY KEY CLUSTERED ([audienceId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

