ALTER TABLE [dbo].[customEntityViews]
    ADD CONSTRAINT [PK_customEntityViews] PRIMARY KEY CLUSTERED ([viewid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

