ALTER TABLE [dbo].[default_views]
    ADD CONSTRAINT [PK_default_views] PRIMARY KEY NONCLUSTERED ([fieldID] ASC, [order] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

