ALTER TABLE [dbo].[emailTemplate_attachments]
    ADD CONSTRAINT [PK_emailTemplate_attachments] PRIMARY KEY CLUSTERED ([attachmentID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

