ALTER TABLE [dbo].[employeeGridSortOrders]
    ADD CONSTRAINT [PK_employeeGridSortOrders] PRIMARY KEY CLUSTERED ([employeeID] ASC, [gridID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

