ALTER TABLE [dbo].[emailTemplateRecipients]
    ADD CONSTRAINT [PK_emailTemplateRecipients] PRIMARY KEY CLUSTERED ([emailRecipientID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

