ALTER TABLE [dbo].[employee_roles]
    ADD CONSTRAINT [PK_employee_roles] PRIMARY KEY CLUSTERED ([employeeid] ASC, [itemroleid] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

