ALTER TABLE [dbo].[ESRElementSubcats]
    ADD CONSTRAINT [PK_esrElementSubcats] PRIMARY KEY CLUSTERED ([elementSubcatID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

