ALTER TABLE [dbo].[employeeHomeLocations]
    ADD CONSTRAINT [PK_employeeHomeLocations] PRIMARY KEY CLUSTERED ([employeeLocationID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

