ALTER TABLE [dbo].[emailTemplates]
    ADD CONSTRAINT [PK_email_templates] PRIMARY KEY CLUSTERED ([emailtemplateid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

