ALTER TABLE [dbo].[exporthistory]
    ADD CONSTRAINT [PK_exporthistory] PRIMARY KEY CLUSTERED ([exporthistoryid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

