ALTER TABLE [dbo].[exporteditems]
    ADD CONSTRAINT [PK_exporteditems] PRIMARY KEY CLUSTERED ([exportid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

