ALTER TABLE [dbo].[emailTemplateBodyFields]
    ADD CONSTRAINT [PK_emailTemplateBodyFields_1] PRIMARY KEY CLUSTERED ([emailBodyFieldID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

