ALTER TABLE [dbo].[ESRElementFields]
    ADD CONSTRAINT [PK_ESRElementFields] PRIMARY KEY CLUSTERED ([elementFieldID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

