ALTER TABLE [dbo].[employee_costcodes]
    ADD CONSTRAINT [PK_employee_costcodes] PRIMARY KEY CLUSTERED ([employeecostcodeid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

