ALTER TABLE [dbo].[email_schedule]
    ADD CONSTRAINT [PK_Email_Schedule] PRIMARY KEY CLUSTERED ([scheduleId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

