ALTER TABLE [dbo].[flagAssociatedExpenseItems]
    ADD CONSTRAINT [PK_flagAssociatedExpenseItems] PRIMARY KEY CLUSTERED ([flagID] ASC, [subCatID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

