ALTER TABLE [dbo].[fields_userdefined]
    ADD CONSTRAINT [PK_fields-userdefined] PRIMARY KEY CLUSTERED ([fieldid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

