ALTER TABLE [dbo].[flagAssociatedFields]
    ADD CONSTRAINT [PK_flagAssociatedFields] PRIMARY KEY CLUSTERED ([flagID] ASC, [fieldID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

