ALTER TABLE [dbo].[filter_rules]
    ADD CONSTRAINT [PK_filter_rule] PRIMARY KEY CLUSTERED ([filterid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

