ALTER TABLE [dbo].[customised_help_text]
    ADD CONSTRAINT [PK_help_text] PRIMARY KEY NONCLUSTERED ([tooltipID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

