ALTER TABLE [dbo].[invoiceHistory]
    ADD CONSTRAINT [PK_invoiceHistory] PRIMARY KEY CLUSTERED ([invoiceHistoryID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

