ALTER TABLE [dbo].[importTemplateMappings]
    ADD CONSTRAINT [PK_importTemplateMappings] PRIMARY KEY CLUSTERED ([templateMappingID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

