ALTER TABLE [dbo].[item_roles]
    ADD CONSTRAINT [PK_item_roles] PRIMARY KEY CLUSTERED ([itemroleid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

