ALTER TABLE [dbo].[importTemplates]
    ADD CONSTRAINT [PK_importTemplates] PRIMARY KEY CLUSTERED ([templateID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

