ALTER TABLE [dbo].[joinVia]
	ADD CONSTRAINT [PK_joinVia] PRIMARY KEY CLUSTERED ([joinViaID] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON);
