ALTER TABLE [dbo].[joinViaParts]
	ADD CONSTRAINT [PK_joinViaParts] PRIMARY KEY CLUSTERED ([joinViaPartID] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON);
