ALTER TABLE [dbo].[logDataItems]
    ADD CONSTRAINT [PK_logDataItems] PRIMARY KEY CLUSTERED ([logDataID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

