ALTER TABLE [dbo].[link_definitions]
    ADD CONSTRAINT [PK_link_definitions] PRIMARY KEY CLUSTERED ([linkId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

