ALTER TABLE [dbo].[mobileDevices]
    ADD CONSTRAINT [PK_mobileDevices] PRIMARY KEY CLUSTERED ([mobileDeviceID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

