ALTER TABLE [dbo].[project_codes]
    ADD CONSTRAINT [PK_project_codes] PRIMARY KEY CLUSTERED ([projectcodeid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

