ALTER TABLE [dbo].[purchaseOrderProducts]
    ADD CONSTRAINT [PK_purchaseOrderProducts_1] PRIMARY KEY CLUSTERED ([purchaseOrderProductID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

