ALTER TABLE [dbo].[purchaseOrderHistory]
    ADD CONSTRAINT [PK_purchaseOrderHistory] PRIMARY KEY CLUSTERED ([purchaseOrderHistoryID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

