ALTER TABLE [dbo].[printout]
    ADD CONSTRAINT [PK_printout] PRIMARY KEY NONCLUSTERED ([fieldID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

