ALTER TABLE [dbo].[previouspasswords]
    ADD CONSTRAINT [PK_previouspasswords] PRIMARY KEY CLUSTERED ([employeeid] ASC, [order] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

