ALTER TABLE [dbo].[purchaseOrders]
    ADD CONSTRAINT [PK_purchaseOrders] PRIMARY KEY CLUSTERED ([purchaseOrderID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

