ALTER TABLE [dbo].[purchaseOrderDeliveries]
    ADD CONSTRAINT [PK_purchaseOrderDeliveries] PRIMARY KEY CLUSTERED ([deliveryID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

