ALTER TABLE [dbo].[returnedexpenses]
    ADD CONSTRAINT [PK_returnedexpenses] PRIMARY KEY NONCLUSTERED ([returnid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

