ALTER TABLE [dbo].[report_folders]
    ADD CONSTRAINT [PK_report_folders_1] PRIMARY KEY CLUSTERED ([folderID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

