ALTER TABLE [dbo].[reportsLog]
    ADD CONSTRAINT [PK_reportsLog] PRIMARY KEY CLUSTERED ([reportsLogId] ASC) 
	WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
