ALTER TABLE [dbo].[reports_export_options]
    ADD CONSTRAINT [PK_reports_export_options_1] PRIMARY KEY CLUSTERED ([employeeid] ASC, [reportID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

