ALTER TABLE [dbo].[reports]
    ADD CONSTRAINT [PK_reports_1] PRIMARY KEY NONCLUSTERED ([reportID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

