ALTER TABLE [dbo].[range_exchangerates]
    ADD CONSTRAINT [PK_range_exchangerates] PRIMARY KEY CLUSTERED ([currencyrangeid] ASC, [tocurrencyid] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

