ALTER TABLE [dbo].[subcat_split]
    ADD CONSTRAINT [PK_subcat_split] PRIMARY KEY CLUSTERED ([primarysubcatid] ASC, [splitsubcatid] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

