ALTER TABLE [dbo].[savedexpenses_flags]
    ADD CONSTRAINT [PK_savedexpenses-flags] PRIMARY KEY CLUSTERED ([flagid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

