ALTER TABLE [dbo].[userdefinedInvoiceDetails]
    ADD CONSTRAINT [PK_userdefinedInvoiceDetails] PRIMARY KEY CLUSTERED ([invoiceid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

