ALTER TABLE [dbo].[user_preferences]
    ADD CONSTRAINT [PK_user_preferences] PRIMARY KEY CLUSTERED ([preferenceId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

