ALTER TABLE [dbo].[views]
    ADD CONSTRAINT [PK_views] PRIMARY KEY CLUSTERED ([viewsid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

