ALTER TABLE [dbo].[workflowEntityState]
    ADD CONSTRAINT [PK_workflow_entity_state] PRIMARY KEY CLUSTERED ([workflowID] ASC, [entityID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

