ALTER TABLE [dbo].[workflowDynamicValues]
    ADD CONSTRAINT [PK_workflowDynamicValues] PRIMARY KEY CLUSTERED ([dynamicValueID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

