ALTER TABLE [dbo].[workflowsApproval]
    ADD CONSTRAINT [PK_workflowsApproval] PRIMARY KEY CLUSTERED ([workflowStepID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

