ALTER TABLE [dbo].[workflowSubWorkflowTracker]
    ADD CONSTRAINT [PK_workflowSubWorkflowTracker] PRIMARY KEY CLUSTERED ([workflowTrackerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

