ALTER TABLE [dbo].[accessRoles]
    ADD CONSTRAINT [IX_accessRoles] UNIQUE NONCLUSTERED ([rolename] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

