ALTER TABLE [dbo].[allowances]
    ADD CONSTRAINT [IX_allowances] UNIQUE NONCLUSTERED ([allowance] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

