ALTER TABLE [dbo].[budgetholders]
    ADD CONSTRAINT [IX_budgetholders] UNIQUE NONCLUSTERED ([budgetholder] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

