ALTER TABLE [dbo].[custom_entities]
    ADD CONSTRAINT [IX_custom_entities_2] UNIQUE NONCLUSTERED ([attachmentTableID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

