ALTER TABLE [dbo].[custom_tables]
    ADD CONSTRAINT [IX_custom_tables] UNIQUE NONCLUSTERED ([tablename] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

