ALTER TABLE [dbo].[companies]
    ADD CONSTRAINT [IX_companies_1] UNIQUE NONCLUSTERED ([company] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

