ALTER TABLE [dbo].[workflows]
    ADD CONSTRAINT [IX_workflows] UNIQUE NONCLUSTERED ([workflowName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

