ALTER TABLE [dbo].[cars]
    ADD CONSTRAINT [PK__cars__151B244E] PRIMARY KEY CLUSTERED ([carid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

