ALTER TABLE [dbo].[codes_contracttype]
    ADD CONSTRAINT [PK__codes_contractty__06976140] PRIMARY KEY CLUSTERED ([contractTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

