ALTER TABLE [dbo].[codes_contractstatus]
    ADD CONSTRAINT [PK__codes_contractst__087FA9B2] PRIMARY KEY CLUSTERED ([statusId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

