ALTER TABLE [dbo].[autoActionLog]
    ADD CONSTRAINT [PK__autoActionLog__5D2D995E] PRIMARY KEY CLUSTERED ([actionid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

