ALTER TABLE [dbo].[signoffs]
    ADD CONSTRAINT [PK__signoffs__282DF8C2] PRIMARY KEY CLUSTERED ([signoffid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

