ALTER TABLE [dbo].[supplier_contacts]
    ADD CONSTRAINT [PK__supplier_contact__372C7E47] PRIMARY KEY CLUSTERED ([contactid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

