ALTER TABLE [dbo].[codes_licencetypes]
    ADD CONSTRAINT [PK__codes_licencetyp__527BCC18] PRIMARY KEY CLUSTERED ([licenceTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

