ALTER TABLE [dbo].[document_mappings_field]
    ADD CONSTRAINT [PK__document_mapping__3E7A3102] PRIMARY KEY CLUSTERED ([mappingid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

