ALTER TABLE [dbo].[codes_termtype]
    ADD CONSTRAINT [PK__codes_termtype__251BE860] PRIMARY KEY CLUSTERED ([termTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

