ALTER TABLE [dbo].[salesTax]
    ADD CONSTRAINT [PK__salesTax__1BE6B88A] PRIMARY KEY CLUSTERED ([salesTaxID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

