ALTER TABLE [dbo].[teamemps]
    ADD CONSTRAINT [PK__teamemps__4E88ABD4] PRIMARY KEY CLUSTERED ([teamempid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

