ALTER TABLE [dbo].[invoiceLineItemCostCentres]
    ADD CONSTRAINT [PK__invoiceLineItems__45DE8904] PRIMARY KEY CLUSTERED ([invoiceLineItemCostCentreId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

