ALTER TABLE [dbo].[licenceRenewalTypes]
    ADD CONSTRAINT [PK__codes_licenceren__0A9078A8] PRIMARY KEY CLUSTERED ([renewalType] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

