ALTER TABLE [dbo].[invoiceLog]
    ADD CONSTRAINT [PK__invoice_log__7B8EF791] PRIMARY KEY CLUSTERED ([invoiceLogID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

