ALTER TABLE [dbo].[productCategories]
    ADD CONSTRAINT [PK__codes_productcat__41219383] PRIMARY KEY CLUSTERED ([categoryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

