ALTER TABLE [dbo].[codes_rechargeentity]
    ADD CONSTRAINT [PK__codes_rechargeen__1B927E26] PRIMARY KEY CLUSTERED ([entityId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

