ALTER TABLE [dbo].[document_mappings_static]
    ADD CONSTRAINT [PK__document_mapping__48F7BF75] PRIMARY KEY CLUSTERED ([mappingid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

