ALTER TABLE [dbo].[teams]
    ADD CONSTRAINT [PK__teams__2A164134] PRIMARY KEY CLUSTERED ([teamid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

