ALTER TABLE [dbo].[cardrecords]
    ADD CONSTRAINT [PK__cardrecords__1332DBDC] PRIMARY KEY CLUSTERED ([cardrecordid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

