ALTER TABLE [dbo].[budgetholders]
    ADD CONSTRAINT [PK__costcodes__17036CC0] PRIMARY KEY CLUSTERED ([budgetholderid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

