ALTER TABLE [dbo].[productDetails]
    ADD CONSTRAINT [PK__product_details__17EA73C6] PRIMARY KEY CLUSTERED ([productId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

