ALTER TABLE [dbo].[document_mappings_text]
    ADD CONSTRAINT [PK__document_mapping__1E027478] PRIMARY KEY CLUSTERED ([static_textid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

