ALTER TABLE [dbo].[document_templates]
    ADD CONSTRAINT [PK__document_templat__1BA52ABA] PRIMARY KEY CLUSTERED ([documentid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

