ALTER TABLE [dbo].[invoiceNotes]
    ADD CONSTRAINT [PK__invoice_notes__7F5F8875] PRIMARY KEY CLUSTERED ([noteID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

