ALTER TABLE [dbo].[exports]
    ADD CONSTRAINT [PK__exports__1AD3FDA4] PRIMARY KEY CLUSTERED ([exportid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

