ALTER TABLE [dbo].[task_history]
    ADD CONSTRAINT [PK__task_history__75AF2E65] PRIMARY KEY CLUSTERED ([historyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

