ALTER TABLE [dbo].[costcodes]
    ADD CONSTRAINT [PK__cost codes__160F4887] PRIMARY KEY CLUSTERED ([costcodeid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

