ALTER TABLE [dbo].[codes_units]
    ADD CONSTRAINT [PK__codes_units__0D97CDDC] PRIMARY KEY CLUSTERED ([unitId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

