ALTER TABLE [dbo].[supplier_status]
    ADD CONSTRAINT [PK__supplier_status__2AC6A762] PRIMARY KEY CLUSTERED ([statusid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

