ALTER TABLE [dbo].[purchaseOrderProductCostCentres]
    ADD CONSTRAINT [PK__purchaseOrderPro__43021C59] PRIMARY KEY CLUSTERED ([purchaseOrderProductCostCentreID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

