ALTER TABLE [dbo].[countries]
    ADD CONSTRAINT [PK__countries__17F790F9] PRIMARY KEY CLUSTERED ([countryid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

