ALTER TABLE [dbo].[holidays]
    ADD CONSTRAINT [PK__holidays__3F466844] PRIMARY KEY CLUSTERED ([holidayid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

