ALTER TABLE [dbo].[logon_trace]
    ADD CONSTRAINT [PK__logon_trace__0C5E54EA] PRIMARY KEY CLUSTERED ([traceId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

