ALTER TABLE [dbo].[accessRoleCustomEntityDetails]
    ADD CONSTRAINT [PK_accessRoleCustomEntityDetails_1] PRIMARY KEY CLUSTERED ([accessRoleCustomEntityDetailsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

