ALTER TABLE [dbo].[accessKeys]
    ADD CONSTRAINT [PK_accessKeys] PRIMARY KEY CLUSTERED ([KeyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

