ALTER TABLE [dbo].[audit_log]
    ADD CONSTRAINT [PK_audit_log] PRIMARY KEY CLUSTERED ([auditlogid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

