ALTER TABLE [dbo].[accessRoleElementDetails]
    ADD CONSTRAINT [PK_accessRoleElementDetails] PRIMARY KEY CLUSTERED ([roleID] ASC, [elementID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

