ALTER TABLE [dbo].[audienceBudgetHolders]
    ADD CONSTRAINT [PK_audienceBudgetHolders] PRIMARY KEY CLUSTERED ([audienceBudgetHolderID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

