ALTER TABLE [dbo].[addressPostcodeDistances]
    ADD CONSTRAINT [PK_addressPostcodeDistances] PRIMARY KEY CLUSTERED ([postcodeLookupID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

