ALTER TABLE [dbo].[accountProperties]
    ADD CONSTRAINT [PK_accountProperties] PRIMARY KEY CLUSTERED ([subAccountID] ASC, [stringKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

