ALTER TABLE [dbo].[accessRolesLink]
    ADD CONSTRAINT [PK_accessRolesLink] PRIMARY KEY CLUSTERED ([primaryAccessRoleID] ASC, [secondaryAccessRoleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

