ALTER TABLE [dbo].[contract_forecastdetails]
    ADD CONSTRAINT [PK_Contract_ForecastDetails] PRIMARY KEY CLUSTERED ([contractForecastId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

