ALTER TABLE [dbo].[contract_productplatforms]
    ADD CONSTRAINT [PK_Contract_ProductPlatforms] PRIMARY KEY CLUSTERED ([productPlatformId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

