ALTER TABLE [dbo].[custom_entity_form_tabs]
    ADD CONSTRAINT [PK_custom_entity_form_tabs] PRIMARY KEY CLUSTERED ([tabid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

