ALTER TABLE [dbo].[custom_menu_structure]
    ADD CONSTRAINT [PK_custom_menu_structure] PRIMARY KEY CLUSTERED ([menuid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

