ALTER TABLE [dbo].[custom_joinbreakdown]
    ADD CONSTRAINT [PK_custom_joinbreakdown] PRIMARY KEY CLUSTERED ([joinbreakdownid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

