ALTER TABLE [dbo].[custom_viewgroups]
    ADD CONSTRAINT [PK_custom_viewgroups] PRIMARY KEY CLUSTERED ([viewgroupid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

