ALTER TABLE [dbo].[corporate_cards]
    ADD CONSTRAINT [PK_corporate_cards_1] PRIMARY KEY CLUSTERED ([cardproviderid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

