ALTER TABLE [dbo].[contract_productdetails]
    ADD CONSTRAINT [PK_Contract_ProductDetails] PRIMARY KEY CLUSTERED ([contractProductId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

