ALTER TABLE [dbo].[categories]
    ADD CONSTRAINT [PK_categories] PRIMARY KEY NONCLUSTERED ([categoryid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

