ALTER TABLE [dbo].[codes_salestax]
    ADD CONSTRAINT [PK_Codes_SalesTax] PRIMARY KEY CLUSTERED ([salesTaxId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

