ALTER TABLE [dbo].[customEntityExportedItems]
    ADD CONSTRAINT [PK_customEntityExportedItems] PRIMARY KEY CLUSTERED ([exportRecordID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

