ALTER TABLE [dbo].[contract_forecastproducts]
    ADD CONSTRAINT [PK_Contract_ForecastProducts] PRIMARY KEY CLUSTERED ([forecastProductId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

