ALTER TABLE [dbo].[codes_notecategory]
    ADD CONSTRAINT [PK_Codes_NoteCategory] PRIMARY KEY CLUSTERED ([noteCatId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

