ALTER TABLE [dbo].[column_templates]
    ADD CONSTRAINT [PK_column_templates] PRIMARY KEY CLUSTERED ([templateid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

