ALTER TABLE [dbo].[custom_tables]
    ADD CONSTRAINT [PK_custom_tables] PRIMARY KEY CLUSTERED ([tableid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

