ALTER TABLE [dbo].[currencyranges]
    ADD CONSTRAINT [PK_currencyranges] PRIMARY KEY CLUSTERED ([currencyrangeid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

