ALTER TABLE [dbo].[contract_history]
    ADD CONSTRAINT [PK_contract_history] PRIMARY KEY CLUSTERED ([historyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

