ALTER TABLE [dbo].[contract_details]
    ADD CONSTRAINT [PK_Contract_Details] PRIMARY KEY CLUSTERED ([contractId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

