ALTER TABLE [dbo].[claims_base]
    ADD CONSTRAINT [PK_claims] PRIMARY KEY CLUSTERED ([claimid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

