ALTER TABLE [dbo].[custom_fields]
    ADD CONSTRAINT [PK_custom_fields] PRIMARY KEY CLUSTERED ([fieldid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

