ALTER TABLE [dbo].[cars_attachmentData]
    ADD CONSTRAINT [PK_car_attachmentsData] PRIMARY KEY CLUSTERED ([attachmentID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

