ALTER TABLE [dbo].[card_statements_base]
    ADD CONSTRAINT [PK_card_statements] PRIMARY KEY CLUSTERED ([statementid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

