ALTER TABLE [dbo].[custom_jointables]
    ADD CONSTRAINT [PK_custom_jointables] PRIMARY KEY CLUSTERED ([jointableid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

