ALTER TABLE [dbo].[custom_entity_views]
    ADD CONSTRAINT [PK_custom_entity_views] PRIMARY KEY CLUSTERED ([viewid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

