ALTER TABLE [dbo].[codes_inflatormetrics]
    ADD CONSTRAINT [PK_codes_inflatormetrics] PRIMARY KEY CLUSTERED ([metricId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

