ALTER TABLE [dbo].[contract_producthistory]
    ADD CONSTRAINT [PK_Contract_Product_History] PRIMARY KEY CLUSTERED ([productHistoryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

