ALTER TABLE [dbo].[document_mergesources]
    ADD CONSTRAINT [PK_document_mergesources] PRIMARY KEY CLUSTERED ([mergesourceid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

