ALTER TABLE [dbo].[default_sorts]
    ADD CONSTRAINT [PK_default_sorts] PRIMARY KEY CLUSTERED ([employeeid] ASC, [gridid] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

