ALTER TABLE [dbo].[employee_attachmentData]
    ADD CONSTRAINT [PK_employeeAttachmentsData] PRIMARY KEY CLUSTERED ([attachmentID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

