ALTER TABLE [dbo].[emailTemplate_attachmentData]
    ADD CONSTRAINT [PK_emailTemplate_attachmentData_1] PRIMARY KEY CLUSTERED ([attachmentID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

