ALTER TABLE [dbo].[employeeWorkLocations]
    ADD CONSTRAINT [PK_employeeWorkLocations_1] PRIMARY KEY CLUSTERED ([employeeLocationID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

