ALTER TABLE [dbo].[esr_assignments]
    ADD CONSTRAINT [PK_esr_assignments] PRIMARY KEY CLUSTERED ([esrAssignID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

