ALTER TABLE [dbo].[email_suffixes]
    ADD CONSTRAINT [PK_email_suffixes] PRIMARY KEY CLUSTERED ([suffixid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

