ALTER TABLE [dbo].[emailNotificationLink]
    ADD CONSTRAINT [PK_emailNotificationLink] PRIMARY KEY CLUSTERED ([emailNotificationLinkID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

