ALTER TABLE [dbo].[emailTemplateSubjectFields]
    ADD CONSTRAINT [PK_emailTemplateSubjectFields] PRIMARY KEY CLUSTERED ([emailSubjectFieldID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

