ALTER TABLE [dbo].[employeePasswordKeys]
    ADD CONSTRAINT [PK_employeePasswordKeys] PRIMARY KEY CLUSTERED ([passwordKeyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

