ALTER TABLE [dbo].[ESRElements]
    ADD CONSTRAINT [PK_ESRElements] PRIMARY KEY CLUSTERED ([elementID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

