ALTER TABLE [dbo].[flagAggregates]
    ADD CONSTRAINT [PK_flagAggregates] PRIMARY KEY CLUSTERED ([flagID] ASC, [aggregateFlagID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

