ALTER TABLE [dbo].[flags]
    ADD CONSTRAINT [PK_flags] PRIMARY KEY CLUSTERED ([flagID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

