ALTER TABLE [dbo].[float_allocations]
    ADD CONSTRAINT [PK_float_allocations] PRIMARY KEY CLUSTERED ([allocationid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

