ALTER TABLE [dbo].[faqcategories]
    ADD CONSTRAINT [PK_faqcategories] PRIMARY KEY CLUSTERED ([faqcategoryid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

