ALTER TABLE [dbo].[floathistory]
    ADD CONSTRAINT [PK_floathistory] PRIMARY KEY CLUSTERED ([floathistoryid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

