ALTER TABLE [dbo].[flagAssociatedRoles]
    ADD CONSTRAINT [PK_flagAssociatedRoles] PRIMARY KEY CLUSTERED ([flagID] ASC, [roleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

