ALTER TABLE [dbo].[financial_exports]
    ADD CONSTRAINT [PK_financial_exports] PRIMARY KEY CLUSTERED ([financialexportid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

