ALTER TABLE [dbo].[logNames]
    ADD CONSTRAINT [PK_logNames] PRIMARY KEY CLUSTERED ([logID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

