ALTER TABLE [dbo].[location_distances]
    ADD CONSTRAINT [PK_location_distances] PRIMARY KEY CLUSTERED ([distanceid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

