ALTER TABLE [dbo].[mileage_dateranges]
    ADD CONSTRAINT [PK_mileage_dateranges] PRIMARY KEY CLUSTERED ([mileagedateid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

