ALTER TABLE [dbo].[mime_headers]
    ADD CONSTRAINT [PK_MIME Headers] PRIMARY KEY CLUSTERED ([mimeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

