ALTER TABLE [dbo].[mileage_thresholds]
    ADD CONSTRAINT [PK_mileage_thresholds] PRIMARY KEY CLUSTERED ([mileagethresholdid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

