ALTER TABLE [dbo].[mileage_categories]
    ADD CONSTRAINT [PK_mileage_categories] PRIMARY KEY CLUSTERED ([mileageid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

