ALTER TABLE [dbo].[notes]
    ADD CONSTRAINT [PK_notes] PRIMARY KEY CLUSTERED ([noteid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

