ALTER TABLE [dbo].[custom_New_Entities]
    ADD CONSTRAINT [PK_New_Entities] PRIMARY KEY CLUSTERED ([att12] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

