ALTER TABLE [dbo].[odometer_readings]
    ADD CONSTRAINT [PK_odometer_readings] PRIMARY KEY CLUSTERED ([odometerid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

