ALTER TABLE [dbo].[pool_car_users]
    ADD CONSTRAINT [PK_pool_car_users_1] PRIMARY KEY CLUSTERED ([carid] ASC, [employeeid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

