ALTER TABLE [dbo].[product_suppliers]
    ADD CONSTRAINT [PK_Product_Supplier] PRIMARY KEY CLUSTERED ([productSupplierId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

