ALTER TABLE [dbo].[print_views]
    ADD CONSTRAINT [PK_print_views] PRIMARY KEY CLUSTERED ([fieldID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

