ALTER TABLE [dbo].[recharge_associations]
    ADD CONSTRAINT [PK_Recharge_Associations] PRIMARY KEY CLUSTERED ([rechargeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

