ALTER TABLE [dbo].[reportcriteria]
    ADD CONSTRAINT [PK_reportcriteria] PRIMARY KEY CLUSTERED ([criteriaid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

