ALTER TABLE [dbo].[receipts]
    ADD CONSTRAINT [PK_receipts] PRIMARY KEY CLUSTERED ([receiptid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

