ALTER TABLE [dbo].[recharge_servicedates]
    ADD CONSTRAINT [PK_recharge_servicedates] PRIMARY KEY CLUSTERED ([serviceDateId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

