ALTER TABLE [dbo].[savedexpenses_previous]
    ADD CONSTRAINT [PK_savedexpenses] PRIMARY KEY NONCLUSTERED ([expenseid] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

