ALTER TABLE [dbo].[supplierNotes]
    ADD CONSTRAINT [PK_SupplierNotes] PRIMARY KEY CLUSTERED ([noteId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

