ALTER TABLE [dbo].[savedexpensesFlags]
    ADD CONSTRAINT [PK_savedexpensesFlags] PRIMARY KEY CLUSTERED ([expenseid] ASC, [flagType] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

