ALTER TABLE [dbo].[subcats]
    ADD CONSTRAINT [PK_subcats] PRIMARY KEY NONCLUSTERED ([subcatid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

