ALTER TABLE [dbo].[scheduled_reports_log]
    ADD CONSTRAINT [PK_scheduled_reports_log] PRIMARY KEY CLUSTERED ([scheduleid] ASC, [datestamp] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

