ALTER TABLE [dbo].[scheduled_months]
    ADD CONSTRAINT [PK_scheduled_months] PRIMARY KEY CLUSTERED ([scheduleid] ASC, [month] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

