ALTER TABLE [dbo].[scheduled_reports]
    ADD CONSTRAINT [PK_scheduled_reports] PRIMARY KEY CLUSTERED ([scheduleid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

