ALTER TABLE [dbo].[subcat_vat_rates]
    ADD CONSTRAINT [PK_subcat_vat_rates] PRIMARY KEY CLUSTERED ([vatrateid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

