ALTER TABLE [dbo].[template_columns]
    ADD CONSTRAINT [PK_template_columns] PRIMARY KEY CLUSTERED ([templateid] ASC, [order] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

