ALTER TABLE [dbo].[userdefinedSubcats]
    ADD CONSTRAINT [PK_userdefinedSubcats] PRIMARY KEY CLUSTERED ([subcatid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

