ALTER TABLE [dbo].[userdefinedGroupings]
    ADD CONSTRAINT [PK_userdefinedGroupings] PRIMARY KEY CLUSTERED ([userdefinedGroupID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

