ALTER TABLE [dbo].[userdefinedCars]
    ADD CONSTRAINT [PK_userdefinedCars] PRIMARY KEY CLUSTERED ([carid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

