ALTER TABLE [dbo].[userdefined_costcodes]
    ADD CONSTRAINT [PK_userdefined_costcodes] PRIMARY KEY CLUSTERED ([costcodeid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

