ALTER TABLE [dbo].[userdefinedLocations]
    ADD CONSTRAINT [PK_userdefinedLocations] PRIMARY KEY CLUSTERED ([locationid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

