ALTER TABLE [dbo].[version_registry]
    ADD CONSTRAINT [PK_Version_Registry] PRIMARY KEY CLUSTERED ([RegistryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

