ALTER TABLE [dbo].[workflowConditions]
    ADD CONSTRAINT [PK_workflow_conditions] PRIMARY KEY CLUSTERED ([conditionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

