ALTER TABLE [dbo].[workflows]
    ADD CONSTRAINT [PK_workflows] PRIMARY KEY CLUSTERED ([workflowID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

