ALTER TABLE [dbo].[workflow_field_monitors]
    ADD CONSTRAINT [PK_workflow_field_monitors] PRIMARY KEY CLUSTERED ([fieldMonitorID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

