//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsrNhsHubFileTransferService.Code.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class esrNhsHubEntities : DbContext
    {
        public esrNhsHubEntities()
            : base("name=esrNhsHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<transferredFile> transferredFiles { get; set; }
        public DbSet<ftpLocation> ftpLocations { get; set; }
    }
}
