<%@ Page Language="C#" MasterPageFile="~/masters/SMForm.master" AutoEventWireup="true" Inherits="Spend_Management.ViewTask" Title="Untitled Page" Codebehind="ViewTask.aspx.cs" %>

<%@ MasterType VirtualPath="~/masters/SMForm.master" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="contentmenu" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="contentleft" runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="contentmain" runat="Server">
	<asp:ScriptManagerProxy runat="server" ID="ajaxScriptProxy">
        <Scripts>
            <asp:ScriptReference Path="~/shared/javaScript/tasks.js" />
        </Scripts>
	</asp:ScriptManagerProxy>
    <script language="javascript" type="text/javascript">

        var cmbStatusID = '<%=lstStatus.ClientID %>';
        var dtTaskStartID = '<%=dtTaskStart.ClientID %>';
        var dtTaskDueID = '<%=dtTaskDue.ClientID %>';
        var dtTaskEndID = '<%=dtTaskEnd.ClientID %>';
        var statusID = 0;
    </script>
	<div class="formpanel formpanel_padding">
		<asp:HiddenField runat="server" ID="returnURL" />
		<asp:HiddenField runat="server" ID="hiddenEditId" />
		<div class="sectiontitle">
			Current Task&nbsp;<asp:Label runat="server" ID="lblTaskTitle"></asp:Label></div>
		<div class="twocolumn">
			<asp:UpdatePanel runat="server" ID="statusUpdatePanel">
				<ContentTemplate>
					<asp:Label runat="server" ID="lblRegarding" AssociatedControlID="txtRegarding">Regarding</asp:Label><span class="inputs"><asp:TextBox runat="server" ID="txtRegarding" Enabled="false" CssClass="fillspan" ValidationGroup="tasks"></asp:TextBox></span><span class="inputicon">&nbsp;</span><span class="inputtooltipfield"><asp:HiddenField runat="server" ID="hiddenRegardingId" /><asp:HiddenField runat="server" ID="hiddenRegardingArea" /></span><span class="inputvalidatorfield">&nbsp;</span><asp:Label runat="server" ID="lblTaskStatus" AssociatedControlID="lstStatus">Task Status</asp:Label><span class="inputs"><asp:DropDownList runat="server" ID="lstStatus" TabIndex="1" CssClass="fillspan" onchange="setStatus();" ValidationGroup="tasks"></asp:DropDownList></span><span class="inputicon">&nbsp;</span><span class="inputtooltipfield"><img src="/shared/images/icons/16/plain/tooltip.png" alt="" id="imgtooltip467" style="margin-top:-15px;" onclick="SEL.Tooltip.Show('7bd521a9-5d5e-4b8a-bd21-428a8098b881', 'sm', this);" class="tooltipicon" /></span><span class="inputvalidatorfield"></span>
				</ContentTemplate>
			</asp:UpdatePanel>
		</div>
		<div class="onecolumnsmall">
			<asp:Label runat="server" ID="lblTaskOwner" AssociatedControlID="lstOwner" CssClass="mandatory">Task Owner*</asp:Label><span class="inputs"><asp:DropDownList runat="server" ID="lstOwner" TabIndex="2" CssClass="fillspan" ValidationGroup="tasks"></asp:DropDownList></span><span class="inputicon">&nbsp;</span><span class="inputtooltipfield">&nbsp;</span><span class="inputvalidatorfield"><asp:RequiredFieldValidator runat="server" ValidationGroup="tasks" ID="reqOwner" ControlToValidate="lstOwner" ErrorMessage="Selection of an owning party is mandatory" Display="Dynamic" InitialValue="0">*</asp:RequiredFieldValidator></span>
		</div>
		<div class="twocolumn">
			<asp:Label runat="server" ID="lblSubject" AssociatedControlID="txtSubject" CssClass="mandatory">Subject*</asp:Label><span class="inputs"><asp:TextBox runat="server" ID="txtSubject" TabIndex="3" CssClass="fillspan" ValidationGroup="tasks"></asp:TextBox></span><span class="inputicon">&nbsp;</span><span class="inputtooltipfield"><img src="/shared/images/icons/16/plain/tooltip.png" alt="" id="imgtooltip468" onclick="SEL.Tooltip.Show('33a80742-4407-4e61-b0b8-21e1a5a09451', 'sm', this);" class="tooltipicon" /></span><span class="inputvalidatorfield"><asp:RequiredFieldValidator ID="reqSubject" runat="server" ControlToValidate="txtSubject" ErrorMessage="The subject field is mandatory" ValidationGroup="tasks" Display="Dynamic">*</asp:RequiredFieldValidator></span>
		</div>
		<div id="lstTasks" runat="server">
		    <div class="onecolumnsmall">
			    <asp:Label runat="server" ID="lblTaskType" AssociatedControlID="lstTaskType">Task Type</asp:Label><span class="inputs"><asp:DropDownList runat="server" ID="lstTaskType" TabIndex="4" CssClass="fillspan" ValidationGroup="tasks"></asp:DropDownList></span><span class="inputicon">&nbsp;</span><span class="inputtooltipfield"><img src="/shared/images/icons/16/plain/tooltip.png" alt="" id="imgtooltip469" onclick="SEL.Tooltip.Show('272ce1dd-279f-4243-a996-acf950ddd587', 'sm', this);" class="tooltipicon" /></span><span class="inputvalidatorfield">&nbsp;</span>
		    </div>
        </div>
		<div class="onecolumn">
			<asp:Label runat="server" ID="lblDescription" AssociatedControlID="txtDescription"><p class="labeldescription">Description</p></asp:Label><span class="inputs"><asp:TextBox runat="server" ID="txtDescription" Rows="6" TextMode="MultiLine" TabIndex="5" ValidationGroup="tasks"></asp:TextBox></span><span class="inputicon">&nbsp;</span><span class="inputtooltipfield"><img src="/shared/images/icons/16/plain/tooltip.png" alt="" id="imgtooltip470" onclick="SEL.Tooltip.Show('f82abdbc-d2dc-472f-abe0-07821e7c3069', 'sm', this);" class="tooltipicon" /></span><span class="inputvalidatorfield">&nbsp;</span>
		</div>
		<div class="twocolumn">
			<asp:Label runat="server" ID="lblStartDate" AssociatedControlID="dtTaskStart">Start Date</asp:Label><span class="inputs"><asp:TextBox runat="server" ID="dtTaskStart" TabIndex="6" CssClass="fillspan" ValidationGroup="tasks"></asp:TextBox></span><span class="inputicon"><asp:ImageButton runat="server" ID="popupTaskStart" ImageUrl="~/shared/images/icons/cal.gif" CausesValidation="false" /><cc1:MaskedEditExtender ID="meexTaskStart" runat="server" Mask="99/99/9999" MaskType="Date" TargetControlID="dtTaskStart" UserDateFormat="DayMonthYear"></cc1:MaskedEditExtender></span><span class="inputtooltipfield"><img src="/shared/images/icons/16/Plain/tooltip.png" alt=""
             id="imgtooltip471" onclick="SEL.Tooltip.Show('354ee83f-90c0-4b8e-bfad-6445420c84a0', 'sm', this);" class="tooltipicon" /></span><span class="inputvalidatorfield"><asp:CompareValidator ID="cvMinStartDate" runat="server" Display="Dynamic" ControlToValidate="dtTaskStart" ValidationGroup="tasks" ErrorMessage="Please enter a start date after 01/01/1900" Type="Date" ValueToCompare="01/01/1900" Operator="GreaterThan">*</asp:CompareValidator><asp:CompareValidator ID="cvMaxStartDate" runat="server" Display="Dynamic" ControlToValidate="dtTaskStart" ValidationGroup="tasks" ErrorMessage="Please enter a start date before 31/12/3000" Type="Date" ValueToCompare="31/12/3000" Operator="LessThan">*</asp:CompareValidator><asp:CompareValidator ID="cmpTaskStart" runat="server" ControlToValidate="dtTaskStart" ErrorMessage="Invalid date format entered" Operator="DataTypeCheck" Type="Date" ValidationGroup="tasks" Display="Dynamic">*</asp:CompareValidator><asp:RequiredFieldValidator ID="reqTaskStart" runat="server" ControlToValidate="dtTaskStart" Enabled="False" ErrorMessage="Task Start Date is mandatory" ValidationGroup="tasks" Display="Dynamic">*</asp:RequiredFieldValidator><asp:CustomValidator ID="custTaskStart" runat="server" ControlToValidate="dtTaskStart" Text="*" ErrorMessage="Task Start Date must be less than or equal to Task Due Date or less than or equal to Task End Date" ClientValidationFunction="validateTaskStartDate" ValidationGroup="tasks" Display="Dynamic"></asp:CustomValidator><cc1:CalendarExtender ID="calexTaskStart" runat="server" Format="dd/MM/yyyy" PopupButtonID="popupTaskStart" TargetControlID="dtTaskStart"></cc1:CalendarExtender></span><asp:Label runat="server" ID="lblTaskDue" AssociatedControlID="dtTaskDue">Due Date</asp:Label><span class="inputs"><asp:TextBox runat="server" ID="dtTaskDue" TabIndex="7" CssClass="fillspan" ValidationGroup="tasks"></asp:TextBox></span><span class="inputicon"><asp:ImageButton runat="server" ID="popupTaskDue" CausesValidation="false" ImageUrl="~/shared/images/icons/cal.gif" /></span><span class="inputtooltipfield"><img src="/shared/images/icons/16/Plain/tooltip.png" alt="" 
            id="imgtooltip472" onclick="SEL.Tooltip.Show('0d1d1a9e-2bfd-4290-9d46-107cd2534747', 'sm', this);" class="tooltipicon" /></span><span class="inputvalidatorfield"><asp:CompareValidator ID="cvMinDueDate" runat="server" Display="Dynamic" ControlToValidate="dtTaskDue" ValidationGroup="tasks" ErrorMessage="Please enter a due date after 01/01/1900" Type="Date" ValueToCompare="01/01/1900" Operator="GreaterThan">*</asp:CompareValidator><asp:CompareValidator ID="cvMaxDueDate" runat="server" Display="Dynamic" ControlToValidate="dtTaskDue" ValidationGroup="tasks" ErrorMessage="Please enter a due date before 31/12/3000" Type="Date" ValueToCompare="31/12/3000" Operator="LessThan">*</asp:CompareValidator><asp:CompareValidator ID="cmpTaskDue" runat="server" ControlToValidate="dtTaskDue" ErrorMessage="Invalid date format entered" Operator="DataTypeCheck" Type="Date" Display="Dynamic" ValidationGroup="tasks">*</asp:CompareValidator><asp:RequiredFieldValidator ID="reqTaskDue" runat="server" ControlToValidate="dtTaskDue" Enabled="False" ErrorMessage="Task Due Date is mandatory" ValidationGroup="tasks" Display="Dynamic">*</asp:RequiredFieldValidator><asp:CustomValidator ID="custTaskDue" runat="server" ControlToValidate="dtTaskDue" Text="*" ErrorMessage="Task Due Date must be greater than or equal to Task Start Date or less than or equal to Task End Date" ClientValidationFunction="validateTaskDueDate" ValidationGroup="tasks"></asp:CustomValidator><cc1:CalendarExtender ID="calexTaskDue" runat="server" Format="dd/MM/yyyy" PopupButtonID="popupTaskDue" TargetControlID="dtTaskDue"></cc1:CalendarExtender><cc1:MaskedEditExtender ID="meexTaskDue" runat="server" Mask="99/99/9999" MaskType="Date" TargetControlID="dtTaskDue" UserDateFormat="DayMonthYear"></cc1:MaskedEditExtender></span>
		</div>
		<div class="twocolumn">
			<asp:Label runat="server" ID="lblTaskEnd" AssociatedControlID="dtTaskEnd">End Date</asp:Label><span class="inputs"><asp:TextBox runat="server" ID="dtTaskEnd" TabIndex="8" CssClass="fillspan" ValidationGroup="tasks"></asp:TextBox></span><span class="inputicon"><asp:ImageButton runat="server" ID="popupTaskEnd" CausesValidation="false" ImageUrl="/shared/images/icons/cal.gif" /></span><span class="inputtooltipfield"><img src="/shared/images/icons/16/Plain/tooltip.png" alt="" id="imgtooltip473" onclick="SEL.Tooltip.Show('078a1224-5d6c-447b-9a45-de1f73026df1', 'sm', this);" class="tooltipicon" /></span><span class="inputvalidatorfield"><asp:CompareValidator ID="cvMinEndDate" runat="server" Display="Dynamic" ControlToValidate="dtTaskEnd" ValidationGroup="tasks" ErrorMessage="Please enter an end date after 01/01/1900" Type="Date" ValueToCompare="01/01/1900" Operator="GreaterThan">*</asp:CompareValidator><asp:CompareValidator ID="cvMaxEndDate" runat="server" Display="Dynamic" ControlToValidate="dtTaskEnd" ValidationGroup="tasks" ErrorMessage="Please enter an end date before 31/12/3000" Type="Date" ValueToCompare="31/12/3000" Operator="LessThan">*</asp:CompareValidator><asp:CompareValidator ID="cmpTaskEnd" runat="server" ControlToValidate="dtTaskEnd" ErrorMessage="Invalid date format entered" Operator="DataTypeCheck" Type="Date" ValidationGroup="tasks" Display="Dynamic">*</asp:CompareValidator><asp:RequiredFieldValidator ID="reqTaskEnd" runat="server" ControlToValidate="dtTaskEnd" Enabled="False" ErrorMessage="Task End Date is mandatory" ValidationGroup="tasks" Display="Dynamic">*</asp:RequiredFieldValidator><asp:CustomValidator ID="custTaskEnd" runat="server" ControlToValidate="dtTaskEnd" Text="*" ErrorMessage="Task End Date must be greater than or equal to Task Due Date or less than or equal to Task Start Date" ClientValidationFunction="validateTaskEndDate" ValidationGroup="tasks"></asp:CustomValidator><cc1:CalendarExtender ID="calexTaskEnd" runat="server" Format="dd/MM/yyyy" PopupButtonID="popupTaskEnd" TargetControlID="dtTaskEnd"></cc1:CalendarExtender><cc1:MaskedEditExtender ID="meexTaskEnd" runat="server" Mask="99/99/9999" MaskType="Date" TargetControlID="dtTaskEnd" UserDateFormat="DayMonthYear"></cc1:MaskedEditExtender></span><span id="attSpan"><asp:Label runat="server" ID="lblAttachments" AssociatedControlID="litAttachments">0 Attachments</asp:Label><span class="inputs"><asp:Literal ID="litAttachments" runat="server"></asp:Literal></span><span class="inputicon"><asp:ImageButton runat="server" ID="cmdAttachments" ImageUrl="../images/icons/16/plain/paperclip.png" OnClick="cmdAttachments_Click" TabIndex="11" /></span><span class="inputtooltipfield">&nbsp;</span><span class="inputvalidatorfield">&nbsp;</span></span>
		</div>
        <div id="divCreator" class="onecolumnsmall" runat="server" style="display:none;">
			<asp:Label runat="server" ID="lblTaskCreator" AssociatedControlID="txtCreator">Task Creator</asp:Label><span class="inputs"><asp:TextBox runat="server" ID="txtCreator" CssClass="fillspan" Enabled="false"></asp:TextBox></span><span class="inputicon">&nbsp;</span><span class="inputtooltipfield">&nbsp;</span><span class="inputvalidatorfield">&nbsp;</span>
		</div>
	</div>
    	<div class="formpanel formpanel_padding">
	<div class="formbuttons">
		<asp:ImageButton runat="server" ID="cmdUpdate" AlternateText="Update" ImageUrl="~/shared/images/buttons/btn_save.png" OnClientClick="return checkStatus();" OnClick="cmdUpdate_Click" />&nbsp;&nbsp;<asp:ImageButton runat="server" ID="cmdCancel" AlternateText="Cancel" CausesValidation="false" ImageUrl="~/shared/images/buttons/btn_close.png" OnClick="cmdCancel_Click" /><asp:HiddenField runat="server" ID="hiddenTSReturnURL" />
	</div>
    </div>
</asp:Content>
