-- <Migration ID="5217a65e-6805-4a9c-b5f0-b19c17806b08" />
GO
SET IDENTITY_INSERT [dbo].[ExpenseValidationCriteria] ON 
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (1, NULL, NULL, N'Invoice number is present', NULL, 1, 0, N'Matching invoice number found on receipt', N'Invoice number found, but does not match the expense', N'Invoice number identified, but was unreadable', N'No invoice number present on the receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (2, NULL, NULL, N'Invoice total is present', NULL, 1, 0, N'Matching invoice total found on receipt', N'Invoice total found, but does not match the expense', N'Invoice total identified, but was unreadable', N'No invoice total present on the receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (3, NULL, NULL, N'Supplier name and address present', NULL, 1, 0, N'Supplier name and address found and matched', N'Supplier name and address found, but does not match expense', N'Supplier name and address identified, but was unreadable', N'No supplier name and address present on the receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (4, NULL, NULL, N'Date is present', NULL, 1, 0, N'Matching date found on receipt', N'Date found, but does not match expense', N'Date identified, but was unreadable', N'No date present on the receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (5, NULL, NULL, N'Description of goods or services is present', NULL, 1, 0, N'Description of goods or services match your expense item', N'Description of goods or services do not match your expense item', N'Description of goods or services was identified, but is unreadable', N'Description of goods or services was not found on the receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (6, NULL, NULL, N'Recipient business name present', NULL, 1, 0, N'Recipient name found that matches your company''s name', N'Recipient name found, but does not match your company', N'Recipient name identified, but was unreadable', N'No recipient name present on the receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (7, NULL, NULL, N'At least one of the images appears to be an original document', NULL, 1, 1, N'At least one of the receipt images appears to be an original document', N'None of the receipt images appear to be an original document', N'None of the receipt images appear to be an original document', N'None of the receipt images appear to be an original document')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (8, NULL, NULL, N'Images contain a receipt that applies to a single expense', NULL, 1, 1, N'Receipt images contain a receipt that applies to a single expense', N'Receipt images contain multiple receipts', N'Receipt images contain multiple receipts', N'Receipt images contain multiple receipts')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (9, NULL, NULL, N'Receipt is actually a receipt', NULL, 1, 1, N'Attachment is a receipt', N'Attachment is not actually a receipt', N'Attachment is not actually a receipt', N'Attachment is not actually a receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (10, NULL, NULL, N'VAT number is present', NULL, 1, 0, N'VAT number found and matched', N'VAT number found, but does not match expense', N'VAT number identified, but was unreadable', N'No VAT number present on the receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (11, NULL, NULL, N'Amount excluding VAT is present', NULL, 1, 0, N'Amount excluding VAT found and matched', N'Amount excluding VAT found, but does not match expense', N'Amount excluding VAT identified, but was unreadable', N'No amount excluding VAT present on the receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (12, NULL, NULL, N'VAT amount is present', NULL, 1, 0, N'VAT amount found and matched', N'VAT amount found, but does not match expense', N'VAT amount identified, but was unreadable', N'No VAT amount present on the receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (13, NULL, NULL, N'VAT rate is present', NULL, 1, 0, N'VAT rate found and matched', N'VAT rate found, but does not match expense', N'VAT rate identified, but was unreadable', N'No VAT rate present on the receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (14, NULL, NULL, N'Item is composite VAT rate', NULL, 1, 0, N'A single item has more than one VAT rate', N'A single item has more than one VAT rate', N'Receipt item does not contain multiple VAT rates', N'Receipt item does not contain multiple VAT rates')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (15, NULL, NULL, N'Amount including VAT is present', NULL, 1, 0, N'Amount including VAT found and matched', N'Amount including VAT found, but does not match expense', N'Amount including VAT identified, but was unreadable', N'No amount including VAT present on the receipt')
GO
INSERT [dbo].[ExpenseValidationCriteria] ([CriterionId], [AccountId], [FieldId], [Requirements], [SubcatId], [Enabled], [FraudulentIfFailsVAT], [FriendlyMessageFoundAndMatched], [FriendlyMessageFoundNotMatched], [FriendlyMessageFoundNotReadable], [FriendlyMessageNotFound]) VALUES (16, NULL, NULL, N'Images contain a UK VAT receipt', NULL, 1, 0, N'Receipt is a UK VAT receipt', N'Receipt is not a UK VAT receipt', N'Receipt is not a UK VAT receipt', N'Receipt is not a UK VAT receipt')
GO
SET IDENTITY_INSERT [dbo].[ExpenseValidationCriteria] OFF
GO
