CREATE VIEW [dbo].[ProductLicencesView]
	AS SELECT [licenceID]
      ,[productID]
      ,[licenceKey]
      ,[licenceType]
      ,[location]
      ,[expiry]
      ,[renewalType]
	  ,CASE WHEN notifyType = 0 THEN NotifyId END AS EmployeeId
	  ,CASE WHEN notifyType = 1 THEN NotifyId END AS TeamId
      ,[notifyDays]
      ,[softCopy]
      ,[hardCopy]
      ,[unlimited]
      ,[numberCopiesHeld]
      ,[dateInstalled]
      ,[installedVersion]
      ,[availableVersion]
      ,[userCode]
      ,[comments]
      ,[licenceTypeId]
      ,[createdOn]
      ,[createdBy]
      ,[modifiedOn]
      ,[modifiedBy]
  FROM [dbo].[productLicences]
