CREATE TABLE [dbo].[fields_base] (
    [fieldid]                UNIQUEIDENTIFIER NOT NULL,
    [field]                  NVARCHAR (100)   COLLATE Latin1_General_CI_AS NOT NULL,
    [fieldtype]              NVARCHAR (2)     COLLATE Latin1_General_CI_AS NOT NULL,
    [description]            NVARCHAR (1000)  COLLATE Latin1_General_CI_AS NULL,
    [comment]                NVARCHAR (4000)  COLLATE Latin1_General_CI_AS NULL,
    [normalview]             BIT              NOT NULL,
    [idfield]                BIT              NOT NULL,
    [viewgroupid_old]        INT              NULL,
    [genlist]                BIT              NOT NULL,
    [width]                  INT              NOT NULL,
    [cantotal]               BIT              NOT NULL,
    [printout]               BIT              NOT NULL,
    [valuelist]              BIT              NOT NULL,
    [allowimport]            BIT              NOT NULL,
    [mandatory]              BIT              NOT NULL,
    [amendedon]              DATETIME         NOT NULL,
    [lookuptable]            UNIQUEIDENTIFIER NULL,
    [lookupfield]            UNIQUEIDENTIFIER NULL,
    [useforlookup]           BIT              NOT NULL,
    [workflowUpdate]         BIT              NOT NULL,
    [workflowSearch]         BIT              NOT NULL,
    [length]                 INT              NOT NULL,
    [tableid]                UNIQUEIDENTIFIER NOT NULL,
    [viewgroupid]            UNIQUEIDENTIFIER NULL,
    [relabel]                BIT              NOT NULL,
    [relabel_param]          NVARCHAR (150)   COLLATE Latin1_General_CI_AS NULL,
    [fieldid_old]            INT              NULL,
    [allowDuplicateChecking] BIT              NOT NULL,
    [classPropertyName]      NVARCHAR (500)   NULL
);

