CREATE TABLE [dbo].[registeredusers] (
    [accountid]               INT            IDENTITY (236, 1) NOT NULL,
    [companyname]             NVARCHAR (50)  COLLATE Latin1_General_CI_AS NOT NULL,
    [companyid]               NVARCHAR (50)  COLLATE Latin1_General_CI_AS NOT NULL,
    [contact]                 NVARCHAR (50)  COLLATE Latin1_General_CI_AS NOT NULL,
    [nousers]                 INT            NOT NULL,
    [expiry]                  DATETIME       NOT NULL,
    [accounttype]             TINYINT        NOT NULL,
    [dbserver]                INT            NULL,
    [dbname]                  NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
    [dbusername]              NVARCHAR (100) NOT NULL,
    [dbpassword]              NVARCHAR (200) COLLATE Latin1_General_CI_AS NULL,
    [resellerid]              INT            NULL,
    [archived]                BIT            NOT NULL,
    [autologEnabled]          BIT            NOT NULL,
    [quickEntryFormsEnabled]  BIT            NOT NULL,
    [employeeSearchEnabled]   BIT            NOT NULL,
    [hotelReviewsEnabled]     BIT            NOT NULL,
    [advancesEnabled]         BIT            NOT NULL,
    [postcodeAnyWhereEnabled] BIT            NOT NULL,
    [corporateCardsEnabled]   BIT            NOT NULL,
    [expensesConnectLicenses] INT            NULL,
    [reportDatabaseID]        INT            NULL,
    [hostnameID]              INT            NULL,
    [isNHSCustomer]           BIT            NOT NULL,
    [contactHelpDeskAllowed]  BIT            NOT NULL,
    [postcodeAnywhereKey]     NVARCHAR (200) COLLATE Latin1_General_CI_AS NULL,
    [licencedUsers]           NVARCHAR (150) NULL
);

