CREATE TABLE [dbo].[addresses] (
	[AddressID]					INT IDENTITY(1,1)	NOT NULL,
	[Postcode]					NVARCHAR(32)		NULL,
	[AddressName]				NVARCHAR(250)		NULL,
	[Line1]						NVARCHAR(256)		NULL,
	[Line2]						NVARCHAR(256)		NULL,
	[Line3]						NVARCHAR(256)		NULL,
	[City]						NVARCHAR(256)		NULL,
	[County]					NVARCHAR(256)		NULL,
	[Country]					INT					NULL,
	[Archived]					BIT					NOT NULL,
	[CreationMethod]			INT					NULL,
	[LookupDate]				DATETIME			NULL,
	[SubAccountID]				INT					NULL,
	[GlobalIdentifier]			NVARCHAR(50)		NULL,
	[ESRLocationID]				BIGINT				NULL,
	[ESRAddressID]				BIGINT				NULL,
	[Longitude]					NVARCHAR(20)		NULL,
	[Latitude]					NVARCHAR(20)		NULL,
	[AccountWideFavourite]		BIT					NOT NULL CONSTRAINT [DF_addresses_accountWideFavourite] DEFAULT ((0)),
	[CreatedOn]					DATETIME			NULL,
	[CreatedBy]					INT					NULL,
	[ModifiedOn]				DATETIME			NULL,
	[ModifiedBy]				INT					NULL,
	[AddressNameLookup]			NVARCHAR(250)		NOT NULL,
	[Line1Lookup]				NVARCHAR(256)		NOT NULL,
	[Line2Lookup]				NVARCHAR(256)		NOT NULL,
	[CityLookup]				NVARCHAR(256)		NOT NULL,
	[PostcodeLookup]			NVARCHAR(256)		NOT NULL,
	[Udprn]						INT					NOT NULL,
	[Obsolete]					BIT					NOT NULL CONSTRAINT [DF_addresses_obsolete] DEFAULT ((0)),
	CONSTRAINT [PK_Addresses] PRIMARY KEY CLUSTERED ([AddressID] ASC)
);