CREATE TABLE [dbo].[cars] (
    [carid]                  INT           IDENTITY (1, 1) NOT NULL,
    [employeeid]             INT           NULL,
    [startdate]              DATETIME      NULL,
    [enddate]                DATETIME      NULL,
    [make]                   NVARCHAR (50) NOT NULL,
    [model]                  NVARCHAR (50) NOT NULL,
    [registration]           NVARCHAR (50) NOT NULL,
    [mileageid]              INT           NULL,
    [cartypeid]              TINYINT       NULL,
    [active]                 BIT           NOT NULL,
    [odometer]               BIGINT        NULL,
    [fuelcard]               BIT           NOT NULL,
    [endodometer]            INT           NULL,
    [taxexpiry]              DATETIME      NULL,
    [taxlastchecked]         DATETIME      NULL,
    [taxcheckedby]           INT           NULL,
    [mottestnumber]          NVARCHAR (50) NULL,
    [motlastchecked]         DATETIME      NULL,
    [motcheckedby]           INT           NULL,
    [motexpiry]              DATETIME      NULL,
    [insurancenumber]        NVARCHAR (50) NULL,
    [insuranceexpiry]        DATETIME      NULL,
    [insurancelastchecked]   DATETIME      NULL,
    [insurancecheckedby]     INT           NULL,
    [serviceexpiry]          DATETIME      NULL,
    [servicelastchecked]     DATETIME      NULL,
    [servicecheckedby]       INT           NULL,
    [CreatedOn]              DATETIME      NULL,
    [CreatedBy]              INT           NULL,
    [ModifiedOn]             DATETIME      NULL,
    [ModifiedBy]             INT           NULL,
    [default_unit]           TINYINT       NOT NULL,
    [enginesize]             DECIMAL(12, 3)           NULL,
    [approved]               BIT           NOT NULL,
    [exemptFromHomeToOffice] BIT           NOT NULL,
    [taxAttachID]            INT           NULL,
    [MOTAttachID]            INT           NULL,
    [insuranceAttachID]      INT           NULL,
    [serviceAttachID]        INT           NULL,
	[ESRVehicleId]			 INT		   NULL, 
    [vehicletypeid] TINYINT NULL
);

