CREATE TABLE [dbo].[contract_details] (
    [contractId]             INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [subAccountId]           INT           NULL,
    [contractNumber]         VARCHAR (25)  NULL,
    [contractDescription]    VARCHAR (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Archived]               NVARCHAR (1)  NULL,
    [supplierId]             INT           NULL,
    [scheduleNumber]         VARCHAR (100) NULL,
    [supplierCode]           NVARCHAR (50) NULL,
    [categoryId]             INT           NULL,
    [contractTypeId]         INT           NULL,
    [termTypeId]             INT           NULL,
    [invoiceFrequencyTypeId] INT           NULL,
    [startDate]              SMALLDATETIME NULL,
    [endDate]                SMALLDATETIME NULL,
    [noticePeriod]           SMALLINT      NULL,
    [contractValue]          FLOAT (53)    NULL,
    [contractCurrency]       INT           NULL,
    [reviewPeriod]           SMALLINT      NULL,
    [reviewComplete]         SMALLDATETIME NULL,
    [Term]                   INT           NULL,
    [cancellationDate]       SMALLDATETIME NULL,
    [reviewDate]             SMALLDATETIME NULL,
    [maintenanceType]        INT           NULL,
    [maintenancePct]         FLOAT (53)    NULL,
    [contractOwner]          INT           NULL,
    [maintenanceInflatorX]   INT           CONSTRAINT [DF_Contract_Details_Maintenance_Inflator X] DEFAULT ((0)) NULL,
    [maintenancePercentX]    FLOAT (53)    CONSTRAINT [DF_Contract_Details_Maintenance_Percent_X] DEFAULT ((0)) NULL,
    [maintenanceInflatorY]   INT           CONSTRAINT [DF_Contract_Details_Maintenance_Inflator Y] DEFAULT ((0)) NULL,
    [maintenancePercentY]    FLOAT (53)    CONSTRAINT [DF_Contract_Details_Maintenance_Percent_Y] DEFAULT ((0)) NULL,
    [totalMaintenanceValue]  FLOAT (53)    CONSTRAINT [DF_Contract_Details_Total_Maintenance_Value] DEFAULT ((0)) NULL,
    [contractStatusId]       INT           NULL,
    [lastChangedBy]          VARCHAR (60)  NULL,
    [lastChangeDate]         DATETIME      NULL,
    [annualContractValue]    FLOAT (53)    CONSTRAINT [DF_Contract_Details_AnnualContractValue] DEFAULT ((0)) NOT NULL,
    [cancellationPenalty]    INT           CONSTRAINT [DF_Contract_Details_CanncellationPenalty] DEFAULT ((0)) NOT NULL,
    [supercedeContract]      VARCHAR (25)  NULL,
    [contractKey]            VARCHAR (30)  NULL,
    [archiveDate]            DATETIME      NULL,
    [forecastTypeId]         INT           CONSTRAINT [DF_Contract_Details_ForecastTypeId] DEFAULT ((0)) NULL,
    [createdOn]              DATETIME      NULL,
    [noticePeriodType]       SMALLINT      CONSTRAINT [DF_Contract_Details_NoticePeriodType] DEFAULT ((0)) NOT NULL,
    [reviewPeriodType]       SMALLINT      CONSTRAINT [DF_Contract_Details_ReviewPeriodType] DEFAULT ((0)) NOT NULL,
    [createdBy]              INT           NULL,
    [modifiedOn]             DATETIME      NULL,
    [modifiedBy]             INT           NULL,
    CONSTRAINT [PK_Contract_Details] PRIMARY KEY CLUSTERED ([contractId] ASC),
    CONSTRAINT [FK_contract_details_accountsSubAccounts] FOREIGN KEY ([subAccountId]) REFERENCES [dbo].[accountsSubAccounts] ([subAccountID]),
    CONSTRAINT [FK_contract_details_codes_contractcategory] FOREIGN KEY ([categoryId]) REFERENCES [dbo].[codes_contractcategory] ([categoryId]),
    CONSTRAINT [FK_contract_details_codes_contractstatus] FOREIGN KEY ([contractStatusId]) REFERENCES [dbo].[codes_contractstatus] ([statusId]),
    CONSTRAINT [FK_contract_details_codes_contracttype] FOREIGN KEY ([contractTypeId]) REFERENCES [dbo].[codes_contracttype] ([contractTypeId]),
    CONSTRAINT [FK_contract_details_codes_invoicefrequencytype] FOREIGN KEY ([invoiceFrequencyTypeId]) REFERENCES [dbo].[codes_invoicefrequencytype] ([invoiceFrequencyTypeId]),
    CONSTRAINT [FK_contract_details_codes_termtype] FOREIGN KEY ([termTypeId]) REFERENCES [dbo].[codes_termtype] ([termTypeId]),
    CONSTRAINT [FK_contract_details_employees] FOREIGN KEY ([contractOwner]) REFERENCES [dbo].[employees] ([employeeid])
);



