CREATE TABLE [dbo].[customEntities] (
    [entityid]                   INT              IDENTITY (1, 1)  NOT NULL,
    [entity_name]                NVARCHAR (250)   NOT NULL,
    [plural_name]                NVARCHAR (250)   NOT NULL,
    [description]                NVARCHAR (4000)  NULL,
    [createdon]                  DATETIME         NOT NULL,
    [createdby]                  INT              NOT NULL,
    [modifiedon]                 DATETIME         NULL,
    [modifiedby]                 INT              NULL,
    [tableid]                    UNIQUEIDENTIFIER NOT NULL,
    [enableAttachments]          BIT              NOT NULL,
    [audienceViewType]           TINYINT		  NOT NULL,
    [allowdocmergeaccess]        BIT              NOT NULL,
    [systemview_derivedentityid] INT              NULL,
    [systemview]                 BIT              NOT NULL,
    [attachmentTableID]          UNIQUEIDENTIFIER NOT NULL,
    [audienceTableID]            UNIQUEIDENTIFIER NOT NULL,
    [systemview_entityid]        INT              NULL,
    [enableCurrencies]           BIT              NOT NULL,
    [defaultCurrencyID]          INT              NULL,
	[masterTableName]			 NVARCHAR (250)	  NOT NULL,
	[CacheExpiry]				 DATETIME		  NULL, 
    [enablePopupWindow]			 BIT              NULL, 
    [defaultPopupView]			 INT              NULL,
	[formSelectionAttribute]	 INT			  NULL,
    [ownerId]					 INT			  NULL, 
    [supportContactId]			 INT			  NULL, 
    [supportQuestion]			 NVARCHAR(250)	  NULL,
	[enableLocking]				 BIT			  NULL, 
    [builtIn] BIT NULL DEFAULT ((0)), 
    [SystemCustomEntityID] UNIQUEIDENTIFIER NULL
);

