CREATE TABLE [dbo].[customEntityAttributes] (
    [attributeid]       INT              IDENTITY (1, 1) NOT NULL,
    [entityid]          INT              NOT NULL,
    [display_name]      NVARCHAR (250)   NOT NULL,
    [description]       NVARCHAR (4000)  NULL,
    [tooltip]           NVARCHAR (4000)  NULL,
    [mandatory]         BIT              NOT NULL,
    [fieldtype]         TINYINT          NOT NULL,
    [createdon]         DATETIME         NOT NULL,
    [createdby]         INT              NOT NULL,
    [modifiedon]        DATETIME         NULL,
    [modifiedby]        INT              NULL,
    [maxlength]         INT              NULL,
    [format]            TINYINT          NULL,
    [defaultvalue]      NVARCHAR (50)    NULL,
    [fieldid]           UNIQUEIDENTIFIER NOT NULL,
    [relatedtable]      UNIQUEIDENTIFIER NULL,
    [precision]         TINYINT          NULL,
    [is_key_field]      BIT              NOT NULL,
    [relationshiptype]  TINYINT          NULL,
    [related_entity]    INT              NULL,
    [formid]            INT              NULL,
    [viewid]            INT              NULL,
    [workflowid]        INT              NULL,
    [is_audit_identity] BIT              NOT NULL,
    [is_unique]         BIT              NOT NULL,
    [allowEdit]         BIT              NOT NULL,
    [allowDelete]       BIT              NOT NULL,
    [advicePanelText]   NVARCHAR (4000)  NULL,
    [aliasTableID]      UNIQUEIDENTIFIER NULL,
	[relationshipDisplayField] UNIQUEIDENTIFIER NULL,
	[maxRows]			INT				NULL,
	[system_attribute]	BIT				NULL,
	[TriggerAttributeId] INT NULL,
	[TriggerJoinViaId]  INT NULL,
	[TriggerDisplayFieldId] UNIQUEIDENTIFIER NULL,
	[CacheExpiry]		DATETIME NULL, 
    [BoolAttribute] BIT NOT NULL DEFAULT 0, 
    [DisplayInMobile] BIT NOT NULL DEFAULT 0,
	[BuiltIn] BIT NOT NULL DEFAULT 0, 
    [SystemCustomEntityAttributeID] UNIQUEIDENTIFIER NULL,
	[Encrypted]		BIT		NOT NULL DEFAULT ((0))
);

