CREATE TABLE [dbo].[esr_assignments] (
    [employeeid]                  INT             NOT NULL,
    [AssignmentID]                BIGINT          NULL,
    [AssignmentNumber]            NVARCHAR (30)   NOT NULL,
    [EarliestAssignmentStartDate] DATETIME        NULL,
    [FinalAssignmentEndDate]      DATETIME        NULL,
    [AssignmentStatus]            NVARCHAR (80)   NULL,
    [PayrollPayType]              NVARCHAR (10)   NULL,
    [PayrollName]                 NVARCHAR (80)   NULL,
    [PayrollPeriodType]           NVARCHAR (30)   NULL,
    [AssignmentAddressLine1]      NVARCHAR (60)   NULL,
    [AssignmentAddressLine2]      NVARCHAR (60)   NULL,
    [AssignmentAddressTown]       NVARCHAR (30)   NULL,
    [AssignmentAddressCounty]     NVARCHAR (70)   NULL,
    [AssignmentAddressPostcode]   NVARCHAR (30)   NULL,
    [AssignmentAddressCountry]    NVARCHAR (60)   NULL,
    [SupervisorFlag]              NVARCHAR (1)    NULL,
    [SupervisorAssignmentNumber]  NVARCHAR (30)   NULL,
    [SupervisorEmployeeNumber]    NVARCHAR (30)   NULL,
    [SupervisorFullName]          NVARCHAR (240)  NULL,
    [AccrualPlan]                 NVARCHAR (80)   NULL,
    [EmployeeCategory]            NVARCHAR (30)   NULL,
    [AssignmentCategory]          NVARCHAR (30)   NULL,
    [PrimaryAssignment]           BIT             CONSTRAINT [DF_esr_assignments_PrimaryAssignment] DEFAULT ((0)) NOT NULL,
    [NormalHours]                 FLOAT (53)      NULL,
    [NormalHoursFrequency]        NVARCHAR (30)   NULL,
    [GradeContractHours]          FLOAT (53)      NULL,
    [NoOfSessions]                FLOAT (53)      NULL,
    [SessionsFrequency]           NVARCHAR (4)    NULL,
    [WorkPatternDetails]          NVARCHAR (80)   NULL,
    [WorkPatternStartDay]         NVARCHAR (30)   NULL,
    [FlexibleWorkingPattern]      NVARCHAR (30)   NULL,
    [AvailabilitySchedule]        NVARCHAR (30)   NULL,
    [Organisation]                NVARCHAR (240)  NULL,
    [LegalEntity]                 NVARCHAR (3)    NULL,
    [PositionName]                NVARCHAR (240)  NULL,
    [JobRole]                     NVARCHAR (60)   NULL,
    [OccupationCode]              NVARCHAR (5)    NULL,
    [AssignmentLocation]          NVARCHAR (60)   NULL,
    [Grade]                       NVARCHAR (240)  NULL,
    [JobName]                     NVARCHAR (120)  NULL,
    [Group]                       NVARCHAR (240)  NULL,
    [TAndAFlag]                   NVARCHAR (240)  NULL,
    [NightWorkerOptOut]           NVARCHAR (3)    NULL,
    [ProjectedHireDate]           DATETIME        NULL,
    [VacancyID]                   INT             NULL,
    [createdon]                   DATETIME        NULL,
    [modifiedon]                  DATETIME        NULL,
    [esrAssignID]                 INT             IDENTITY (1, 1) NOT NULL,
    [Active]                      BIT             CONSTRAINT [DF_esr_assignments_Active] DEFAULT ((1)) NOT NULL,
    [CreatedBy]                   INT             NULL,
    [ModifiedBy]                  INT             NULL,
    [oldProjectedHireDate]        NVARCHAR (8)    NULL,
    [ESRPersonId]                 BIGINT          NULL,
    [AssignmentType]              NVARCHAR (1)    NULL,
    [EffectiveStartDate]          DATETIME        NULL,
    [EffectiveEndDate]            DATETIME        NULL,
    [SystemAssignmentStatus]      NVARCHAR (30)   NULL,
    [EmployeeStatusFlag]          NVARCHAR (1)    NULL,
    [ESRLocationId]               BIGINT          NULL,
    [SupervisorPersonId]          BIGINT          NULL,
    [SupervisorAssignmentId]      BIGINT          NULL,
    [SupervisorEsrAssignId]       INT             NULL,
    [DepartmentManagerAssignmentId]   BIGINT          NULL,
    [PrimaryAssignmentString]     NVARCHAR (30)   NULL,
    [FTE]                         DECIMAL (22, 3) NULL,
    [ESROrganisationId]           BIGINT          NULL,
    [ESRPositionId]               BIGINT          NULL,
    [GradeStep]                   NVARCHAR (10)   NULL,
    [StartDateInGrade]            DATETIME        NULL,
    [AnnualSalaryValue]           MONEY           NULL,
    [ContractEndDate]             DATETIME        NULL,
    [IncrementDate]               DATETIME        NULL,
    [MaximumPartTimeFlag]         NVARCHAR (30)   NULL,
    [AFCFlag]                     NVARCHAR (1)    NULL,
    [ESRLastUpdate]               DATETIME        NULL,
    [LastWorkingDay]              DATETIME        NULL,
    [eKSFSpinalPoint]             NVARCHAR (30)   NULL,
    [ManagerFlag]                 NVARCHAR (30)   NULL,
    [SignOffOwner]                VARCHAR (39)    NULL,
    CONSTRAINT [PK_esr_assignments] PRIMARY KEY CLUSTERED ([esrAssignID] ASC),
    CONSTRAINT [FK_esr_assignments_employees] FOREIGN KEY ([employeeid]) REFERENCES [dbo].[employees] ([employeeid]) ON DELETE CASCADE,
    CONSTRAINT [FK_esr_assignments_esr_assignments_supervisor] FOREIGN KEY ([SupervisorEsrAssignId]) REFERENCES [dbo].[esr_assignments] ([esrAssignID])
);






GO
CREATE NONCLUSTERED INDEX [IX_esr_assignments_SupervisorEsrAssignId]
    ON [dbo].[esr_assignments]([SupervisorEsrAssignId] ASC);

