CREATE TABLE [dbo].[savedexpenses](
	[expenseid] [int] IDENTITY(756969,1) NOT NULL,
	[bmiles] [decimal](18, 2) NULL,
	[pmiles] [decimal](18, 2) NULL,
	[reason] [nvarchar](2500) NULL,
	[receipt] [bit] NOT NULL,
	[net] [money] NOT NULL,
	[vat] [money] NOT NULL,
	[total] [money] NOT NULL,
	[subcatid] [int] NOT NULL,
	[date] [datetime] NOT NULL,
	[staff] [tinyint] NULL,
	[others] [tinyint] NULL,
	[companyid] [int] NULL,
	[returned] [bit] NULL,
	[home] [bit] NULL,
	[refnum] [nvarchar](50) NOT NULL,
	[claimid] [int] NOT NULL,
	[plitres] [int] NULL,
	[blitres] [int] NULL,
	[allowanceamount] [money] NULL,
	[currencyid] [int] NULL,
	[attendees] [nvarchar](1000) NULL,
	[tip] [money] NOT NULL,
	[countryid] [int] NULL,
	[foreignvat] [money] NOT NULL,
	[convertedtotal] [money] NOT NULL,
	[exchangerate] [float] NOT NULL,
	[tempallow] [bit] NOT NULL,
	[reasonid] [int] NULL,
	[normalreceipt] [bit] NOT NULL,
	[receiptattached] [bit] NOT NULL,
	[allowancestartdate] [datetime] NULL,
	[allowanceenddate] [datetime] NULL,
	[carid] [int] NULL,
	[allowancededuct] [money] NULL,
	[allowanceid] [int] NULL,
	[nonights] [tinyint] NULL,
	[quantity] [float] NULL,
	[directors] [tinyint] NULL,
	[amountpayable] [money] NOT NULL,
	[hotelid] [int] NULL,
	[primaryitem] [bit] NOT NULL,
	[norooms] [tinyint] NOT NULL,
	[vatnumber] [nvarchar](50) NULL,
	[personalguests] [tinyint] NULL,
	[remoteworkers] [tinyint] NULL,
	[accountcode] [nvarchar](50) NULL,
	[pencepermile] [money] NULL,
	[basecurrency] [int] NULL,
	[globalexchangerate] [float] NULL,
	[globalbasecurrency] [int] NULL,
	[globaltotal] [money] NULL,
	[itemtype] [tinyint] NOT NULL,
	[CreatedOn] [datetime] NULL,
	[CreatedBy] [int] NULL,
	[ModifiedOn] [datetime] NULL,
	[ModifiedBy] [int] NULL,
	[mileageid] [int] NULL,
	[transactionid] [int] NULL,
	[journey_unit] [tinyint] NULL,
	[esrAssignID] [int] NULL,
	[AssignmentNumber] [nvarchar](50) NULL,
	[CacheExpiry] [datetime] NULL,
	[hometooffice_deduction_method] [tinyint] NULL,
	[addedAsMobileItem] [bit] NOT NULL,
	[addedByDeviceTypeId] [int] NULL,
	[itemCheckerId] [int] NULL, 
    [organisationIdentifier] INT NULL,
	[ValidationProgress] INT NOT NULL default(-20),
	[ValidationCount] INT NOT NULL default(0),
	[itemCheckerTeamId] [int] NULL,
	[Paid]                    BIT             CONSTRAINT [DF_savedexpenses_paid] DEFAULT (NULL) NULL,
	[Edited]                  BIT             CONSTRAINT [DF_savedexpenses_edited] DEFAULT (NULL) NULL,
	[OriginalExpenseId]       INT             CONSTRAINT [DF_savedexpenses_OriginalExpenseId] DEFAULT (NULL) NULL,
	[DatePaid]				  DATETIME        CONSTRAINT [DF_savedexpenses_DatePaid] DEFAULT (NULL) NULL,
	[BankAccountId] INT NULL, 
	[IsItemEscalated] BIT NULL, 
	[ExpediteValidationProgress] INT NOT NULL  DEFAULT(0),
    [WorkAddressId] INT NULL, 
    [MobileMetricDeviceId] INT NULL, 
	CreatedVia AS Case when mobilemetricdeviceId is  Null then 'Web' ELSE 'Mobile' END
    CONSTRAINT [PK_savedexpenses_current] PRIMARY KEY NONCLUSTERED ([expenseid] ASC)
)

