CREATE TABLE [dbo].[subcats] (
    [subcatid]                    INT             IDENTITY (1, 1) NOT NULL,
    [categoryid]                  INT             CONSTRAINT [DF_subcats_categoryid] DEFAULT (0) NOT NULL,
    [description]                 NVARCHAR (4000) NULL,
    [subcat]                      NVARCHAR (50)   NOT NULL,
    [vatapp]                      BIT             CONSTRAINT [DF_subcats_vatapp] DEFAULT (0) NOT NULL,
    [vatamount]                   FLOAT (53)      NULL,
    [mileageapp]                  BIT             CONSTRAINT [DF_subcats_mileageapp] DEFAULT (0) NOT NULL,
    [staffapp]                    BIT             CONSTRAINT [DF_subcats_staffapp] DEFAULT (0) NOT NULL,
    [othersapp]                   BIT             CONSTRAINT [DF_subcats_othersapp] DEFAULT (0) NOT NULL,
    [vatreceipt]                  BIT             CONSTRAINT [DF_subcats_vatreceipt] DEFAULT (0) NOT NULL,
    [vattype]                     INT             CONSTRAINT [DF_subcats_vattype] DEFAULT ((0)) NOT NULL,
    [tipapp]                      BIT             CONSTRAINT [DF_subcats_tipapp] DEFAULT (0) NOT NULL,
    [pmilesapp]                   BIT             CONSTRAINT [DF_subcats_pmilesapp] DEFAULT (0) NOT NULL,
    [bmilesapp]                   BIT             CONSTRAINT [DF_subcats_bmilesapp] DEFAULT (0) NOT NULL,
    [speedoapp]                   BIT             CONSTRAINT [DF_subcats_speedoapp] DEFAULT (0) NOT NULL,
    [blitresapp]                  BIT             CONSTRAINT [DF_subcats_blitresapp] DEFAULT (0) NOT NULL,
    [plitresapp]                  BIT             CONSTRAINT [DF_subcats_plitresapp] DEFAULT (0) NOT NULL,
    [allowance]                   BIT             CONSTRAINT [DF_subcats_allowance] DEFAULT (0) NOT NULL,
    [allowanceamount]             MONEY           NULL,
    [accountcode]                 NVARCHAR (50)   NULL,
    [attendeesapp]                BIT             CONSTRAINT [DF_subcats_attendeesapp] DEFAULT (0) NOT NULL,
    [addasnet]                    BIT             CONSTRAINT [DF__subcats__addasne__4D2A7347] DEFAULT (0) NOT NULL,
    [pdcatid]                     INT             NULL,
    [vatpercent]                  TINYINT         CONSTRAINT [DF__subcats__vatperc__351DDF8C] DEFAULT (100) NULL,
    [eventinhomeapp]              BIT             CONSTRAINT [DF__subcats__eventin__05A3D694] DEFAULT (0) NOT NULL,
    [receiptapp]                  BIT             CONSTRAINT [DF_subcats_receiptapp] DEFAULT (0) NOT NULL,
    [calculation]                 TINYINT         CONSTRAINT [DF_subcats_calculation] DEFAULT (1) NOT NULL,
    [passengersapp]               BIT             CONSTRAINT [DF_subcats_passengersapp] DEFAULT (0) NOT NULL,
    [nopassengersapp]             BIT             CONSTRAINT [DF_subcats_nopassengersapp] DEFAULT (0) NOT NULL,
    [passengernamesapp]           BIT             CONSTRAINT [DF_subcats_passengernamesapp] DEFAULT (0) NOT NULL,
    [comment]                     NVARCHAR (4000) NULL,
    [splitentertainment]          BIT             CONSTRAINT [DF_subcats_splitentertainment] DEFAULT (0) NOT NULL,
    [entertainmentid]             INT             NULL,
    [reimbursable]                BIT             CONSTRAINT [DF_subcats_reimbursable] DEFAULT (1) NOT NULL,
    [nonightsapp]                 BIT             CONSTRAINT [DF_subcats_nonightsapp] DEFAULT (0) NOT NULL,
    [attendeesmand]               BIT             CONSTRAINT [DF_subcats_attendeesmand] DEFAULT (0) NOT NULL,
    [nodirectorsapp]              BIT             CONSTRAINT [DF_subcats_nodirectorsapp] DEFAULT (0) NOT NULL,
    [hotelapp]                    BIT             CONSTRAINT [DF_subcats_hotelapp] DEFAULT (0) NOT NULL,
    [noroomsapp]                  BIT             CONSTRAINT [DF_subcats_noroomsapp] DEFAULT (0) NOT NULL,
    [hotelmand]                   BIT             CONSTRAINT [DF_subcats_hotelmand] DEFAULT (0) NOT NULL,
    [vatnumberapp]                BIT             CONSTRAINT [DF_subcats_vatnumberapp] DEFAULT (0) NOT NULL,
    [vatnumbermand]               BIT             CONSTRAINT [DF_subcats_vatnumbermand] DEFAULT (0) NOT NULL,
    [nopersonalguestsapp]         BIT             CONSTRAINT [DF_subcats_nopersonalguestsapp] DEFAULT (0) NOT NULL,
    [noremoteworkersapp]          BIT             CONSTRAINT [DF_subcats_noremoteworkersapp] DEFAULT (0) NOT NULL,
    [alternateaccountcode]        NVARCHAR (50)   NULL,
    [splitpersonal]               BIT             CONSTRAINT [DF_subcats_splitpersonal] DEFAULT (0) NOT NULL,
    [splitremote]                 BIT             CONSTRAINT [DF_subcats_splitremote] DEFAULT (0) NOT NULL,
    [personalid]                  INT             NULL,
    [remoteid]                    INT             NULL,
    [vatlimitwithout]             DECIMAL (18)    CONSTRAINT [DF_subcats_vatlimitwithout] DEFAULT (0) NOT NULL,
    [vatlimitwith]                DECIMAL (18)    CONSTRAINT [DF_subcats_vatlimitwith] DEFAULT (0) NOT NULL,
    [reasonapp]                   BIT             CONSTRAINT [DF_subcats_reasonapp] DEFAULT (0) NOT NULL,
    [otherdetailsapp]             BIT             CONSTRAINT [DF_subcats_otherdetailsapp] DEFAULT (0) NOT NULL,
    [CreatedOn]                   DATETIME        NULL,
    [CreatedBy]                   INT             NULL,
    [ModifiedOn]                  DATETIME        NULL,
    [ModifiedBy]                  INT             NULL,
    [shortsubcat]                 NVARCHAR (50)   NULL,
    [fromapp]                     BIT             CONSTRAINT [DF_subcats_fromapp] DEFAULT ((0)) NOT NULL,
    [toapp]                       BIT             CONSTRAINT [DF_subcats_toapp] DEFAULT ((0)) NOT NULL,
    [companyapp]                  BIT             CONSTRAINT [DF_subcats_companyapp] DEFAULT ((0)) NOT NULL,
    [enableHomeToLocationMileage] BIT             CONSTRAINT [DF_subcats_enableHomeToLocationMileaeg] DEFAULT ((0)) NOT NULL,
    [homeToLocationType]          TINYINT         NULL,
    [mileageCategory]             INT             NULL,
    [isRelocationMileage]         BIT             CONSTRAINT [DF_subcats_isRelocationMileage] DEFAULT ((0)) NOT NULL,
    [reimbursableSubcatID]        INT             NULL,
    [allowHeavyBulkyMileage]      BIT             CONSTRAINT [DF_subcats_allowHeavyBulkyMileage] DEFAULT ((0)) NOT NULL,
    [homeToOfficeAlwaysZero]      BIT             CONSTRAINT [DF_subcats_homeToOfficeAlwaysZero] DEFAULT ((0)) NOT NULL,
    [StartDate]					  DATE			  NULL, 
    [EndDate]					  DATE			  NULL, 
	[Validate]					  BIT			  CONSTRAINT [DF_subcats_Validate] DEFAULT ((0)) NOT NULL,
	[ValidatorNotes]			  NVARCHAR (500)  NULL,
	[HomeToOfficeFixedMiles]      FLOAT           NULL,
	[PublicTransportRate] INT NULL, 
	[EnableDutyOfCare]             BIT			  CONSTRAINT [DF_EnableDutyOfCare] DEFAULT ((0)) NOT NULL,
	[RequireClassOneBusinessInsurance]            BIT			  CONSTRAINT [DF_RequireClassOneBusinessInsurance] DEFAULT ((0)) NOT NULL,
    [EnforceHomeToOfficeMileageCap] BIT NULL DEFAULT ((0)), 
    [HomeToOfficeMileageCap] FLOAT NULL, 
    CONSTRAINT [PK_subcats] PRIMARY KEY NONCLUSTERED ([subcatid] ASC),
    CONSTRAINT [FK_subcats_categories] FOREIGN KEY ([categoryid]) REFERENCES [dbo].[categories] ([categoryid]),
    CONSTRAINT [FK_subcats_mileage_categories] FOREIGN KEY ([mileageCategory]) REFERENCES [dbo].[mileage_categories] ([mileageid]),
    CONSTRAINT [FK_subcats_pdcats] FOREIGN KEY ([pdcatid]) REFERENCES [dbo].[pdcats] ([pdcatid]),
    CONSTRAINT [IX_subcats] UNIQUE NONCLUSTERED ([subcat] ASC)
);




GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'1=calculate;2=flag', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'subcats', @level2type = N'COLUMN', @level2name = N'homeToLocationType';

