//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsrNhsHubFileTransferService.EsrFileProcessor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EsrFileProcessor.IEsrFileProcessor")]
    public interface IEsrFileProcessor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEsrFileProcessor/ProcessStreamedFile", ReplyAction="http://tempuri.org/IEsrFileProcessor/ProcessStreamedFileResponse")]
        EsrNhsHubFileTransferService.EsrFileProcessor.EsrFileResponseInfo ProcessStreamedFile(EsrNhsHubFileTransferService.EsrFileProcessor.EsrFileRequestInfo request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEsrFileProcessor/ProcessStreamedFile", ReplyAction="http://tempuri.org/IEsrFileProcessor/ProcessStreamedFileResponse")]
        System.Threading.Tasks.Task<EsrNhsHubFileTransferService.EsrFileProcessor.EsrFileResponseInfo> ProcessStreamedFileAsync(EsrNhsHubFileTransferService.EsrFileProcessor.EsrFileRequestInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EsrFileRequestInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EsrFileRequestInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://software-europe.com/API/2013/02")]
        public long FileBytes;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://software-europe.com/API/2013/02")]
        public int FileId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://software-europe.com/API/2013/02")]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream Stream;
        
        public EsrFileRequestInfo() {
        }
        
        public EsrFileRequestInfo(long FileBytes, int FileId, string FileName, System.IO.Stream Stream) {
            this.FileBytes = FileBytes;
            this.FileId = FileId;
            this.FileName = FileName;
            this.Stream = Stream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EsrFileResponseInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EsrFileResponseInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool processed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public EsrFileResponseInfo() {
        }
        
        public EsrFileResponseInfo(bool processed, string message) {
            this.processed = processed;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEsrFileProcessorChannel : EsrNhsHubFileTransferService.EsrFileProcessor.IEsrFileProcessor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EsrFileProcessorClient : System.ServiceModel.ClientBase<EsrNhsHubFileTransferService.EsrFileProcessor.IEsrFileProcessor>, EsrNhsHubFileTransferService.EsrFileProcessor.IEsrFileProcessor {
        
        public EsrFileProcessorClient() {
        }
        
        public EsrFileProcessorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EsrFileProcessorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EsrFileProcessorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EsrFileProcessorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EsrNhsHubFileTransferService.EsrFileProcessor.EsrFileResponseInfo EsrNhsHubFileTransferService.EsrFileProcessor.IEsrFileProcessor.ProcessStreamedFile(EsrNhsHubFileTransferService.EsrFileProcessor.EsrFileRequestInfo request) {
            return base.Channel.ProcessStreamedFile(request);
        }
        
        public bool ProcessStreamedFile(long FileBytes, int FileId, string FileName, System.IO.Stream Stream, out string message) {
            EsrNhsHubFileTransferService.EsrFileProcessor.EsrFileRequestInfo inValue = new EsrNhsHubFileTransferService.EsrFileProcessor.EsrFileRequestInfo();
            inValue.FileBytes = FileBytes;
            inValue.FileId = FileId;
            inValue.FileName = FileName;
            inValue.Stream = Stream;
            EsrNhsHubFileTransferService.EsrFileProcessor.EsrFileResponseInfo retVal = ((EsrNhsHubFileTransferService.EsrFileProcessor.IEsrFileProcessor)(this)).ProcessStreamedFile(inValue);
            message = retVal.message;
            return retVal.processed;
        }
        
        public System.Threading.Tasks.Task<EsrNhsHubFileTransferService.EsrFileProcessor.EsrFileResponseInfo> ProcessStreamedFileAsync(EsrNhsHubFileTransferService.EsrFileProcessor.EsrFileRequestInfo request) {
            return base.Channel.ProcessStreamedFileAsync(request);
        }
    }
}
