CREATE TABLE [dbo].[card_transactions_vcf4] (
    [transactionid]                            INT            NOT NULL,
    [LoadTransactionCode]                      INT            NULL,
    [PostingDate]                              DATETIME       NULL,
    [SequenceNumber]                           NVARCHAR (10)  NULL,
    [Period]                                   INT            NULL,
    [AcquiringBin]                             INT            NULL,
    [CardAcceptorID]                           NVARCHAR (26)  NULL,
    [SupplierName]                             NVARCHAR (26)  NULL,
    [SupplierCity]                             NVARCHAR (14)  NULL,
    [SupplierStateProvinceCode]                NVARCHAR (4)   NULL,
    [SupplierPostalCode]                       NVARCHAR (14)  NULL,
    [MerchantCategoryCode]                     INT            NULL,
    [TransactionTypeCode]                      NVARCHAR (2)   NULL,
    [BillingCurrencyCode]                      INT            NULL,
    [TaxAmount]                                MONEY          NULL,
    [DisputeAmount]                            NVARCHAR (16)  NULL,
    [DisputeReasonCode]                        INT            NULL,
    [DisputeDate]                              DATETIME       NULL,
    [CommodityCode]                            NVARCHAR (4)   NULL,
    [SupplierVATNumber]                        NVARCHAR (20)  NULL,
    [SupplierOrderNumber]                      NVARCHAR (25)  NULL,
    [CustomerVATNumber]                        NVARCHAR (14)  NULL,
    [VATAmount]                                MONEY          NULL,
    [Tax2Amount]                               MONEY          NULL,
    [PurchaseIdentificationFormat]             NVARCHAR (2)   NULL,
    [CustomerCodeCRI]                          NVARCHAR (50)  NULL,
    [PurchaseIdentification]                   NVARCHAR (76)  NULL,
    [TransactionTime]                          NVARCHAR (4)   NULL,
    [TaxAmountIncludedCode]                    INT            NULL,
    [Tax2AmountIncludedCode]                   INT            NULL,
    [OrderTypeCode]                            INT            NULL,
    [MessageIdentifier]                        NVARCHAR (16)  NULL,
    [ProcessorAddendumKey]                     NVARCHAR (52)  NULL,
    [MerchantProfileServiceIdentifier(MPS-ID)] NVARCHAR (12)  NULL,
    [UsageCode]                                INT            NULL,
    [EnrichedTransactionFlag]                  NVARCHAR (2)   NULL,
    [BillingAccountNumber]                     NVARCHAR (19)  NULL,
    [DDANumber]                                NVARCHAR (15)  NULL,
    [DDASavingsNumber]                         NVARCHAR (15)  NULL,
    [DisputeStatusCode]                        NVARCHAR (2)   NULL,
    [MatchedIndicator]                         INT            NULL,
    [RoutingNumber]                            NVARCHAR (10)  NULL,
    [AuthorizationNumber]                      NVARCHAR (6)   NULL,
    [CardholderTransactionApproval]            NVARCHAR (2)   NULL,
    [ExtractID]                                NVARCHAR (15)  NULL,
    [MemoPostFlag]                             INT            NULL,
    [StatementDate]                            DATETIME       NULL,
    [UserData1]                                NVARCHAR (20)  NULL,
    [UserData1Description]                     NVARCHAR (20)  NULL,
    [UserData2]                                NVARCHAR (20)  NULL,
    [UserData2Description]                     NVARCHAR (20)  NULL,
    [UserData3]                                NVARCHAR (20)  NULL,
    [UserData3Description]                     NVARCHAR (20)  NULL,
    [UserData4]                                NVARCHAR (20)  NULL,
    [UserData4Description]                     NVARCHAR (20)  NULL,
    [UserData5]                                NVARCHAR (20)  NULL,
    [UserData5Description]                     NVARCHAR (20)  NULL,
    [VisaCommerceBatchID]                      NVARCHAR (20)  NULL,
    [VisaCommercePaymentInstructionDate]       DATETIME       NULL,
    [LineItemMatchedIndicator]                 INT            NULL,
    [IssuerDefinedUsageCode]                   NVARCHAR (2)   NULL,
    [Source]                                   NVARCHAR (10)  NULL,
    [OptionalField1]                           NVARCHAR (256) NULL,
    [OptionalField2]                           NVARCHAR (256) NULL,
    [OptionalField3]                           NVARCHAR (256) NULL,
    [OptionalField4]                           NVARCHAR (256) NULL,
    [ReservedField1]                           NVARCHAR (30)  NULL,
    [ReservedField2]                           NVARCHAR (30)  NULL,
    [ReservedField3]                           NVARCHAR (30)  NULL,
    [ReservedField4]                           NVARCHAR (30)  NULL
);

