CREATE TABLE [dbo].[card_transactions_rbs_purchase] (
    [transactionid]                 INT           NOT NULL,
    [cycle_date]                    DATETIME      NULL,
    [trans_postdate]                DATETIME      NULL,
    [trans_type]                    NVARCHAR (50) NULL,
    [bank_ref]                      NVARCHAR (23) NULL,
    [mcc]                           NVARCHAR (4)  NULL,
    [exception_indicator]           NVARCHAR (9)  NULL,
    [sequence_number]               NVARCHAR (3)  NULL,
    [merchant_town]                 NVARCHAR (13) NULL,
    [local_tax]                     MONEY         NULL,
    [tax_included]                  BIT           NULL,
    [national_tax]                  MONEY         NULL,
    [national_tax_included]         BIT           NULL,
    [merchant_vat_registration]     NVARCHAR (20) NULL,
    [customer_vat_registration]     NVARCHAR (20) NULL,
    [merchant_order_number]         NVARCHAR (25) NULL,
    [commodity_code]                NVARCHAR (4)  NULL,
    [other_tax]                     MONEY         NULL,
    [messageid]                     NVARCHAR (15) NULL,
    [creation_date]                 DATETIME      NULL,
    [vat_evidence_report_type]      NVARCHAR (2)  NULL,
    [merchant_currency_description] NVARCHAR (40) NULL,
    [mcg]                           NVARCHAR (50) NULL,
    [merchant_country_description]  NVARCHAR (75) NULL,
    [reason_code]                   NVARCHAR (2)  NULL,
    [reason_description]            NVARCHAR (40) NULL
);

