CREATE TABLE [dbo].[contract_details] (
    [contractId]             INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [subAccountId]           INT           NULL,
    [contractNumber]         VARCHAR (25)  NULL,
    [contractDescription]    VARCHAR (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Archived]               NVARCHAR (1)  NULL,
    [supplierId]             INT           NULL,
    [scheduleNumber]         VARCHAR (100) NULL,
    [supplierCode]           NVARCHAR (50) NULL,
    [categoryId]             INT           NULL,
    [contractTypeId]         INT           NULL,
    [termTypeId]             INT           NULL,
    [invoiceFrequencyTypeId] INT           NULL,
    [startDate]              SMALLDATETIME NULL,
    [endDate]                SMALLDATETIME NULL,
    [noticePeriod]           SMALLINT      NULL,
    [contractValue]          FLOAT         NULL,
    [contractCurrency]       INT           NULL,
    [reviewPeriod]           SMALLINT      NULL,
    [reviewComplete]         SMALLDATETIME NULL,
    [Term]                   INT           NULL,
    [cancellationDate]       SMALLDATETIME NULL,
    [reviewDate]             SMALLDATETIME NULL,
    [maintenanceType]        INT           NULL,
    [maintenancePct]         FLOAT         NULL,
    [contractOwner]          INT           NULL,
    [maintenanceInflatorX]   INT           NULL,
    [maintenancePercentX]    FLOAT         NULL,
    [maintenanceInflatorY]   INT           NULL,
    [maintenancePercentY]    FLOAT         NULL,
    [totalMaintenanceValue]  FLOAT         NULL,
    [contractStatusId]       INT           NULL,
    [lastChangedBy]          VARCHAR (60)  NULL,
    [lastChangeDate]         DATETIME      NULL,
    [annualContractValue]    FLOAT         NOT NULL,
    [cancellationPenalty]    INT           NOT NULL,
    [supercedeContract]      VARCHAR (25)  NULL,
    [contractKey]            VARCHAR (30)  NULL,
    [archiveDate]            DATETIME      NULL,
    [forecastTypeId]         INT           NULL,
    [createdOn]              DATETIME      NULL,
    [noticePeriodType]       SMALLINT      NOT NULL,
    [reviewPeriodType]       SMALLINT      NOT NULL,
    [createdBy]              INT           NULL,
    [modifiedOn]             DATETIME      NULL,
    [modifiedBy]             INT           NULL
);

