CREATE TABLE [dbo].[custom_fields] (
    [fieldid]         UNIQUEIDENTIFIER NOT NULL,
    [field]           NVARCHAR (500)   NOT NULL,
    [fieldtype]       NVARCHAR (2)     NOT NULL,
    [description]     NVARCHAR (1000)  NULL,
    [comment]         NVARCHAR (4000)  NULL,
    [normalview]      BIT              NOT NULL,
    [idfield]         BIT              NOT NULL,
    [viewgroupid_old] INT              NULL,
    [genlist]         BIT              NOT NULL,
    [width]           INT              NOT NULL,
    [cantotal]        BIT              NOT NULL,
    [printout]        BIT              NOT NULL,
    [valuelist]       BIT              NOT NULL,
    [allowimport]     BIT              NOT NULL,
    [mandatory]       BIT              NOT NULL,
    [amendedon]       DATETIME         NOT NULL,
    [lookuptable]     UNIQUEIDENTIFIER NULL,
    [lookupfield]     UNIQUEIDENTIFIER NULL,
    [useforlookup]    BIT              NOT NULL,
    [workflowUpdate]  BIT              NOT NULL,
    [workflowSearch]  BIT              NOT NULL,
    [length]          INT              NOT NULL,
    [tableid]         UNIQUEIDENTIFIER NOT NULL,
    [viewgroupid]     UNIQUEIDENTIFIER NULL,
    [relabel]         BIT              NOT NULL,
    [relabel_param]   NVARCHAR (150)   NULL,
    [FieldCategory]   TINYINT          NOT NULL
);

