CREATE TABLE [dbo].[esr_assignments] (
    [employeeid]                  INT            NOT NULL,
    [AssignmentID]                INT            NULL,
    [AssignmentNumber]            NVARCHAR (30)  NOT NULL,
    [EarliestAssignmentStartDate] DATETIME       NULL,
    [FinalAssignmentEndDate]      DATETIME       NULL,
    [AssignmentStatus]            NVARCHAR (80)  NULL,
    [PayrollPayType]              NVARCHAR (10)  NULL,
    [PayrollName]                 NVARCHAR (80)  NULL,
    [PayrollPeriodType]           NVARCHAR (30)  NULL,
    [AssignmentAddressLine1]      NVARCHAR (60)  NULL,
    [AssignmentAddressLine2]      NVARCHAR (60)  NULL,
    [AssignmentAddressTown]       NVARCHAR (30)  NULL,
    [AssignmentAddressCounty]     NVARCHAR (70)  NULL,
    [AssignmentAddressPostcode]   NVARCHAR (30)  NULL,
    [AssignmentAddressCountry]    NVARCHAR (60)  NULL,
    [SupervisorFlag]              NVARCHAR (1)   NULL,
    [SupervisorAssignmentNumber]  NVARCHAR (30)  NULL,
    [SupervisorEmployeeNumber]    NVARCHAR (30)  NULL,
    [SupervisorFullName]          NVARCHAR (240) NULL,
    [AccrualPlan]                 NVARCHAR (80)  NULL,
    [EmployeeCategory]            NVARCHAR (2)   NULL,
    [AssignmentCategory]          NVARCHAR (30)  NULL,
    [PrimaryAssignment]           BIT            NOT NULL,
    [NormalHours]                 FLOAT          NULL,
    [NormalHoursFrequency]        NVARCHAR (30)  NULL,
    [GradeContractHours]          FLOAT          NULL,
    [NoOfSessions]                FLOAT          NULL,
    [SessionsFrequency]           NVARCHAR (4)   NULL,
    [WorkPatternDetails]          NVARCHAR (80)  NULL,
    [WorkPatternStartDay]         NVARCHAR (30)  NULL,
    [FlexibleWorkingPattern]      NVARCHAR (30)  NULL,
    [AvailabilitySchedule]        NVARCHAR (30)  NULL,
    [Organisation]                NVARCHAR (240) NULL,
    [LegalEntity]                 NVARCHAR (3)   NULL,
    [PositionName]                NVARCHAR (240) NULL,
    [JobRole]                     NVARCHAR (60)  NULL,
    [OccupationCode]              NVARCHAR (5)   NULL,
    [AssignmentLocation]          NVARCHAR (60)  NULL,
    [Grade]                       NVARCHAR (240) NULL,
    [JobName]                     NVARCHAR (120) NULL,
    [Group]                       NVARCHAR (240) NULL,
    [TAndAFlag]                   NVARCHAR (240) NULL,
    [NightWorkerOptOut]           NVARCHAR (3)   NULL,
    [ProjectedHireDate]           NVARCHAR (8)   NULL,
    [VacancyID]                   INT            NULL,
    [createdon]                   DATETIME       NULL,
    [modifiedon]                  DATETIME       NULL,
    [esrAssignID]                 INT            IDENTITY (1, 1) NOT NULL,
    [Active]                      BIT            NOT NULL,
    [CreatedBy]                   INT            NULL,
    [ModifiedBy]                  INT            NULL
);

