CREATE TABLE [dbo].[savedexpenses_previous] (
    [expenseid]                     INT             NOT NULL,
    [bmiles]                        DECIMAL (18, 2) NULL,
    [pmiles]                        DECIMAL (18, 2) NULL,
    [reason]                        NVARCHAR (2500) NULL,
    [receipt]                       BIT             NOT NULL,
    [net]                           MONEY           NOT NULL,
    [vat]                           MONEY           NOT NULL,
    [total]                         MONEY           NOT NULL,
    [subcatid]                      INT             NOT NULL,
    [date]                          DATETIME        NOT NULL,
    [staff]                         TINYINT         NULL,
    [others]                        TINYINT         NULL,
    [companyid]                     INT             NULL,
    [returned]                      BIT             NULL,
    [home]                          BIT             NULL,
    [refnum]                        NVARCHAR (50)   NOT NULL,
    [claimid]                       INT             NOT NULL,
    [plitres]                       INT             NULL,
    [blitres]                       INT             NULL,
    [allowanceamount]               MONEY           NULL,
    [currencyid]                    INT             NULL,
    [attendees]                     NVARCHAR (1000) NULL,
    [tip]                           MONEY           NOT NULL,
    [countryid]                     INT             NULL,
    [foreignvat]                    MONEY           NOT NULL,
    [convertedtotal]                MONEY           NOT NULL,
    [exchangerate]                  FLOAT           NOT NULL,
    [tempallow]                     BIT             NOT NULL,
    [reasonid]                      INT             NULL,
    [normalreceipt]                 BIT             NOT NULL,
    [receiptattached]               BIT             NOT NULL,
    [allowancestartdate]            DATETIME        NULL,
    [allowanceenddate]              DATETIME        NULL,
    [carid]                         INT             NULL,
    [allowancededuct]               MONEY           NULL,
    [allowanceid]                   INT             NULL,
    [nonights]                      TINYINT         NULL,
    [quantity]                      FLOAT           NULL,
    [directors]                     TINYINT         NULL,
    [amountpayable]                 MONEY           NOT NULL,
    [hotelid]                       INT             NULL,
    [primaryitem]                   BIT             NOT NULL,
    [norooms]                       TINYINT         NOT NULL,
    [vatnumber]                     NVARCHAR (50)   NULL,
    [personalguests]                TINYINT         NULL,
    [remoteworkers]                 TINYINT         NULL,
    [accountcode]                   NVARCHAR (50)   NULL,
    [pencepermile]                  MONEY           NULL,
    [basecurrency]                  INT             NULL,
    [globalexchangerate]            FLOAT           NULL,
    [globalbasecurrency]            INT             NULL,
    [globaltotal]                   MONEY           NULL,
    [itemtype]                      TINYINT         NOT NULL,
    [createdon]                     DATETIME        NULL,
    [createdby]                     INT             NULL,
    [modifiedon]                    DATETIME        NULL,
    [modifiedby]                    INT             NULL,
    [mileageid]                     INT             NULL,
    [transactionid]                 INT             NULL,
    [journey_unit]                  TINYINT         NULL,
    [esrAssignID]                   INT             NULL,
    [AssignmentNumber]              NVARCHAR (50)   NULL,
    [CacheExpiry]                   DATETIME        NULL,
    [hometooffice_deduction_method] TINYINT         NULL
);

