CREATE TABLE [dbo].[subcats] (
    [subcatid]                    INT             IDENTITY (1, 1) NOT NULL,
    [categoryid]                  INT             NOT NULL,
    [description]                 NVARCHAR (4000) NULL,
    [subcat]                      NVARCHAR (50)   NOT NULL,
    [vatapp]                      BIT             NOT NULL,
    [vatamount]                   FLOAT           NULL,
    [mileageapp]                  BIT             NOT NULL,
    [staffapp]                    BIT             NOT NULL,
    [othersapp]                   BIT             NOT NULL,
    [vatreceipt]                  BIT             NOT NULL,
    [vattype]                     INT             NOT NULL,
    [tipapp]                      BIT             NOT NULL,
    [pmilesapp]                   BIT             NOT NULL,
    [bmilesapp]                   BIT             NOT NULL,
    [speedoapp]                   BIT             NOT NULL,
    [blitresapp]                  BIT             NOT NULL,
    [plitresapp]                  BIT             NOT NULL,
    [allowance]                   BIT             NOT NULL,
    [allowanceamount]             MONEY           NULL,
    [accountcode]                 NVARCHAR (50)   NULL,
    [attendeesapp]                BIT             NOT NULL,
    [addasnet]                    BIT             NOT NULL,
    [pdcatid]                     INT             NULL,
    [vatpercent]                  TINYINT         NULL,
    [eventinhomeapp]              BIT             NOT NULL,
    [receiptapp]                  BIT             NOT NULL,
    [calculation]                 TINYINT         NOT NULL,
    [passengersapp]               BIT             NOT NULL,
    [nopassengersapp]             BIT             NOT NULL,
    [comment]                     NVARCHAR (4000) NULL,
    [splitentertainment]          BIT             NOT NULL,
    [entertainmentid]             INT             NULL,
    [reimbursable]                BIT             NOT NULL,
    [nonightsapp]                 BIT             NOT NULL,
    [attendeesmand]               BIT             NOT NULL,
    [nodirectorsapp]              BIT             NOT NULL,
    [hotelapp]                    BIT             NOT NULL,
    [noroomsapp]                  BIT             NOT NULL,
    [hotelmand]                   BIT             NOT NULL,
    [vatnumberapp]                BIT             NOT NULL,
    [vatnumbermand]               BIT             NOT NULL,
    [nopersonalguestsapp]         BIT             NOT NULL,
    [noremoteworkersapp]          BIT             NOT NULL,
    [alternateaccountcode]        NVARCHAR (50)   NULL,
    [splitpersonal]               BIT             NOT NULL,
    [splitremote]                 BIT             NOT NULL,
    [personalid]                  INT             NULL,
    [remoteid]                    INT             NULL,
    [vatlimitwithout]             DECIMAL (18)    NOT NULL,
    [vatlimitwith]                DECIMAL (18)    NOT NULL,
    [reasonapp]                   BIT             NOT NULL,
    [otherdetailsapp]             BIT             NOT NULL,
    [CreatedOn]                   DATETIME        NULL,
    [CreatedBy]                   INT             NULL,
    [ModifiedOn]                  DATETIME        NULL,
    [ModifiedBy]                  INT             NULL,
    [shortsubcat]                 NVARCHAR (50)   NULL,
    [fromapp]                     BIT             NOT NULL,
    [toapp]                       BIT             NOT NULL,
    [companyapp]                  BIT             NOT NULL,
    [enableHomeToLocationMileage] BIT             NOT NULL,
    [homeToLocationType]          TINYINT         NULL,
    [mileageCategory]             INT             NULL,
    [isRelocationMileage]         BIT             NOT NULL,
    [reimbursableSubcatID]        INT             NULL,
    [allowHeavyBulkyMileage]      BIT             NOT NULL
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'1=calculate;2=flag', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'subcats', @level2type = N'COLUMN', @level2name = N'homeToLocationType';

