CREATE TYPE [dbo].[ApiBatchSaveCarType] AS TABLE (
    [carid]                  INT            NULL,
    [employeeid]             INT            NULL,
    [startdate]              DATETIME       NULL,
    [enddate]                DATETIME       NULL,
    [make]                   NVARCHAR (500) NULL,
    [model]                  NVARCHAR (500) NULL,
    [registration]           NVARCHAR (500) NULL,
    [mileageid]              INT            NULL,
    [cartypeid]              TINYINT        NULL,
    [active]                 BIT            NULL,
    [odometer]               BIGINT         NULL,
    [fuelcard]               BIT            NULL,
    [endodometer]            INT            NULL,
    [taxexpiry]              DATETIME       NULL,
    [taxlastchecked]         DATETIME       NULL,
    [taxcheckedby]           INT            NULL,
    [mottestnumber]          NVARCHAR (500) NULL,
    [motlastchecked]         DATETIME       NULL,
    [motcheckedby]           INT            NULL,
    [motexpiry]              DATETIME       NULL,
    [insurancenumber]        NVARCHAR (500) NULL,
    [insuranceexpiry]        DATETIME       NULL,
    [insurancelastchecked]   DATETIME       NULL,
    [insurancecheckedby]     INT            NULL,
    [serviceexpiry]          DATETIME       NULL,
    [servicelastchecked]     DATETIME       NULL,
    [servicecheckedby]       INT            NULL,
    [CreatedOn]              DATETIME       NULL,
    [CreatedBy]              INT            NULL,
    [ModifiedOn]             DATETIME       NULL,
    [ModifiedBy]             INT            NULL,
    [default_unit]           TINYINT        NULL,
    [enginesize]             INT            NULL,
    [approved]               BIT            NULL,
    [exemptFromHomeToOffice] BIT            NULL,
    [taxAttachID]            INT            NULL,
    [MOTAttachID]            INT            NULL,
    [insuranceAttachID]      INT            NULL,
    [serviceAttachID]        INT            NULL);

