CREATE TYPE [dbo].[ApiBatchSaveEmployeeType] AS TABLE (
    [employeeid]                INT             NULL,
    [username]                  NVARCHAR (500)  NULL,
    [password]                  NVARCHAR (500)  NULL,
    [title]                     NVARCHAR (500)  NULL,
    [firstname]                 NVARCHAR (500)  NULL,
    [surname]                   NVARCHAR (500)  NULL,
    [mileagetotal]              INT             NULL,
    [email]                     NVARCHAR (500)  NULL,
    [currefnum]                 INT             NULL,
    [curclaimno]                INT             NULL,
    [speedo]                    INT             NULL,
    [payroll]                   NVARCHAR (500)  NULL,
    [position]                  NVARCHAR (500)  NULL,
    [telno]                     NVARCHAR (500)  NULL,
    [creditor]                  NVARCHAR (500)  NULL,
    [archived]                  BIT             NULL,
    [groupid]                   INT             NULL,
    [roleid]                    INT             NULL,
    [hint]                      NVARCHAR (1000) NULL,
    [lastchange]                SMALLDATETIME   NULL,
    [additems]                  INT             NULL,
    [cardnum]                   NVARCHAR (500)  NULL,
    [userole]                   BIT             NULL,
    [costcodeid]                INT             NULL,
    [departmentid]              INT             NULL,
    [extension]                 NVARCHAR (500)  NULL,
    [pagerno]                   NVARCHAR (500)  NULL,
    [mobileno]                  NVARCHAR (500)  NULL,
    [faxno]                     NVARCHAR (500)  NULL,
    [homeemail]                 NVARCHAR (500)  NULL,
    [linemanager]               INT             NULL,
    [advancegroupid]            INT             NULL,
    [mileage]                   INT             NULL,
    [mileageprev]               INT             NULL,
    [customiseditems]           BIT             NULL,
    [active]                    BIT             NULL,
    [primarycountry]            INT             NULL,
    [primarycurrency]           INT             NULL,
    [verified]                  BIT             NULL,
    [licenceexpiry]             DATETIME        NULL,
    [licencelastchecked]        DATETIME        NULL,
    [licencecheckedby]          INT             NULL,
    [licencenumber]             NVARCHAR (500)  NULL,
    [groupidcc]                 INT             NULL,
    [groupidpc]                 INT             NULL,
    [CreatedOn]                 DATETIME        NULL,
    [CreatedBy]                 INT             NULL,
    [ModifiedOn]                DATETIME        NULL,
    [ModifiedBy]                INT             NULL,
    [country]                   NVARCHAR (500)  NULL,
    [ninumber]                  NVARCHAR (500)  NULL,
    [maidenname]                NVARCHAR (500)  NULL,
    [middlenames]               NVARCHAR (500)  NULL,
    [gender]                    NVARCHAR (500)  NULL,
    [dateofbirth]               DATETIME        NULL,
    [hiredate]                  DATETIME        NULL,
    [terminationdate]           DATETIME        NULL,
    [homelocationid]            INT             NULL,
    [officelocationid]          INT             NULL,
    [applicantnumber]           NVARCHAR (500)  NULL,
    [applicantactivestatusflag] BIT             NULL,
    [passwordMethod]            TINYINT         NULL,
    [name]                      NVARCHAR (500)  NULL,
    [accountnumber]             NVARCHAR (500)  NULL,
    [accounttype]               NVARCHAR (500)  NULL,
    [sortcode]                  NVARCHAR (500)  NULL,
    [reference]                 NVARCHAR (500)  NULL,
    [localeID]                  INT             NULL,
    [NHSTrustID]                INT             NULL,
    [logonCount]                INT             NULL,
    [retryCount]                INT             NULL,
    [firstLogon]                BIT             NULL,
    [licenceAttachID]           INT             NULL,
    [defaultSubAccountId]       INT             NULL,
    [CacheExpiry]               DATETIME        NULL,
    [supportPortalAccountID]    INT             NULL,
    [supportPortalPassword]     NVARCHAR (500)  NULL,
    [CreationMethod]            TINYINT         NULL,
    [mileagetotaldate]          DATETIME        NULL,
    [adminonly]                 BIT             NULL,
    [locked]                    BIT             NULL,
    [ESRPersonId]               BIGINT          NULL,
    [preferredname]             NVARCHAR (500)  NULL,
    [employeenumber]            NVARCHAR (500)  NULL,
    [esrpersontype]             NVARCHAR (500)  NULL,
    [nhsuniqueid]               NVARCHAR (500)  NULL,
    [esreffectivestartdate]     DATETIME        NULL,
    [esreffectiveenddate]       DATETIME        NULL);

