CREATE TYPE [dbo].[ApiBatchSaveEsrPositionType] AS TABLE (
    [ESRPositionId]             BIGINT          NULL,
    [EffectiveFromDate]         DATETIME        NULL,
    [EffectiveToDate]           DATETIME        NULL,
    [PositionNumber]            BIGINT          NULL,
    [PositionName]              NVARCHAR (500)  NULL,
    [BudgetedFTE]               DECIMAL (13, 5) NULL,
    [SubjectiveCode]            NVARCHAR (500)  NULL,
    [JobStaffGroup]             NVARCHAR (500)  NULL,
    [JobRole]                   NVARCHAR (500)  NULL,
    [OccupationCode]            NVARCHAR (500)  NULL,
    [Payscale]                  NVARCHAR (500)  NULL,
    [GradeStep]                 NVARCHAR (500)  NULL,
    [ISARegulatedPost]          NVARCHAR (500)  NULL,
    [ESROrganisationId]         BIGINT          NULL,
    [HiringStatus]              NVARCHAR (500)  NULL,
    [PositionType]              NVARCHAR (500)  NULL,
    [OHProcessingEligible]      NVARCHAR (500)  NULL,
    [EPPFlag]                   NVARCHAR (500)  NULL,
    [DeaneryPostNumber]         NVARCHAR (500)  NULL,
    [ManagingDeaneryBody]       NVARCHAR (500)  NULL,
    [WorkplaceOrgCode]          NVARCHAR (500)  NULL,
    [ESRLastUpdateDate]         DATETIME        NULL,
    [SubjectiveCodeDescription] NVARCHAR (500)  NULL);

