CREATE TYPE [dbo].[ApiBatchSaveEsrAssignmentType] AS TABLE (
    [esrAssignID]                 INT             NULL,
    [ESRPersonId]                 BIGINT          NULL,
    [employeeid]                  INT             NULL,
    [AssignmentID]                BIGINT          NULL,
    [EffectiveStartDate]          DATETIME        NULL,
    [EffectiveEndDate]            DATETIME        NULL,
    [EarliestAssignmentStartDate] DATETIME        NULL,
    [AssignmentType]              NVARCHAR (500)  NULL,
    [AssignmentNumber]            NVARCHAR (500)  NULL,
    [SystemAssignmentStatus]      NVARCHAR (500)  NULL,
    [AssignmentStatus]            NVARCHAR (500)  NULL,
    [EmployeeStatusFlag]          NVARCHAR (500)  NULL,
    [PayrollName]                 NVARCHAR (500)  NULL,
    [PayrollPeriodType]           NVARCHAR (500)  NULL,
    [EsrLocationId]               BIGINT          NULL,
    [SupervisorFlag]              NVARCHAR (500)  NULL,
    [SupervisorPersonId]          BIGINT          NULL,
    [SupervisorAssignmentId]      BIGINT          NULL,
    [SupervisorAssignmentNumber]  NVARCHAR (500)  NULL,
    [DepartmentManagerAssignmentId]   BIGINT          NULL,
    [EmployeeCategory]            NVARCHAR (500)  NULL,
    [AssignmentCategory]          NVARCHAR (500)  NULL,
    [PrimaryAssignmentString]     NVARCHAR (500)  NULL,
    [PrimaryAssignment]           BIT             NULL,
    [NormalHours]                 FLOAT (53)      NULL,
    [NormalHoursFrequency]        NVARCHAR (500)  NULL,
    [GradeContractHours]          FLOAT (53)      NULL,
    [Fte]                         DECIMAL (22, 3) NULL,
    [FlexibleWorkingPattern]      NVARCHAR (500)  NULL,
    [EsrOrganisationId]           BIGINT          NULL,
    [EsrPositionId]               BIGINT          NULL,
    [PositionName]                NVARCHAR (500)  NULL,
    [Grade]                       NVARCHAR (500)  NULL,
    [GradeStep]                   NVARCHAR (500)  NULL,
    [StartDateInGrade]            DATETIME        NULL,
    [AnnualSalaryValue]           MONEY           NULL,
    [JobName]                     NVARCHAR (500)  NULL,
    [Group]                       NVARCHAR (500)  NULL,
    [TAndAFlag]                   NVARCHAR (500)  NULL,
    [NightWorkerOptOut]           NVARCHAR (500)  NULL,
    [ProjectedHireDate]           DATETIME        NULL,
    [VacancyID]                   INT             NULL,
    [ContractEndDate]             DATETIME        NULL,
    [IncrementDate]               DATETIME        NULL,
    [MaximumPartTimeFlag]         NVARCHAR (500)  NULL,
    [AfcFlag]                     NVARCHAR (500)  NULL,
    [EsrLastUpdate]               DATETIME        NULL,
    [LastWorkingDay]              DATETIME        NULL,
    [eKSFSpinalPoint]             NVARCHAR (500)  NULL,
    [ManagerFlag]                 NVARCHAR (500)  NULL,
    [FinalAssignmentEndDate]      DATETIME        NULL,
    [Active]                      BIT             NULL,
    [SupervisorEsrAssignId]       INT             NULL,
    [SignOffOwner]                VARCHAR  (39)   NULL);
